In [204]:
!lscpu

'lscpu' is not recognized as an internal or external command,
operable program or batch file.

# Library

In [2]:
# Import các thư viện cần thiết

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Flatten, Input
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

import os
# import cv2


import matplotlib.pyplot as plt
import seaborn as sns

# Mining Dataset

# Xử lý outfits

In [61]:
ROOT= r"E:\DoCode\CD2\source\Source\get_hrs_rs\rs\get10k_data\output_10k_sample"
ROOT_PRESS = r"E:\DoCode\CD2\source\Source\get_hrs_rs\rs\get10k_data\output_10k_sample\preprocess"

In [5]:
with open(rf"{ROOT_PRESS}\outfits_10k.csv", 'r') as f:
    lines = f.readlines()

# In các dòng đầu tiên để kiểm tra định dạng
for i in range(5):
    print(lines[i])

id;name;description;group;owner;timeCreated;retailPrice;pricePerWeek;pricePerMonth;outfit_tags;tag_categories

outfit.ffd83466cdb84a0dba02339aa0c72f73;Mariposa Earrings AB-Crystal;The Mariposa Earrings are the perfect statement jewelry. We recommend wearing your hair up to show them off. ;group.4f70fa1707b559c0db341fa53997e52f;o_00037;2019-03-22 11:52:11.000;1600.0;250.0;500.0;['Jewelry', 'Cecilie Melli', 'Statement', 'Metallic', 'Formal'];['Category', 'Brand', 'Occasion', 'Details', 'Occasion']

outfit.ff08dd87bf144defaa332eac0bf5bd4e;The Gisele Dress;This mini satin dress is made in a beautiful olive color, and features a V-neckline and puffed sleeves. The pleated detail in the front gives it an edge. ;group.a65e95a2f1823633a8d0b07b7fff2e7b;o_00740;2020-02-27 12:51:07.073;2500.0;750.0;1500.0;['Statement', 'S', 'Bastet Noir', 'Mini', 'Dresses', 'Women', 'Green', 'Silk', 'Multi Season'];['Occasion', 'Size', 'Brand', 'Length', 'Category', 'Gender', 'Color', 'Material', 'Seasons']

outfit.fec66293d37940b79dde2c1acd761fe3;Evie Deauville Mauve Long Sleeve Dress;The Evie Long Sleeve Dress is made in a flowy chiffon quality, and features elastic sleeves and waistline. This ensures a perfect and comfortable fit, as well as a feminine silhouette.;group.fcc139e28abeaf451c19d46bf311fcb0;o_00530;2019-09-23 09:47:20.000;2200.0;660.0;1320.0;['Ruffles', 'Women', 'Midi', 'Purple', 'Multi Season', 'Synthetic', 'Stretchy', 'Dresses', 'Untold Stories', 'Statement', 'L', 'Viscose', 'Pattern'];['Details', 'Gender', 'Length', 'Color', 'Seasons', 'Material', 'Fit', 'Category', 'Brand', 'Occasion', 'Size', 'Material', 'Details']

outfit.feaa16af0f6b4a96b65f8a29ace77979;Tahiti Earrings Green/Gold;The Tahiti Earrings are the perfect statement jewelry. We recommend wearing your hair up to show them off. ;group.d940849fd6a77efb5fd69121e43bb3ad;o_00037;2019-03-22 11:34:50.000;1600.0;590.0;1180.0;['Multi Season', 'Jewelry', 'Formal', 'Green', 'Metallic', 'Women', 'Onesize', 'Statement', 'Cecilie Melli'];['Seasons', 'Category', 'Occasion', 'Color', 'Details', 'Gender', 'Size', 'Occasion', 'Brand']

In [6]:
outfits = pd.read_csv(rf"{ROOT_PRESS}\outfits_10k.csv", sep=';', on_bad_lines='skip')

In [7]:
import ast

# Chuyển đổi chuỗi thành danh sách
outfits['outfit_tags'] = outfits['outfit_tags'].apply(ast.literal_eval)
outfits['tag_categories'] = outfits['tag_categories'].apply(ast.literal_eval)

In [8]:
outfits.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              2223 non-null   str
 1   name            2223 non-null   str
 2   description     2206 non-null   str
 3   group           2223 non-null   str
 4   owner           2223 non-null   str
 5   timeCreated     2223 non-null   str
 6   retailPrice     2220 non-null   float64
 7   pricePerWeek    2223 non-null   float64
 8   pricePerMonth   2223 non-null   float64
 9   outfit_tags     2223 non-null   object
 10  tag_categories  2223 non-null   object
dtypes: float64(3), object(2), str(6)
memory usage: 191.2+ KB

In [9]:
outfits.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,"[Jewelry, Cecilie Melli, Statement, Metallic, ...","[Category, Brand, Occasion, Details, Occasion]"
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,"[Statement, S, Bastet Noir, Mini, Dresses, Wom...","[Occasion, Size, Brand, Length, Category, Gend..."
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,"[Ruffles, Women, Midi, Purple, Multi Season, S...","[Details, Gender, Length, Color, Seasons, Mate..."
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,"[Multi Season, Jewelry, Formal, Green, Metalli...","[Seasons, Category, Occasion, Color, Details, ..."
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,"[Everyday, Midi, Ruffles, Wrap, Skirts, Women,...","[Occasion, Length, Details, Fit, Category, Gen..."

In [10]:
outfits['outfit_tags'][0][0]

'Jewelry'

In [11]:
outfits['group'][0]

'group.4f70fa1707b559c0db341fa53997e52f'

In [12]:
outfits.isnull().sum()

id                 0
name               0
description       17
group              0
owner              0
timeCreated        0
retailPrice        3
pricePerWeek       0
pricePerMonth      0
outfit_tags        0
tag_categories     0
dtype: int64

In [13]:
print(outfits[['name', 'description']].isnull().sum())

name            0
description    17
dtype: int64

In [14]:
# Lấy các dòng có cột 'name' là null
outfits_null_name = outfits[outfits['name'].isnull()]

# Hiển thị kết quả
outfits_null_name

Empty DataFrame
Columns: [id, name, description, group, owner, timeCreated, retailPrice, pricePerWeek, pricePerMonth, outfit_tags, tag_categories]
Index: []

In [15]:
null_outfit_ids = outfits[outfits['name'].isnull()]['id']
null_outfit_ids

Series([], Name: id, dtype: str)

với cột name loại bỏ missing

In [16]:
outfits = outfits.dropna(subset=['name'])

vơí cột des giữ nguyên thay missing bằng "No description available" nghĩa là không mô tả khả dụng, đảm bảo đầu vào cho mô hình ( tùy trường hợp )

In [17]:
outfits['description'] = outfits['description'].fillna('No description available')

In [18]:
outfits.reset_index(drop=True, inplace=True)  # Đặt lại chỉ mục

In [19]:
outfits.isnull().sum()

id                0
name              0
description       0
group             0
owner             0
timeCreated       0
retailPrice       3
pricePerWeek      0
pricePerMonth     0
outfit_tags       0
tag_categories    0
dtype: int64

In [20]:
outfits.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              2223 non-null   str
 1   name            2223 non-null   str
 2   description     2223 non-null   str
 3   group           2223 non-null   str
 4   owner           2223 non-null   str
 5   timeCreated     2223 non-null   str
 6   retailPrice     2220 non-null   float64
 7   pricePerWeek    2223 non-null   float64
 8   pricePerMonth   2223 non-null   float64
 9   outfit_tags     2223 non-null   object
 10  tag_categories  2223 non-null   object
dtypes: float64(3), object(2), str(6)
memory usage: 191.2+ KB

In [21]:
outfits.describe()

        retailPrice  pricePerWeek  pricePerMonth
count   2220.000000   2223.000000    2223.000000
mean    3401.374775    709.781826    1396.914530
std     4231.879141    197.717988     430.434391
min      266.000000    150.000000     200.000000
25%     1600.000000    590.000000    1180.000000
50%     2300.000000    630.000000    1260.000000
75%     3500.000000    900.000000    1800.000000
max    80000.000000   1300.000000    2600.000000

In [22]:
outfits.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,"[Jewelry, Cecilie Melli, Statement, Metallic, ...","[Category, Brand, Occasion, Details, Occasion]"
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,"[Statement, S, Bastet Noir, Mini, Dresses, Wom...","[Occasion, Size, Brand, Length, Category, Gend..."
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,"[Ruffles, Women, Midi, Purple, Multi Season, S...","[Details, Gender, Length, Color, Seasons, Mate..."
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,"[Multi Season, Jewelry, Formal, Green, Metalli...","[Seasons, Category, Occasion, Color, Details, ..."
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,"[Everyday, Midi, Ruffles, Wrap, Skirts, Women,...","[Occasion, Length, Details, Fit, Category, Gen..."

# Xử lý picture_triplets

In [24]:
with open(rf"{ROOT_PRESS}\picture_triplets_10k.csv", 'r') as f:
    lines = f.readlines()

# In các dòng đầu tiên để kiểm tra định dạng
for i in range(5):
    print(lines[i])

picture.id;outfit.id;displayOrder;file_name

picture.0000cdba64314d84a49ed1c266589cc0;outfit.794483397da8425a813301eecf9828c6;0;0000cdba64314d84a49ed1c266589cc0.jpg

picture.0010c2e161154d6893734981d5455e76;outfit.9387d05b47f906c5;0;0010c2e161154d6893734981d5455e76.jpg

picture.0013342f663843d4b7397b4b88b98e6d;outfit.b24fc57f02ac4e4c9061761ca18d9d3c;0;0013342f663843d4b7397b4b88b98e6d.jpg

picture.001a58ea68da426384567b8cccc0c8a6;outfit.e989b8cb4a814d97b642e1cb326f47e6;0;001a58ea68da426384567b8cccc0c8a6.jpg

In [25]:

pictures= pd.read_csv(rf"{ROOT_PRESS}\picture_triplets_10k.csv", sep=';', on_bad_lines='skip')

In [26]:
pictures.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    2223 non-null   str
 1   outfit.id     2223 non-null   str
 2   displayOrder  2223 non-null   int64
 3   file_name     2223 non-null   str
dtypes: int64(1), str(3)
memory usage: 69.6 KB

In [27]:
pictures.head()

,picture.id,outfit.id,displayOrder,file_name
0,picture.0000cdba64314d84a49ed1c266589cc0,outfit.794483397da8425a813301eecf9828c6,0,0000cdba64314d84a49ed1c266589cc0.jpg
1,picture.0010c2e161154d6893734981d5455e76,outfit.9387d05b47f906c5,0,0010c2e161154d6893734981d5455e76.jpg
2,picture.0013342f663843d4b7397b4b88b98e6d,outfit.b24fc57f02ac4e4c9061761ca18d9d3c,0,0013342f663843d4b7397b4b88b98e6d.jpg
3,picture.001a58ea68da426384567b8cccc0c8a6,outfit.e989b8cb4a814d97b642e1cb326f47e6,0,001a58ea68da426384567b8cccc0c8a6.jpg
4,picture.0021a36dd3b04f7ebff9430b7801d44d,outfit.070bc7bd72154b5a805f52f086fb72ed,0,0021a36dd3b04f7ebff9430b7801d44d.jpg

In [28]:
null_outfit_ids

Series([], Name: id, dtype: str)

In [29]:
# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
pictures_filter = pictures[pictures['outfit.id'].isin(null_outfit_ids)]
pictures_filter

Empty DataFrame
Columns: [picture.id, outfit.id, displayOrder, file_name]
Index: []

In [30]:
# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
pictures = pictures[~pictures['outfit.id'].isin(null_outfit_ids)]

In [31]:
pictures.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    2223 non-null   str
 1   outfit.id     2223 non-null   str
 2   displayOrder  2223 non-null   int64
 3   file_name     2223 non-null   str
dtypes: int64(1), str(3)
memory usage: 69.6 KB

# Xử lý user_activity_triplets

In [33]:
with open(rf"{ROOT_PRESS}\\user_activity_triplets_10k.csv", 'r') as f:
    lines = f.readlines()

# In các dòng đầu tiên để kiểm tra định dạng
for i in range(5):
    print(lines[i])

customer.id;outfit.id;rentalPeriod.start;rentalPeriod.end

1128;outfit.03bdf90c39e1431685d49ce8309dd242;2021-10-11;2021-11-11

1128;outfit.c46affd5f8ee4749b1f8e7d4ff47f3ff;2021-10-11;2021-11-11

1128;outfit.900dd323358401b1;2022-02-22;2022-03-11

1128;outfit.0630ef7d996d4c489b4e54e85bd09e5a;2021-11-11;2021-12-15

In [34]:

transactions = pd.read_csv(rf"{ROOT_PRESS}\\user_activity_triplets_10k.csv", sep=';', on_bad_lines='skip')

In [35]:
transactions['rentalPeriod.start'] = pd.to_datetime(transactions['rentalPeriod.start'])
transactions['rentalPeriod.end'] = pd.to_datetime(transactions['rentalPeriod.end'])

In [36]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer.id         10000 non-null  int64
 1   outfit.id           10000 non-null  str
 2   rentalPeriod.start  10000 non-null  datetime64[us]
 3   rentalPeriod.end    10000 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(1)
memory usage: 312.6 KB

In [37]:
transactions.head()

,customer.id,outfit.id,rentalPeriod.start,rentalPeriod.end
0,1128,outfit.03bdf90c39e1431685d49ce8309dd242,2021-10-11,2021-11-11
1,1128,outfit.c46affd5f8ee4749b1f8e7d4ff47f3ff,2021-10-11,2021-11-11
2,1128,outfit.900dd323358401b1,2022-02-22,2022-03-11
3,1128,outfit.0630ef7d996d4c489b4e54e85bd09e5a,2021-11-11,2021-12-15
4,6310,outfit.bd37bc0ed1857fb5,2022-07-07,2022-08-06

In [38]:
null_outfit_ids

Series([], Name: id, dtype: str)

In [39]:
# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
transactions_filter = transactions[transactions['outfit.id'].isin(null_outfit_ids)]
transactions_filter

Empty DataFrame
Columns: [customer.id, outfit.id, rentalPeriod.start, rentalPeriod.end]
Index: []

In [40]:

# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
transactions_cleaned = transactions[~transactions['outfit.id'].isin(null_outfit_ids)]

In [41]:
transactions_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer.id         10000 non-null  int64
 1   outfit.id           10000 non-null  str
 2   rentalPeriod.start  10000 non-null  datetime64[us]
 3   rentalPeriod.end    10000 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(1)
memory usage: 312.6 KB

# Preprocessing

In [42]:
outfits.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              2223 non-null   str
 1   name            2223 non-null   str
 2   description     2223 non-null   str
 3   group           2223 non-null   str
 4   owner           2223 non-null   str
 5   timeCreated     2223 non-null   str
 6   retailPrice     2220 non-null   float64
 7   pricePerWeek    2223 non-null   float64
 8   pricePerMonth   2223 non-null   float64
 9   outfit_tags     2223 non-null   object
 10  tag_categories  2223 non-null   object
dtypes: float64(3), object(2), str(6)
memory usage: 191.2+ KB

In [43]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = outfits['id'].nunique()
print(f"Số phần tử không trùng lặpe: {unique_count}")

Số phần tử không trùng lặpe: 2223

In [44]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer.id         10000 non-null  int64
 1   outfit.id           10000 non-null  str
 2   rentalPeriod.start  10000 non-null  datetime64[us]
 3   rentalPeriod.end    10000 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(1)
memory usage: 312.6 KB

In [45]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = transactions['outfit.id'].nunique()
print(f"Số phần tử không trùng lặp: {unique_count}")

Số phần tử không trùng lặp: 2223

In [46]:
pictures.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    2223 non-null   str
 1   outfit.id     2223 non-null   str
 2   displayOrder  2223 non-null   int64
 3   file_name     2223 non-null   str
dtypes: int64(1), str(3)
memory usage: 69.6 KB

In [47]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = pictures['outfit.id'].nunique()
print(f"Số phần tử không trùng lặp: {unique_count}")

Số phần tử không trùng lặp: 2223

In [48]:
# Lấy danh sách các outfit.id từ outfits và transactions
outfit_ids = set(outfits['id'])  # Cột 'id' từ outfits
transaction_outfit_ids = set(transactions['outfit.id'])  # Cột 'outfit.id' từ transactions

# Tìm các id có trong transactions nhưng không có trong outfits
foreign_ids = transaction_outfit_ids - outfit_ids

# Kết quả
if foreign_ids:
    print("Các outfit.id ngoại lai (có trong transactions nhưng không có trong outfits):")
    print(foreign_ids)
else:
    print("Không có outfit.id ngoại lai.")

Không có outfit.id ngoại lai.

In [49]:
# Lấy danh sách các outfit.id từ outfits và transactions
pictures_ids = set(pictures['outfit.id'])  # Cột 'id' từ outfits
transaction_outfit_ids = set(transactions['outfit.id'])  # Cột 'outfit.id' từ transactions

# Tìm các id có trong transactions nhưng không có trong outfits
foreign_ids = transaction_outfit_ids - pictures_ids

# Kết quả
if foreign_ids:
    print("Các outfit.id (trong pictures ) ngoại lai (có trong transactions nhưng không có trong outfits):")
    print(foreign_ids)
else:
    print("Không có outfit.id (trong pictures ) ngoại lai.")

Không có outfit.id (trong pictures ) ngoại lai.

In [249]:
transactions = transactions[transactions['outfit.id'].isin(pictures['outfit.id'])]

In [50]:
# Kiểm tra các id có trong transactions nhưng không có trong outfits
foreign_ids_df = transactions[~transactions['outfit.id'].isin(outfits['id'])]

# Kết quả
if not foreign_ids_df.empty:
    print("Các giao dịch có outfit.id không tồn tại trong outfits:")
    print(foreign_ids_df)
else:
    print("Tất cả outfit.id trong transactions đều có trong outfits.")

Tất cả outfit.id trong transactions đều có trong outfits.

In [51]:
# Kiểm tra các id có trong transactions nhưng không có trong pictures
foreign_ids_df = transactions[~transactions['outfit.id'].isin(pictures['outfit.id'])]

# Kết quả
if not foreign_ids_df.empty:
    print("Các giao dịch có outfit.id không tồn tại trong pictures:")
    print(foreign_ids_df)
else:
    print("Tất cả outfit.id trong transactions đều có trong pictures.")

Tất cả outfit.id trong transactions đều có trong pictures.

In [63]:
import time

# Đổi tên cột
data_collect = transactions.rename(columns={
    "outfit.id": "item_id_original",
    "customer.id": "user_id_original",
    "rentalPeriod.start": "time"
})

# Chuyển cột "time" thành UNIX Timestamp (Epoch Time)
data_collect["time"] = pd.to_datetime(data_collect["time"])
data_collect["time"] = data_collect["time"].apply(lambda x: int(time.mktime(x.timetuple())))


data_collect = data_collect[['user_id_original', 'item_id_original' , 'time']]

# Lưu DataFrame đã xử lý thành file CSV mới
output_path = rf"{ROOT}\dataset_VCR.csv"
data_collect.to_csv(output_path, index=False)
    
# Hiển thị dữ liệu đã xử lý
data_collect.head()

   user_id_original                         item_id_original        time
0              1128  outfit.03bdf90c39e1431685d49ce8309dd242  1633885200
1              1128  outfit.c46affd5f8ee4749b1f8e7d4ff47f3ff  1633885200
2              1128                  outfit.900dd323358401b1  1645462800
3              1128  outfit.0630ef7d996d4c489b4e54e85bd09e5a  1636563600
4              6310                  outfit.bd37bc0ed1857fb5  1657126800

In [64]:
data_collect.shape

(10000, 3)

In [65]:
data_collect["user_id_original"].nunique()

711

In [66]:
data_collect["item_id_original"].nunique()

2223

# Xử lý default df

In [67]:
# Đọc file CSV
df = pd.read_csv(rf"{ROOT}\dataset_VCR.csv")

# Lấy 3 cột chính
df

      user_id_original                         item_id_original        time
0                 1128  outfit.03bdf90c39e1431685d49ce8309dd242  1633885200
1                 1128  outfit.c46affd5f8ee4749b1f8e7d4ff47f3ff  1633885200
2                 1128                  outfit.900dd323358401b1  1645462800
3                 1128  outfit.0630ef7d996d4c489b4e54e85bd09e5a  1636563600
4                 6310                  outfit.bd37bc0ed1857fb5  1657126800
...                ...                                      ...         ...
9995              3189  outfit.706635d443e040d2a4ae9e6862a95961  1663952400
9996              3320  outfit.e0f170b8b51f4ae4a7e00047b9ea8d79  1665248400
9997              7376  outfit.9bd9226c247f4ee8a64be90ee310fd8b  1626627600
9998              5837                  outfit.bb35c791b2bfa191  1619974800
9999              5837                  outfit.ad6f853b5c31b6f5  1619974800

[10000 rows x 3 columns]

In [68]:
df.shape

(10000, 3)

In [69]:
df['user_id_original'].value_counts()

user_id_original
3267    126
6907    124
3094    116
675     103
7411     93
       ...
2788      3
1211      3
1680      3
747       3
2219      3
Name: count, Length: 711, dtype: int64

In [70]:
df['item_id_original'].value_counts()

item_id_original
outfit.b4e582b38a10f6bf                    21
outfit.aa76777d3b9d4073a342e2093e4ea1e2    20
outfit.2ea36f84cb12427686eed685f97f2a8f    19
outfit.b45f71cef3bf96b3                    19
outfit.fd816aa2311d45c78fd0ab2d663a177a    18
                                           ..
outfit.e5573a0b879d4a31b02ff8dfe70ea20f     1
outfit.0ac1ac7d05ed43eeb9cb12c66cae3d18     1
outfit.092ee39646f34dafac13607ee3c17215     1
outfit.296da213b6db4d99817dea16407654f0     1
outfit.776c13028a5e48b7899f4a9057ee8e18     1
Name: count, Length: 2223, dtype: int64

In [77]:


def process_data(df, random_percent=0.1, n_core=10, random_state=42):
    """
    Xử lý dataframe theo quy trình
    1. Lấy random k% số phần tử và lưu lại 
       - random_percent: phần trăm dữ liệu muốn lấy (0-1)
       - random_state: tái tạo kết quả
    2. Áp dụng n-core
       - n_core: số lượng tương tác tối thiểu
    3. Mapping ID cho User và Item
    4. Chia thành train/val/test
    
    """
    BASE = r"E:\DoCode\CD2\source\Source\get_hrs_rs\rs\get10k_data\output_10k_sample"
    # 1. Lấy random k% số phần tử
    np.random.seed(random_state)
    n_samples = int(len(df) * random_percent)
    sampled_df = df.sample(n=n_samples, random_state=random_state)
    
    # Lưu file csv với k% phần tử
    # sampled_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}.csv', index=False)
    
    # 2. Áp dụng n-core
    # Đếm số lượng tương tác của mỗi user và item
    user_counts = sampled_df['user_id_original'].value_counts()
    # item_counts = sampled_df['item_id_original'].value_counts()
    
    # Lọc các user và item có ít nhất n tương tác
    valid_users = user_counts[user_counts >= n_core].index
    # valid_items = item_counts[item_counts >= n_core].index
    
    # filtered_df = sampled_df[
    #     sampled_df['user_id_original'].isin(valid_users) & 
    #     sampled_df['item_id_original'].isin(valid_items)
    # ]
    
    # Giữ lại dữ liệu của các user hợp lệ
    filtered_df = sampled_df[sampled_df['user_id_original'].isin(valid_users)]
    
    # 3. Mapping ID
    # Tạo mapping cho user
    unique_users = filtered_df['user_id_original'].unique()
    user_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_users , start=0)}
    
    # Tạo mapping cho item
    unique_items = filtered_df['item_id_original'].unique()
    item_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_items , start=0)}
    
    # Áp dụng mapping
    mapped_df = filtered_df.copy()
    mapped_df['user_id'] = mapped_df['user_id_original'].map(user_id_map)
    mapped_df['item_id'] = mapped_df['item_id_original'].map(item_id_map)

    print(mapped_df.head())
    # Lưu file csv sau mapping
    out_path = rf"{BASE}\dataset_VCR_{random_percent}_{random_state}_{n_core}.csv"
    mapped_df.to_csv(out_path, index=False)
    print(f"✅ Đã lưu: {out_path}")
    print(f"   Users: {mapped_df['user_id'].nunique()}")
    print(f"   Items: {mapped_df['item_id'].nunique()}")
    print(f"   Records: {len(mapped_df)}")
    
    # # 4. Chia thành train/val/test
    # # Sắp xếp theo thời gian
    # mapped_df = mapped_df.sort_values('time')
    
    # # Chia theo tỷ lệ 70/15/15
    # train_df, temp_df = train_test_split(mapped_df, test_size=0.3, shuffle=False)
    # val_df, test_df = train_test_split(temp_df, test_size=0.5, shuffle=False)
    
    # Lưu các file
    # train_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}_train.csv', index=False)
    # val_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}_val.csv', index=False)
    # test_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}_test.csv', index=False)
    
    # return train_df, val_df, test_df, user_id_map, item_id_map

# Sử dụng hàm
process_data(
    df, 
    random_percent=1,  # Lấy 20% dữ liệu
    n_core=5,           # Loại bỏ user/item có ít hơn 5 tương tác
    random_state=42     # Seed để tái tạo kết quả
)

# In thông tin về kết quả
# print(f"Số lượng users sau khi mapping: {len(user_mapping)}")
# print(f"Số lượng items sau khi mapping: {len(item_mapping)}")
# print("\nKích thước các tập dữ liệu:")
# print(f"Train: {len(train)} rows")
# print(f"Validation: {len(val)} rows")
# print(f"Test: {len(test)} rows")

      user_id_original                         item_id_original        time  \
6252               446  outfit.7cc6bd8e645a41d2837976a0d09e3ca9  1570467600
4684              7367  outfit.7ee7542297f944ecb49f4fe5b44728f7  1680454800
1731              6696  outfit.e8e4d130fa3e4f108127dc74fd854a75  1621270800
4742              1878  outfit.7395b78d10084aebb906f8f83bfd89cc  1658854800
4521              4906  outfit.c929e1bd6aa940f7a34c16471389c460  1596042000

      user_id  item_id
6252        0        0
4684        1        1
1731        2        2
4742        3        3
4521        4        4
✅ Đã lưu: E:\DoCode\CD2\source\Source\get_hrs_rs\rs\get10k_data\output_10k_sample\dataset_VCR_1_42_5.csv
   Users: 553
   Items: 2194
   Records: 9455

# Xử lý sample df

In [78]:
# Đọc file CSV
df = pd.read_csv(rf"{ROOT}\dataset_VCR_1_42_5.csv")
# "E:\DoCode\CD2\source\Source\get_hrs_rs\rs\get10k_data\preprocess\dataset_VCR_0.5_42_10.csv"
# df = pd.read_csv(r'/kaggle/working/dataset_VCR_full_10.csv')

In [79]:
df.head(10)

,user_id_original,item_id_original,time,user_id,item_id
0,446,outfit.7cc6bd8e645a41d2837976a0d09e3ca9,1570467600,0,0
1,7367,outfit.7ee7542297f944ecb49f4fe5b44728f7,1680454800,1,1
2,6696,outfit.e8e4d130fa3e4f108127dc74fd854a75,1621270800,2,2
3,1878,outfit.7395b78d10084aebb906f8f83bfd89cc,1658854800,3,3
4,4906,outfit.c929e1bd6aa940f7a34c16471389c460,1596042000,4,4
5,7411,outfit.6a8a9e4b00374d0e953550820b496573,1603990800,5,5
6,1374,outfit.1e4a3ce9976a4d9a9061c167255f3875,1601830800,6,6
7,6118,outfit.5862a9386cbc4ff29e9892f49274c243,1570467600,7,7
8,7101,outfit.f6e0ac328eac45939027a5dbf9d8a086,1618938000,8,8
9,5929,outfit.69510e71049843628dabe5ef896f1b04,1636909200,9,9

In [264]:
# df = df[['user_id' , 'item_id' , 'time']]

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9455 entries, 0 to 9454
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  9455 non-null   int64
 1   item_id_original  9455 non-null   str
 2   time              9455 non-null   int64
 3   user_id           9455 non-null   int64
 4   item_id           9455 non-null   int64
dtypes: int64(4), str(1)
memory usage: 369.5 KB

In [81]:
# Sắp xếp dữ liệu theo `user_id` và `time`
df = df.sort_values(by=["user_id", "time"]).reset_index(drop=True)

In [82]:
df.head(10)

,user_id_original,item_id_original,time,user_id,item_id
0,446,outfit.9edf55f5369fd779,1570381200,0,1906
1,446,outfit.7cc6bd8e645a41d2837976a0d09e3ca9,1570467600,0,0
2,446,outfit.5b219e65b35544769ae32989b15ff364,1570467600,0,1127
3,446,outfit.989e3eb7e1be092f,1570467600,0,1695
4,446,outfit.84f134b06fbed5a0,1570467600,0,960
5,446,outfit.9aadfc9a1d195c33,1570467600,0,1013
6,446,outfit.af4c1536e8d62d77,1571936400,0,1483
7,446,outfit.dd6c85fa43ab4ef7989ebb6a72302ca0,1571936400,0,1930
8,446,outfit.d6578bc3024d48369705dc09bd28f070,1571936400,0,2049
9,446,outfit.925c69db26f6bbae,1571936400,0,367

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9455 entries, 0 to 9454
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  9455 non-null   int64
 1   item_id_original  9455 non-null   str
 2   time              9455 non-null   int64
 3   user_id           9455 non-null   int64
 4   item_id           9455 non-null   int64
dtypes: int64(4), str(1)
memory usage: 369.5 KB

# Tạo user list

In [84]:
user_df = df[['user_id_original', 'user_id']]

In [85]:
user_df = user_df.drop_duplicates()

In [95]:

# Sắp xếp theo giá trị user_id tăng dần
user_list_df = user_df.sort_values(by='user_id')

# Ghi vào file user_list.txt, không bao gồm dòng tên cột
user_list_df.to_csv(rf"{ROOT}\\user_list.txt", sep=' ', index=False, header=False)

print("File user_list.txt đã được tạo.")

File user_list.txt đã được tạo.

In [96]:
user_list_df.info()

<class 'pandas.DataFrame'>
Index: 553 entries, 0 to 9450
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  553 non-null    int64
 1   user_id           553 non-null    int64
dtypes: int64(2)
memory usage: 13.0 KB

# Tạo item list

In [97]:
item_df = df[['item_id_original', 'item_id']]

In [98]:
item_df = item_df.drop_duplicates()

In [99]:
# Sắp xếp theo giá trị user_id tăng dần
item_list_df = item_df.sort_values(by='item_id')

# Ghi vào file user_list.txt, không bao gồm dòng tên cột
item_list_df.to_csv(rf"{ROOT}\\item_list.txt", sep=' ', index=False, header=False)

print("File item_list.txt đã được tạo.")

File item_list.txt đã được tạo.

In [100]:
item_list_df.info()

<class 'pandas.DataFrame'>
Index: 2194 entries, 1 to 1453
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  2194 non-null   str
 1   item_id           2194 non-null   int64
dtypes: int64(1), str(1)
memory usage: 51.4 KB

In [101]:
item_list_df.head()

                           item_id_original  item_id
1   outfit.7cc6bd8e645a41d2837976a0d09e3ca9        0
51  outfit.7ee7542297f944ecb49f4fe5b44728f7        1
56  outfit.e8e4d130fa3e4f108127dc74fd854a75        2
83  outfit.7395b78d10084aebb906f8f83bfd89cc        3
91  outfit.c929e1bd6aa940f7a34c16471389c460        4

# Tạo interactions matrix

In [102]:
# Tạo dictionary lưu quan hệ user và danh sách item
user_item_interactions = df.groupby('user_id')['item_id'].apply(lambda x: sorted(x)).to_dict()

# Ghi file intersection_user.txt
with open(rf"{ROOT}\\intersection_user.txt", 'w') as f:
    for user_id in sorted(user_item_interactions.keys()):  # Sắp xếp user_id theo thứ tự tăng dần
        # Lấy danh sách item_id đã được sắp xếp và chuyển thành chuỗi cách nhau bởi khoảng trắng
        item_list_str = ' '.join(map(str, user_item_interactions[user_id]))
        # Ghi user_id và danh sách item vào file
        f.write(f"{user_id} {item_list_str}\n")

print("File intersection_user.txt đã được tạo.")

File intersection_user.txt đã được tạo.

## **=> Kiểm tra lại dữ liệu**

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9455 entries, 0 to 9454
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  9455 non-null   int64
 1   item_id_original  9455 non-null   str
 2   time              9455 non-null   int64
 3   user_id           9455 non-null   int64
 4   item_id           9455 non-null   int64
dtypes: int64(4), str(1)
memory usage: 369.5 KB

In [104]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = user_df['user_id_original'].nunique()
print(f"Số phần tử không trùng lặp trong cột user_id_original: {unique_count}")

Số phần tử không trùng lặp trong cột user_id_original: 553

In [105]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = item_df['item_id_original'].nunique()
print(f"Số phần tử không trùng lặp trong cột item_id_original: {unique_count}")

Số phần tử không trùng lặp trong cột item_id_original: 2194

In [106]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = item_df['item_id'].max()
print(f"phần tử lớn nhất trong cột item_id: {unique_count}")

phần tử lớn nhất trong cột item_id: 2193

In [107]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = user_df['user_id'].max()
print(f"phần tử lớn nhất trong cột user_id: {unique_count}")

phần tử lớn nhất trong cột user_id: 552

# Chia train / test

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9455 entries, 0 to 9454
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  9455 non-null   int64
 1   item_id_original  9455 non-null   str
 2   time              9455 non-null   int64
 3   user_id           9455 non-null   int64
 4   item_id           9455 non-null   int64
dtypes: int64(4), str(1)
memory usage: 369.5 KB

In [109]:
df.tail(10)

,user_id_original,item_id_original,time,user_id,item_id
9445,6013,outfit.3ccefaac1825408c82d9980a3ea5964a,1636909200,551,1630
9446,6013,outfit.76443d6db496494dbb26ac275ecbdb3b,1644858000,551,72
9447,6013,outfit.880e71e3568b6812,1649264400,551,1671
9448,6013,outfit.48b43358755242c4bf529574c171b675,1651856400,551,1835
9449,6013,outfit.50a8ff8407894fcb9048249c78732fc4,1654534800,551,1718
9450,1073,outfit.043a430a63b34151a6489d2863ea11aa,1596387600,552,978
9451,1073,outfit.b2f9d48f3d4c4549b8d51fcd04979a79,1596387600,552,1380
9452,1073,outfit.adc57b4886354fdcafea896cdd2609b8,1596387600,552,1970
9453,1073,outfit.88e9a4b11d284db686be6be18502f641,1596387600,552,1493
9454,1073,outfit.6377a711bdf04683819c6fc08921cfaf,1596387600,552,2004

In [110]:

# Thêm cột `rank` cho từng `user_id`
df["rank"] = df.groupby("user_id").cumcount() + 1

In [111]:
# Tính toán số lượng tương tác và ngưỡng phân chia
user_counts = df.groupby("user_id")["rank"].max().reset_index()
user_counts.rename(columns={"rank": "total_interactions"}, inplace=True)
user_counts["train_threshold"] = (user_counts["total_interactions"] * 0.8).astype(int)

In [112]:
# Gộp ngưỡng với DataFrame ban đầu
df = df.merge(user_counts, on="user_id", how="inner")

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9455 entries, 0 to 9454
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id_original    9455 non-null   int64
 1   item_id_original    9455 non-null   str
 2   time                9455 non-null   int64
 3   user_id             9455 non-null   int64
 4   item_id             9455 non-null   int64
 5   rank                9455 non-null   int64
 6   total_interactions  9455 non-null   int64
 7   train_threshold     9455 non-null   int32
dtypes: int32(1), int64(6), str(1)
memory usage: 554.1 KB

In [114]:
df.head(10)

,user_id_original,item_id_original,time,user_id,item_id,rank,total_interactions,train_threshold
0,446,outfit.9edf55f5369fd779,1570381200,0,1906,1,47,37
1,446,outfit.7cc6bd8e645a41d2837976a0d09e3ca9,1570467600,0,0,2,47,37
2,446,outfit.5b219e65b35544769ae32989b15ff364,1570467600,0,1127,3,47,37
3,446,outfit.989e3eb7e1be092f,1570467600,0,1695,4,47,37
4,446,outfit.84f134b06fbed5a0,1570467600,0,960,5,47,37
5,446,outfit.9aadfc9a1d195c33,1570467600,0,1013,6,47,37
6,446,outfit.af4c1536e8d62d77,1571936400,0,1483,7,47,37
7,446,outfit.dd6c85fa43ab4ef7989ebb6a72302ca0,1571936400,0,1930,8,47,37
8,446,outfit.d6578bc3024d48369705dc09bd28f070,1571936400,0,2049,9,47,37
9,446,outfit.925c69db26f6bbae,1571936400,0,367,10,47,37

In [115]:
df.tail(10)

,user_id_original,item_id_original,time,user_id,item_id,rank,total_interactions,train_threshold
9445,6013,outfit.3ccefaac1825408c82d9980a3ea5964a,1636909200,551,1630,1,5,4
9446,6013,outfit.76443d6db496494dbb26ac275ecbdb3b,1644858000,551,72,2,5,4
9447,6013,outfit.880e71e3568b6812,1649264400,551,1671,3,5,4
9448,6013,outfit.48b43358755242c4bf529574c171b675,1651856400,551,1835,4,5,4
9449,6013,outfit.50a8ff8407894fcb9048249c78732fc4,1654534800,551,1718,5,5,4
9450,1073,outfit.043a430a63b34151a6489d2863ea11aa,1596387600,552,978,1,5,4
9451,1073,outfit.b2f9d48f3d4c4549b8d51fcd04979a79,1596387600,552,1380,2,5,4
9452,1073,outfit.adc57b4886354fdcafea896cdd2609b8,1596387600,552,1970,3,5,4
9453,1073,outfit.88e9a4b11d284db686be6be18502f641,1596387600,552,1493,4,5,4
9454,1073,outfit.6377a711bdf04683819c6fc08921cfaf,1596387600,552,2004,5,5,4

In [116]:
# Tạo ma trận train và test từ DataFrame
train_interactions = {}
test_interactions = {}

for user_id, user_df in df.groupby('user_id'):
    # Lấy ngưỡng train_threshold cho user hiện tại
    train_threshold = user_df['train_threshold'].iloc[0]

    # Phân chia item_id thành train và test
    train_items = user_df[user_df['rank'] <= train_threshold]['item_id'].tolist()
    test_items = user_df[user_df['rank'] > train_threshold]['item_id'].tolist()

    # Lưu vào dictionary
    train_interactions[user_id] = train_items
    test_interactions[user_id] = test_items

In [117]:
len(train_interactions)

553

In [118]:
len(train_interactions[0])

37

In [119]:
len(test_interactions)

553

In [120]:
len(test_interactions[0])

10

In [121]:
# Ghi file train.txt
with open(rf"{ROOT}\\train.txt", 'w') as f:
    for user_id, item_list in train_interactions.items():
        item_list_str = ' '.join(map(str, item_list))  # Chuyển danh sách item_id thành chuỗi
        f.write(f"{user_id} {item_list_str}\n")  # Ghi user_id và item_id cách nhau bởi khoảng trắng

# Ghi file test.txt
with open(rf"{ROOT}\\test.txt", 'w') as f:
    for user_id, item_list in test_interactions.items():
        item_list_str = ' '.join(map(str, item_list))  # Chuyển danh sách item_id thành chuỗi
        f.write(f"{user_id} {item_list_str}\n")  # Ghi user_id và item_id cách nhau bởi khoảng trắng

print("Files train.txt và test.txt đã được tạo.")

Files train.txt và test.txt đã được tạo.

=> đang sai chia lại theo hướng , mỗi người dùng , đều có trong train và test (đã fix)

# Tạo items_features

## Xử lý feature1 và 2

In [122]:
item_df.info()

<class 'pandas.DataFrame'>
Index: 2194 entries, 0 to 9438
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  2194 non-null   str
 1   item_id           2194 non-null   int64
dtypes: int64(1), str(1)
memory usage: 51.4 KB

In [123]:
item_df.reset_index(drop=True, inplace=True)  # Đặt lại chỉ mục

In [124]:
item_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  2194 non-null   str
 1   item_id           2194 non-null   int64
dtypes: int64(1), str(1)
memory usage: 34.4 KB

In [125]:
item_df.head()

                          item_id_original  item_id
0                  outfit.9edf55f5369fd779     1906
1  outfit.7cc6bd8e645a41d2837976a0d09e3ca9        0
2  outfit.5b219e65b35544769ae32989b15ff364     1127
3                  outfit.989e3eb7e1be092f     1695
4                  outfit.84f134b06fbed5a0      960

In [126]:
outfits.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              2223 non-null   str
 1   name            2223 non-null   str
 2   description     2223 non-null   str
 3   group           2223 non-null   str
 4   owner           2223 non-null   str
 5   timeCreated     2223 non-null   str
 6   retailPrice     2220 non-null   float64
 7   pricePerWeek    2223 non-null   float64
 8   pricePerMonth   2223 non-null   float64
 9   outfit_tags     2223 non-null   object
 10  tag_categories  2223 non-null   object
dtypes: float64(3), object(2), str(6)
memory usage: 191.2+ KB

In [127]:
outfits.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,"[Jewelry, Cecilie Melli, Statement, Metallic, ...","[Category, Brand, Occasion, Details, Occasion]"
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,"[Statement, S, Bastet Noir, Mini, Dresses, Wom...","[Occasion, Size, Brand, Length, Category, Gend..."
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,"[Ruffles, Women, Midi, Purple, Multi Season, S...","[Details, Gender, Length, Color, Seasons, Mate..."
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,"[Multi Season, Jewelry, Formal, Green, Metalli...","[Seasons, Category, Occasion, Color, Details, ..."
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,"[Everyday, Midi, Ruffles, Wrap, Skirts, Women,...","[Occasion, Length, Details, Fit, Category, Gen..."

In [128]:
item_df['item_id_original'].nunique()

2194

In [129]:
outfits['id'].nunique()

2223

In [130]:
merged_df = pd.merge(outfits, item_df, left_on='id', right_on='item_id_original', how='inner')

In [131]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                2194 non-null   str
 1   name              2194 non-null   str
 2   description       2194 non-null   str
 3   group             2194 non-null   str
 4   owner             2194 non-null   str
 5   timeCreated       2194 non-null   str
 6   retailPrice       2191 non-null   float64
 7   pricePerWeek      2194 non-null   float64
 8   pricePerMonth     2194 non-null   float64
 9   outfit_tags       2194 non-null   object
 10  tag_categories    2194 non-null   object
 11  item_id_original  2194 non-null   str
 12  item_id           2194 non-null   int64
dtypes: float64(3), int64(1), object(2), str(7)
memory usage: 223.0+ KB

In [132]:
merged_df['id'].nunique()

2194

In [133]:
merged_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,"[Jewelry, Cecilie Melli, Statement, Metallic, ...","[Category, Brand, Occasion, Details, Occasion]",outfit.ffd83466cdb84a0dba02339aa0c72f73,482
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,"[Statement, S, Bastet Noir, Mini, Dresses, Wom...","[Occasion, Size, Brand, Length, Category, Gend...",outfit.ff08dd87bf144defaa332eac0bf5bd4e,580
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,"[Ruffles, Women, Midi, Purple, Multi Season, S...","[Details, Gender, Length, Color, Seasons, Mate...",outfit.fec66293d37940b79dde2c1acd761fe3,1427
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,"[Multi Season, Jewelry, Formal, Green, Metalli...","[Seasons, Category, Occasion, Color, Details, ...",outfit.feaa16af0f6b4a96b65f8a29ace77979,814
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,"[Everyday, Midi, Ruffles, Wrap, Skirts, Women,...","[Occasion, Length, Details, Fit, Category, Gen...",outfit.fea3bb7d8ff54872ad84977465e29da4,572

In [134]:
merged_df.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags         [Jewelry, Cecilie Melli, Statement, Metallic, ...
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
Name: 0, dtype: object

## Xử lý feature3 ( embedings đặc trưng hình ảnh )

In [135]:
pictures.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    2223 non-null   str
 1   outfit.id     2223 non-null   str
 2   displayOrder  2223 non-null   int64
 3   file_name     2223 non-null   str
dtypes: int64(1), str(3)
memory usage: 69.6 KB

In [136]:
pictures.head()

,picture.id,outfit.id,displayOrder,file_name
0,picture.0000cdba64314d84a49ed1c266589cc0,outfit.794483397da8425a813301eecf9828c6,0,0000cdba64314d84a49ed1c266589cc0.jpg
1,picture.0010c2e161154d6893734981d5455e76,outfit.9387d05b47f906c5,0,0010c2e161154d6893734981d5455e76.jpg
2,picture.0013342f663843d4b7397b4b88b98e6d,outfit.b24fc57f02ac4e4c9061761ca18d9d3c,0,0013342f663843d4b7397b4b88b98e6d.jpg
3,picture.001a58ea68da426384567b8cccc0c8a6,outfit.e989b8cb4a814d97b642e1cb326f47e6,0,001a58ea68da426384567b8cccc0c8a6.jpg
4,picture.0021a36dd3b04f7ebff9430b7801d44d,outfit.070bc7bd72154b5a805f52f086fb72ed,0,0021a36dd3b04f7ebff9430b7801d44d.jpg

In [137]:
pictures['outfit.id'].nunique()

2223

In [138]:
print(pictures['outfit.id'].isna().sum())

0

In [139]:
import pandas as pd

# Giả định df là DataFrame của bạn
grouped_sorted_df = (
    pictures.sort_values(by=['outfit.id', 'displayOrder'])  # Sắp xếp theo outfit.id và displayOrder
      .groupby('outfit.id', as_index=False)
      .agg({
          'picture.id': lambda x: list(x),
          'file_name': lambda x: list(x),
          'displayOrder': lambda x: list(x)
      })
)

In [140]:
grouped_sorted_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   outfit.id     2223 non-null   str
 1   picture.id    2223 non-null   object
 2   file_name     2223 non-null   object
 3   displayOrder  2223 non-null   object
dtypes: object(3), str(1)
memory usage: 69.6+ KB

In [141]:
grouped_sorted_df.head()

,outfit.id,picture.id,file_name,displayOrder
0,outfit.005031a3c94b4073b25088b0e19f0e99,[picture.3c1352a3e42d4c9e920edf8eb969ed40],[3c1352a3e42d4c9e920edf8eb969ed40.jpg],[0]
1,outfit.005123277cc440ffbac2d52252cfcac1,[picture.9c39d325e1b34a80b5f1a9b734c04129],[9c39d325e1b34a80b5f1a9b734c04129.jpg],[0]
2,outfit.006b61bc5e404f37a41b85e6ae915723,[picture.29739c734ae14c73bae71a7303f2a46d],[29739c734ae14c73bae71a7303f2a46d.jpg],[0]
3,outfit.007a4828b12b40ed9ed3db0c5803b813,[picture.724d682edbd14a0b9edf9245d5a2e137],[724d682edbd14a0b9edf9245d5a2e137.jpg],[0]
4,outfit.00c68b581a95458991a876f791e739ab,[picture.27a00e5cb9ad4c5ea953b9c9e4abf8a9],[27a00e5cb9ad4c5ea953b9c9e4abf8a9.jpg],[0]

In [142]:
grouped_sorted_df['outfit.id'].nunique()

2223

In [143]:
grouped_sorted_df.iloc[2000]

outfit.id          outfit.e0f170b8b51f4ae4a7e00047b9ea8d79
picture.id      [picture.5edd410bd98c4dcabf86f94e359a6319]
file_name           [5edd410bd98c4dcabf86f94e359a6319.jpg]
displayOrder                                           [0]
Name: 2000, dtype: object

In [144]:
grouped_sorted_df.iloc[2000]['picture.id']

['picture.5edd410bd98c4dcabf86f94e359a6319']

In [145]:
grouped_sorted_df.iloc[2000]['picture.id'][0]

'picture.5edd410bd98c4dcabf86f94e359a6319'

In [146]:
print(merged_df.isna().sum())

id                  0
name                0
description         0
group               0
owner               0
timeCreated         0
retailPrice         3
pricePerWeek        0
pricePerMonth       0
outfit_tags         0
tag_categories      0
item_id_original    0
item_id             0
dtype: int64

In [147]:
print(grouped_sorted_df.isna().sum())

outfit.id       0
picture.id      0
file_name       0
displayOrder    0
dtype: int64

In [148]:
# Kiểm tra các giá trị trong 'id' của merged_df không tồn tại trong 'outfit.id' của grouped_sorted_df
non_matching_ids = merged_df[~merged_df['id'].isin(grouped_sorted_df['outfit.id'])]

# Hiển thị các giá trị không khớp
print(non_matching_ids[['id']])

Empty DataFrame
Columns: [id]
Index: []

In [149]:
import pandas as pd

# Giả định df_a và df_b đã được đọc vào
items_features_df = pd.merge(
    merged_df, grouped_sorted_df,
    left_on='item_id_original',     # Cột tham chiếu từ df_a
    right_on='outfit.id',  # Cột tham chiếu từ df_b
    how='inner'       # Merge theo cách "inner" để giữ lại các hàng khớp
)

In [150]:
items_features_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                2194 non-null   str
 1   name              2194 non-null   str
 2   description       2194 non-null   str
 3   group             2194 non-null   str
 4   owner             2194 non-null   str
 5   timeCreated       2194 non-null   str
 6   retailPrice       2191 non-null   float64
 7   pricePerWeek      2194 non-null   float64
 8   pricePerMonth     2194 non-null   float64
 9   outfit_tags       2194 non-null   object
 10  tag_categories    2194 non-null   object
 11  item_id_original  2194 non-null   str
 12  item_id           2194 non-null   int64
 13  outfit.id         2194 non-null   str
 14  picture.id        2194 non-null   object
 15  file_name         2194 non-null   object
 16  displayOrder      2194 non-null   object
dtypes: float64(3), int64(1), object(5), str(8)
memory usage: 291.5+ KB

In [151]:
print(items_features_df.isna().sum())

id                  0
name                0
description         0
group               0
owner               0
timeCreated         0
retailPrice         3
pricePerWeek        0
pricePerMonth       0
outfit_tags         0
tag_categories      0
item_id_original    0
item_id             0
outfit.id           0
picture.id          0
file_name           0
displayOrder        0
dtype: int64

In [152]:
items_features_df['outfit.id'].nunique()

2194

In [153]:
items_features_df['id'].nunique()

2194

In [154]:
items_features_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id,outfit.id,picture.id,file_name,displayOrder
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,"[Jewelry, Cecilie Melli, Statement, Metallic, ...","[Category, Brand, Occasion, Details, Occasion]",outfit.ffd83466cdb84a0dba02339aa0c72f73,482,outfit.ffd83466cdb84a0dba02339aa0c72f73,[picture.aad5bad820ae40e2af66dda30b887fd3],[aad5bad820ae40e2af66dda30b887fd3.jpg],[0]
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,"[Statement, S, Bastet Noir, Mini, Dresses, Wom...","[Occasion, Size, Brand, Length, Category, Gend...",outfit.ff08dd87bf144defaa332eac0bf5bd4e,580,outfit.ff08dd87bf144defaa332eac0bf5bd4e,[picture.1adaeb284b764f3fb0b553e4df7067d3],[1adaeb284b764f3fb0b553e4df7067d3.jpg],[0]
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,"[Ruffles, Women, Midi, Purple, Multi Season, S...","[Details, Gender, Length, Color, Seasons, Mate...",outfit.fec66293d37940b79dde2c1acd761fe3,1427,outfit.fec66293d37940b79dde2c1acd761fe3,[picture.1854c475fbfa402f9867c970a71f4656],[1854c475fbfa402f9867c970a71f4656.jpg],[0]
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,"[Multi Season, Jewelry, Formal, Green, Metalli...","[Seasons, Category, Occasion, Color, Details, ...",outfit.feaa16af0f6b4a96b65f8a29ace77979,814,outfit.feaa16af0f6b4a96b65f8a29ace77979,[picture.7e2df174e9d84919bea360f6da43e59a],[7e2df174e9d84919bea360f6da43e59a.jpg],[0]
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,"[Everyday, Midi, Ruffles, Wrap, Skirts, Women,...","[Occasion, Length, Details, Fit, Category, Gen...",outfit.fea3bb7d8ff54872ad84977465e29da4,572,outfit.fea3bb7d8ff54872ad84977465e29da4,[picture.376103f9513c4440a29824e469e330f8],[376103f9513c4440a29824e469e330f8.jpg],[0]

In [155]:
items_features_df.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags         [Jewelry, Cecilie Melli, Statement, Metallic, ...
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
Name: 0, dtype: object

In [339]:
# # Thực hiện merge với how='left'
# left_merged_df = pd.merge(
#     merged_df, grouped_sorted_df,
#     left_on='id',     # Cột tham chiếu từ df_a
#     right_on='outfit.id',  # Cột tham chiếu từ df_b
#     how='left'       # Merge theo cách "left" để giữ lại tất cả các hàng từ merged_df
# )

# # Lọc ra các hàng không khớp
# non_matching_rows = left_merged_df[left_merged_df['outfit.id'].isna()]

# # Hiển thị các hàng không khớp
# non_matching_rows.head()

In [340]:
# left_merged_df.info()

## Tạo image_list

In [156]:
image_list_df = items_features_df[['item_id_original' ,'item_id', 'file_name']]

In [157]:
image_list_df.head()

,item_id_original,item_id,file_name
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,482,[aad5bad820ae40e2af66dda30b887fd3.jpg]
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,580,[1adaeb284b764f3fb0b553e4df7067d3.jpg]
2,outfit.fec66293d37940b79dde2c1acd761fe3,1427,[1854c475fbfa402f9867c970a71f4656.jpg]
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,814,[7e2df174e9d84919bea360f6da43e59a.jpg]
4,outfit.fea3bb7d8ff54872ad84977465e29da4,572,[376103f9513c4440a29824e469e330f8.jpg]

In [158]:
image_list_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  2194 non-null   str
 1   item_id           2194 non-null   int64
 2   file_name         2194 non-null   object
dtypes: int64(1), object(1), str(1)
memory usage: 51.6+ KB

In [159]:
# Sắp xếp theo giá trị user_id tăng dần
image_list_df = image_list_df.sort_values(by='item_id')

image_list_df.reset_index(drop=True, inplace=True)  # Đặt lại chỉ mục

In [160]:
image_list_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  2194 non-null   str
 1   item_id           2194 non-null   int64
 2   file_name         2194 non-null   object
dtypes: int64(1), object(1), str(1)
memory usage: 51.6+ KB

In [161]:
image_list_df.head()

,item_id_original,item_id,file_name
0,outfit.7cc6bd8e645a41d2837976a0d09e3ca9,0,[7ff7061578c34d1bab1a6ea843b1ffa9.jpg]
1,outfit.7ee7542297f944ecb49f4fe5b44728f7,1,[0b128533a20941d3b4483ec55b94f3c8.jpg]
2,outfit.e8e4d130fa3e4f108127dc74fd854a75,2,[2745413be437408b943701d3b1df26ba.jpg]
3,outfit.7395b78d10084aebb906f8f83bfd89cc,3,[1b7695b2c0824da5b46d0e2f74b6f0ed.jpg]
4,outfit.c929e1bd6aa940f7a34c16471389c460,4,[09326e8ed84b4a1fae03a7911a2ca901.jpg]

In [162]:
# Ghi vào file user_list.txt, không bao gồm dòng tên cột
image_list_df.to_csv(rf"{ROOT}\\image_list.txt", sep=' ', index=False, header=False)

print("File image_list.txt đã được tạo.")

File image_list.txt đã được tạo.

## Tạo file items_features

In [163]:
# Tạo cột item_id từ cột index trong df_b
fe_df = items_features_df.copy()

fe_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id,outfit.id,picture.id,file_name,displayOrder
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,"[Jewelry, Cecilie Melli, Statement, Metallic, ...","[Category, Brand, Occasion, Details, Occasion]",outfit.ffd83466cdb84a0dba02339aa0c72f73,482,outfit.ffd83466cdb84a0dba02339aa0c72f73,[picture.aad5bad820ae40e2af66dda30b887fd3],[aad5bad820ae40e2af66dda30b887fd3.jpg],[0]
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,"[Statement, S, Bastet Noir, Mini, Dresses, Wom...","[Occasion, Size, Brand, Length, Category, Gend...",outfit.ff08dd87bf144defaa332eac0bf5bd4e,580,outfit.ff08dd87bf144defaa332eac0bf5bd4e,[picture.1adaeb284b764f3fb0b553e4df7067d3],[1adaeb284b764f3fb0b553e4df7067d3.jpg],[0]
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,"[Ruffles, Women, Midi, Purple, Multi Season, S...","[Details, Gender, Length, Color, Seasons, Mate...",outfit.fec66293d37940b79dde2c1acd761fe3,1427,outfit.fec66293d37940b79dde2c1acd761fe3,[picture.1854c475fbfa402f9867c970a71f4656],[1854c475fbfa402f9867c970a71f4656.jpg],[0]
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,"[Multi Season, Jewelry, Formal, Green, Metalli...","[Seasons, Category, Occasion, Color, Details, ...",outfit.feaa16af0f6b4a96b65f8a29ace77979,814,outfit.feaa16af0f6b4a96b65f8a29ace77979,[picture.7e2df174e9d84919bea360f6da43e59a],[7e2df174e9d84919bea360f6da43e59a.jpg],[0]
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,"[Everyday, Midi, Ruffles, Wrap, Skirts, Women,...","[Occasion, Length, Details, Fit, Category, Gen...",outfit.fea3bb7d8ff54872ad84977465e29da4,572,outfit.fea3bb7d8ff54872ad84977465e29da4,[picture.376103f9513c4440a29824e469e330f8],[376103f9513c4440a29824e469e330f8.jpg],[0]

## => Tạo feature1 và feature2

In [164]:
# Chuyển 'tag_categories' thành chuỗi, nối các phần tử trong danh sách với khoảng trắng
fe_df['outfit_tags'] = fe_df['outfit_tags'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

# Tạo cột feature1: kết hợp name và tag_categories với dấu cách giữa chúng
fe_df['feature1'] = fe_df['name'] + ' ' + fe_df['outfit_tags']

# Tạo cột feature2: là cột description từ df_a
fe_df['feature2'] = fe_df['description']

In [165]:
fe_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id,outfit.id,picture.id,file_name,displayOrder,feature1,feature2
0,outfit.ffd83466cdb84a0dba02339aa0c72f73,Mariposa Earrings AB-Crystal,The Mariposa Earrings are the perfect statemen...,group.4f70fa1707b559c0db341fa53997e52f,o_00037,2019-03-22 11:52:11.000,1600.0,250.0,500.0,Jewelry Cecilie Melli Statement Metallic Formal,"[Category, Brand, Occasion, Details, Occasion]",outfit.ffd83466cdb84a0dba02339aa0c72f73,482,outfit.ffd83466cdb84a0dba02339aa0c72f73,[picture.aad5bad820ae40e2af66dda30b887fd3],[aad5bad820ae40e2af66dda30b887fd3.jpg],[0],Mariposa Earrings AB-Crystal Jewelry Cecilie M...,The Mariposa Earrings are the perfect statemen...
1,outfit.ff08dd87bf144defaa332eac0bf5bd4e,The Gisele Dress,This mini satin dress is made in a beautiful o...,group.a65e95a2f1823633a8d0b07b7fff2e7b,o_00740,2020-02-27 12:51:07.073,2500.0,750.0,1500.0,Statement S Bastet Noir Mini Dresses Women Gre...,"[Occasion, Size, Brand, Length, Category, Gend...",outfit.ff08dd87bf144defaa332eac0bf5bd4e,580,outfit.ff08dd87bf144defaa332eac0bf5bd4e,[picture.1adaeb284b764f3fb0b553e4df7067d3],[1adaeb284b764f3fb0b553e4df7067d3.jpg],[0],The Gisele Dress Statement S Bastet Noir Mini ...,This mini satin dress is made in a beautiful o...
2,outfit.fec66293d37940b79dde2c1acd761fe3,Evie Deauville Mauve Long Sleeve Dress,The Evie Long Sleeve Dress is made in a flowy ...,group.fcc139e28abeaf451c19d46bf311fcb0,o_00530,2019-09-23 09:47:20.000,2200.0,660.0,1320.0,Ruffles Women Midi Purple Multi Season Synthet...,"[Details, Gender, Length, Color, Seasons, Mate...",outfit.fec66293d37940b79dde2c1acd761fe3,1427,outfit.fec66293d37940b79dde2c1acd761fe3,[picture.1854c475fbfa402f9867c970a71f4656],[1854c475fbfa402f9867c970a71f4656.jpg],[0],Evie Deauville Mauve Long Sleeve Dress Ruffles...,The Evie Long Sleeve Dress is made in a flowy ...
3,outfit.feaa16af0f6b4a96b65f8a29ace77979,Tahiti Earrings Green/Gold,The Tahiti Earrings are the perfect statement ...,group.d940849fd6a77efb5fd69121e43bb3ad,o_00037,2019-03-22 11:34:50.000,1600.0,590.0,1180.0,Multi Season Jewelry Formal Green Metallic Wom...,"[Seasons, Category, Occasion, Color, Details, ...",outfit.feaa16af0f6b4a96b65f8a29ace77979,814,outfit.feaa16af0f6b4a96b65f8a29ace77979,[picture.7e2df174e9d84919bea360f6da43e59a],[7e2df174e9d84919bea360f6da43e59a.jpg],[0],Tahiti Earrings Green/Gold Multi Season Jewelr...,The Tahiti Earrings are the perfect statement ...
4,outfit.fea3bb7d8ff54872ad84977465e29da4,Asbjorg Aqua Haze Leopard Skirt,Own this look for a vintage and everyday look....,group.fc687f43497199532a11b0f991ebee04,o_00530,2019-05-21 14:33:03.000,1700.0,590.0,1180.0,Everyday Midi Ruffles Wrap Skirts Women S Visc...,"[Occasion, Length, Details, Fit, Category, Gen...",outfit.fea3bb7d8ff54872ad84977465e29da4,572,outfit.fea3bb7d8ff54872ad84977465e29da4,[picture.376103f9513c4440a29824e469e330f8],[376103f9513c4440a29824e469e330f8.jpg],[0],Asbjorg Aqua Haze Leopard Skirt Everyday Midi ...,Own this look for a vintage and everyday look....

In [166]:
fe_df.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags           Jewelry Cecilie Melli Statement Metallic Formal
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
feature1            Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2            The Mariposa Earrings are the perfect statemen...
Name: 0, dtype: object

=> path sẵn có từ dữ liệu gốc ( chưa detect phần thừa )

In [352]:
# import numpy as np
# import os
# # Tạo cột feature3: là danh sách embedings từ df_a

# # Thư mục chứa các file embeddings
# embeddings_dir = '/kaggle/input/vibrent-clothes-rental-dataset/embeddings/EfficientNet_V2_L_final'

# # Hàm tạo danh sách đường dẫn đầy đủ đến tệp .npy
# def create_embedding_paths(picture_ids):
#     return [os.path.join(embeddings_dir, f"{pic_id}.npy") for pic_id in picture_ids]

# # Sử dụng function
# fe_df['embedding_paths'] = fe_df['picture.id'].apply(create_embedding_paths)

=> path mới (đã detect phần thừa lưu ý số chiều )

In [167]:
import numpy as np
import os

# Thư mục chứa các file embeddings
embeddings_dir = r'E:\\DoCode\\CD2\\source\\Source\\get_hrs_rs\\rs\\get10k_data\\output_10k_sample\\embeddings_10k'

# Hàm tạo danh sách đường dẫn đầy đủ đến tệp .npy
def create_embedding_paths(picture_ids):
    return [os.path.join(embeddings_dir, f"{pic_id.split('.')[1]}.npy") for pic_id in picture_ids]

# Sử dụng function
fe_df['embedding_paths'] = fe_df['picture.id'].apply(create_embedding_paths)

## combine feature3 embeddings#1 ( mean )

In [168]:
cbf_f31 = fe_df.copy()

In [169]:
cbf_f31.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags           Jewelry Cecilie Melli Statement Metallic Formal
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
feature1            Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2            The Mariposa Earrings are the perfect statemen...
embedding_paths     [E:\\DoCode\\CD2\\source\\Source\\get_hrs_rs\\...
Name: 0, dtype: object

In [170]:
cbf_f31.iloc[0]['embedding_paths']

['E:\\\\DoCode\\\\CD2\\\\source\\\\Source\\\\get_hrs_rs\\\\rs\\\\get10k_data\\\\output_10k_sample\\\\embeddings_10k\\aad5bad820ae40e2af66dda30b887fd3.npy']

In [171]:

def load_mean_embeddings(paths):
    """
    Load và combine embeddings của các ảnh trong một outfit
    paths: list các đường dẫn đến embedding files của một outfit
    """
    outfit_embeddings = []
    
    for path in paths:
        if os.path.isfile(path):
            # Load embedding và giữ nguyên shape
            embedding = np.load(path)
            # Print để debug
            # print("Single image embedding shape:", embedding.shape)  # Should be (1280,)
            outfit_embeddings.append(embedding.astype(np.float32))
    
    if outfit_embeddings:
        # Đảm bảo mỗi embedding là 1D array
        outfit_embeddings = [emb.flatten() for emb in outfit_embeddings]
        # Combine embeddings
        combined_embedding = np.mean(outfit_embeddings, axis=0)
        # Print để debug
        # print("Combined embedding shape:", combined_embedding.shape)  # Should be (1280,)
        return combined_embedding.tolist()
    return [0] * 1280  # Return zero vector nếu không có embedding


# Sử dụng function
cbf_f31['feature3'] = cbf_f31['embedding_paths'].apply(load_mean_embeddings)

# Kiểm tra sau khi load
print("Sample of feature3 first element:", len(cbf_f31['feature3'].iloc[0]))  # Should be 1280

Sample of feature3 first element: 1280

## combine feature3 embeddings#2 ( weighted )

In [172]:
cbf_f32 = fe_df.copy()

In [173]:
cbf_f32.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags           Jewelry Cecilie Melli Statement Metallic Formal
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
feature1            Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2            The Mariposa Earrings are the perfect statemen...
embedding_paths     [E:\\DoCode\\CD2\\source\\Source\\get_hrs_rs\\...
Name: 0, dtype: object

In [174]:
cbf_f32.iloc[0]['embedding_paths']

['E:\\\\DoCode\\\\CD2\\\\source\\\\Source\\\\get_hrs_rs\\\\rs\\\\get10k_data\\\\output_10k_sample\\\\embeddings_10k\\aad5bad820ae40e2af66dda30b887fd3.npy']

In [175]:

def load_weighted_embeddings(paths, display_orders):
    """
    Load và combine embeddings của các ảnh trong một outfit với trọng số dựa trên display order.
    paths: list các đường dẫn đến embedding files của một outfit.
    display_orders: list thứ tự ưu tiên của các ảnh trong outfit.
    """
    outfit_embeddings = []
    valid_orders = []

    for idx, path in enumerate(paths):
        if os.path.isfile(path):
            embedding = np.load(path).flatten().astype(np.float32)
            outfit_embeddings.append(embedding)
            valid_orders.append(display_orders[idx])

    if outfit_embeddings:
        # Tính trọng số dựa vào displayOrder
        weights = 1 / (np.array(valid_orders) + 1)
        weights = weights / np.sum(weights)  # Chuẩn hóa trọng số
        
        # Áp dụng trọng số vào embeddings
        weighted_embedding = np.sum([w * emb for w, emb in zip(weights, outfit_embeddings)], axis=0)
        
        return weighted_embedding.tolist()

    # Trả về vector zero nếu không có embedding hợp lệ
    return [0] * 1280

# Áp dụng cho DataFrame fe_df
cbf_f32['feature3'] = cbf_f32.apply(
    lambda row: load_weighted_embeddings(row['embedding_paths'], row['displayOrder']),
    axis=1
)

# Kiểm tra kết quả
print("Feature3 sample embedding length:", len(cbf_f32['feature3'].iloc[0]))  # Should be 1280

Feature3 sample embedding length: 1280

## combine feature3 embeddings#3 ( max )

In [176]:
cbf_f33 = fe_df.copy()

In [177]:
cbf_f33.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags           Jewelry Cecilie Melli Statement Metallic Formal
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
feature1            Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2            The Mariposa Earrings are the perfect statemen...
embedding_paths     [E:\\DoCode\\CD2\\source\\Source\\get_hrs_rs\\...
Name: 0, dtype: object

In [178]:
cbf_f33.iloc[0]['embedding_paths']

['E:\\\\DoCode\\\\CD2\\\\source\\\\Source\\\\get_hrs_rs\\\\rs\\\\get10k_data\\\\output_10k_sample\\\\embeddings_10k\\aad5bad820ae40e2af66dda30b887fd3.npy']

In [179]:

def load_max_embeddings(paths):
    """
    Load và combine embeddings của các ảnh trong một outfit
    paths: list các đường dẫn đến embedding files của một outfit
    """
    outfit_embeddings = []
    
    for path in paths:
        if os.path.isfile(path):
            # Load embedding và giữ nguyên shape
            embedding = np.load(path)
            # Print để debug
            # print("Single image embedding shape:", embedding.shape)  # Should be (1280,)
            outfit_embeddings.append(embedding.astype(np.float32))
    
    if outfit_embeddings:
        # Đảm bảo mỗi embedding là 1D array
        outfit_embeddings = [emb.flatten() for emb in outfit_embeddings]
        # Combine embeddings
        combined_embedding = np.max(outfit_embeddings, axis=0)
        # Print để debug
        # print("Combined embedding shape:", combined_embedding.shape)  # Should be (1280,)
        return combined_embedding.tolist()
    return [0] * 1280  # Return zero vector nếu không có embedding


# Sử dụng function
cbf_f33['feature3'] = cbf_f33['embedding_paths'].apply(load_max_embeddings)

# Kiểm tra sau khi load
print("Sample of feature3 first element:", len(cbf_f33['feature3'].iloc[0]))  # Should be 1280

Sample of feature3 first element: 1280

## Dimensionality reduction with PCA

In [180]:
cbf_f31['feature3'].head()

0    [0.0, 2.368340492248535, 0.008222006261348724,...
1    [0.0, 0.017007915303111076, 0.0, 0.37110745906...
2    [0.07040582597255707, 0.19717185199260712, 0.0...
3    [0.028707018122076988, 2.110269069671631, 0.02...
4    [0.010761134326457977, 0.0, 0.4700208902359009...
Name: feature3, dtype: object

In [181]:
cbf_f32['feature3'].head()

0    [0.0, 2.368340492248535, 0.008222006261348724,...
1    [0.0, 0.017007915303111076, 0.0, 0.37110745906...
2    [0.07040582597255707, 0.19717185199260712, 0.0...
3    [0.028707018122076988, 2.110269069671631, 0.02...
4    [0.010761134326457977, 0.0, 0.4700208902359009...
Name: feature3, dtype: object

In [182]:
cbf_f33['feature3'].head()

0    [0.0, 2.368340492248535, 0.008222006261348724,...
1    [0.0, 0.017007915303111076, 0.0, 0.37110745906...
2    [0.07040582597255707, 0.19717185199260712, 0.0...
3    [0.028707018122076988, 2.110269069671631, 0.02...
4    [0.010761134326457977, 0.0, 0.4700208902359009...
Name: feature3, dtype: object

In [183]:
# Gán lại kết quả vào fe_df sau khi kiểm tra
#mean
fe_df['feature3'] = cbf_f31['feature3']
#weight
# fe_df['feature3'] = cbf_f32['feature3']
#max
# fe_df['feature3'] = cbf_f33['feature3']

# Kiểm tra sau khi load
print("Sample of feature3 first element:", len(fe_df['feature3'].iloc[0]))  # Should be 1280

Sample of feature3 first element: 1280

In [184]:
fe_df.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags           Jewelry Cecilie Melli Statement Metallic Formal
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
feature1            Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2            The Mariposa Earrings are the perfect statemen...
embedding_paths     [E:\\DoCode\\CD2\\source\\Source\\get_hrs_rs\\...
feature3            [0.0, 2.368340492248535, 0.008222006261348724,...
Name: 0, dtype: object

In [185]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize
import numpy as np

# Kiểm tra và thay thế NaN bằng vector zero có cùng số chiều
image_embeddings = np.vstack([
    np.array(emb).reshape(1, -1) if isinstance(emb, list) else emb.reshape(1, -1)
    for emb in fe_df['feature3']
])
print("Image embeddings shape before normalization:", image_embeddings.shape)

# Thay thế NaN bằng vector zero
image_embeddings = np.nan_to_num(image_embeddings)

# Chuẩn hóa embeddings trước khi áp dụng PCA
image_embeddings_normalized = normalize(image_embeddings)

# Xác định số chiều mong muốn cho PCA
n_samples, n_features = image_embeddings_normalized.shape
n_components = min(768, n_features, n_samples)

# Áp dụng PCA
pca = PCA(n_components=n_components)
image_embeddings_reduced = pca.fit_transform(image_embeddings_normalized)

# Cập nhật cột feature3 mà không làm thay đổi thứ tự ban đầu
fe_df['feature3'] = list(image_embeddings_reduced)

# Kiểm tra kết quả
print("Feature3 vector size:", len(fe_df['feature3'].iloc[0]))

Image embeddings shape before normalization: (2194, 1280)
Feature3 vector size: 768

In [186]:
print(len(fe_df['feature3'].iloc[0]))  # Kiểm tra vector sau giảm chiều
print("Tổng số mẫu:", len(fe_df))

768
Tổng số mẫu: 2194

In [187]:
fe_df.iloc[0]

id                            outfit.ffd83466cdb84a0dba02339aa0c72f73
name                                     Mariposa Earrings AB-Crystal
description         The Mariposa Earrings are the perfect statemen...
group                          group.4f70fa1707b559c0db341fa53997e52f
owner                                                         o_00037
timeCreated                                   2019-03-22 11:52:11.000
retailPrice                                                    1600.0
pricePerWeek                                                    250.0
pricePerMonth                                                   500.0
outfit_tags           Jewelry Cecilie Melli Statement Metallic Formal
tag_categories         [Category, Brand, Occasion, Details, Occasion]
item_id_original              outfit.ffd83466cdb84a0dba02339aa0c72f73
item_id                                                           482
outfit.id                     outfit.ffd83466cdb84a0dba02339aa0c72f73
picture.id                 [picture.aad5bad820ae40e2af66dda30b887fd3]
file_name                      [aad5bad820ae40e2af66dda30b887fd3.jpg]
displayOrder                                                      [0]
feature1            Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2            The Mariposa Earrings are the perfect statemen...
embedding_paths     [E:\\DoCode\\CD2\\source\\Source\\get_hrs_rs\\...
feature3            [-0.1818618411653846, -0.14280182755422194, -0...
Name: 0, dtype: object

In [188]:
fe_df['displayOrder'].head(10)

0    [0]
1    [0]
2    [0]
3    [0]
4    [0]
5    [0]
6    [0]
7    [0]
8    [0]
9    [0]
Name: displayOrder, dtype: object

In [189]:
fe_df['displayOrder'].tail(10)

2184    [0]
2185    [0]
2186    [0]
2187    [0]
2188    [0]
2189    [0]
2190    [0]
2191    [0]
2192    [0]
2193    [0]
Name: displayOrder, dtype: object

In [190]:
fe_df.iloc[0]['embedding_paths']

['E:\\\\DoCode\\\\CD2\\\\source\\\\Source\\\\get_hrs_rs\\\\rs\\\\get10k_data\\\\output_10k_sample\\\\embeddings_10k\\aad5bad820ae40e2af66dda30b887fd3.npy']

In [191]:
fe_df.iloc[0]['picture.id']

['picture.aad5bad820ae40e2af66dda30b887fd3']

In [192]:
len(fe_df.iloc[0]['feature3'])

768

In [193]:
# Chọn chỉ các cột cần thiết để tạo df_c
df_c = fe_df[['item_id', 'feature1', 'feature2' ,'feature3']]

# Hiển thị kết quả
df_c.head()

,item_id,feature1,feature2,feature3
0,482,Mariposa Earrings AB-Crystal Jewelry Cecilie M...,The Mariposa Earrings are the perfect statemen...,"[-0.1818618411653846, -0.14280182755422194, -0..."
1,580,The Gisele Dress Statement S Bastet Noir Mini ...,This mini satin dress is made in a beautiful o...,"[0.02342565428738875, -0.016955449037710322, 0..."
2,1427,Evie Deauville Mauve Long Sleeve Dress Ruffles...,The Evie Long Sleeve Dress is made in a flowy ...,"[-0.13170364849893063, -0.17881093367455508, -..."
3,814,Tahiti Earrings Green/Gold Multi Season Jewelr...,The Tahiti Earrings are the perfect statement ...,"[-0.2248584545447264, -0.2217712433645414, -0...."
4,572,Asbjorg Aqua Haze Leopard Skirt Everyday Midi ...,Own this look for a vintage and everyday look....,"[0.10333186472271742, 0.04879593792854971, -0...."

In [194]:
df_c['item_id'][0]

482

In [195]:
df_c.iloc[0]

item_id                                                   482
feature1    Mariposa Earrings AB-Crystal Jewelry Cecilie M...
feature2    The Mariposa Earrings are the perfect statemen...
feature3    [-0.1818618411653846, -0.14280182755422194, -0...
Name: 0, dtype: object

In [196]:
df_c['feature1'][0]

'Mariposa Earrings AB-Crystal Jewelry Cecilie Melli Statement Metallic Formal'

In [197]:
df_c['feature2'][0]

'The Mariposa Earrings are the perfect statement jewelry. We recommend wearing your hair up to show them off. '

In [198]:
df_c['feature3'][1200][0]

0.14344012527871722

In [199]:
df_c.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   2194 non-null   int64
 1   feature1  2194 non-null   str
 2   feature2  2194 non-null   str
 3   feature3  2194 non-null   object
dtypes: int64(1), object(1), str(2)
memory usage: 68.7+ KB

In [200]:
df_c.isnull().sum()

item_id     0
feature1    0
feature2    0
feature3    0
dtype: int64

In [201]:
# Lưu DataFrame df_c vào file CSV
df_c.to_csv(rf"{ROOT}\\items_features.csv", index=False)

# Hiển thị thông báo lưu thành công
print("DataFrame đã được lưu vào items_features.csv")

DataFrame đã được lưu vào items_features.csv

# Debug Item feature (sửa khi load items_features trong load_data)

In [202]:
xxx = pd.read_csv(rf"{ROOT}\\items_features.csv")

In [203]:
xxx.info()

<class 'pandas.DataFrame'>
RangeIndex: 2194 entries, 0 to 2193
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   2194 non-null   int64
 1   feature1  2194 non-null   str
 2   feature2  2194 non-null   str
 3   feature3  2194 non-null   str
dtypes: int64(1), str(3)
memory usage: 68.7 KB

In [204]:
xxx.head()

,item_id,feature1,feature2,feature3
0,482,Mariposa Earrings AB-Crystal Jewelry Cecilie M...,The Mariposa Earrings are the perfect statemen...,[-1.81861841e-01 -1.42801828e-01 -1.73801487e-...
1,580,The Gisele Dress Statement S Bastet Noir Mini ...,This mini satin dress is made in a beautiful o...,[ 2.34256543e-02 -1.69554490e-02 5.82059605e-...
2,1427,Evie Deauville Mauve Long Sleeve Dress Ruffles...,The Evie Long Sleeve Dress is made in a flowy ...,[-1.31703648e-01 -1.78810934e-01 -1.12301135e-...
3,814,Tahiti Earrings Green/Gold Multi Season Jewelr...,The Tahiti Earrings are the perfect statement ...,[-2.24858455e-01 -2.21771243e-01 -1.38866243e-...
4,572,Asbjorg Aqua Haze Leopard Skirt Everyday Midi ...,Own this look for a vintage and everyday look....,[ 1.03331865e-01 4.87959379e-02 -1.19034438e-...

In [205]:
xxx['feature3'][0]

'[-1.81861841e-01 -1.42801828e-01 -1.73801487e-01  2.22816044e-01\n -1.85576959e-01 -8.72849977e-02 -7.47555686e-02  8.47545173e-02\n -2.18261067e-01 -1.26205035e-01  6.62624919e-02 -9.84610015e-02\n -6.17713053e-02  3.41829938e-02  1.95979812e-02 -3.35348070e-02\n  6.84568964e-02 -1.70965173e-01 -6.08901110e-03 -3.71863768e-02\n  2.76397530e-02 -3.35425869e-02 -5.18217055e-02  2.60866879e-02\n -2.95264551e-02  3.93884742e-02 -2.28475665e-02 -6.89586382e-02\n  9.07938965e-02 -7.01272184e-02 -4.31429562e-02 -4.44394261e-02\n -3.99916836e-02 -8.57988959e-02 -4.65823002e-02 -8.67159560e-02\n -5.90027168e-02 -7.47831357e-02 -1.00582427e-01  1.54308927e-01\n -1.92014151e-03  9.11744429e-02  6.61664115e-02  1.91523421e-02\n  1.40991686e-02 -8.40122541e-02  2.08141831e-02  1.13986433e-01\n  3.70342419e-02  3.29378373e-02  6.19243480e-02  2.39760128e-02\n  2.95271117e-03  5.63252171e-02 -1.82790384e-02  4.76904814e-02\n -9.42604760e-02 -3.50648880e-02 -5.34658016e-03  3.61661725e-02\n  6.59257134e-04  4.07869373e-02  5.19227367e-03 -7.01502402e-02\n  8.63378827e-02  6.07805008e-02  1.56899465e-02 -3.39765667e-02\n  1.18362905e-02 -2.14111143e-02 -2.11360247e-02 -2.59754405e-02\n  3.32091137e-02 -2.93350397e-02 -5.97348112e-02 -6.67539339e-02\n  8.17051480e-02 -9.15452824e-02  6.08664786e-02  2.83306240e-02\n -1.11373187e-02 -4.78292216e-02  6.27127057e-02  4.47246085e-02\n  1.81832393e-02  2.97440950e-02  1.54823698e-02  7.44846277e-02\n -1.06191514e-01  4.31075798e-02  4.87904172e-02 -3.31321455e-02\n -2.53165045e-02  5.09542409e-02  1.49928772e-02 -3.13048450e-02\n -4.31680086e-02 -9.70238077e-03  3.49189270e-02 -5.00607629e-02\n -2.78644524e-02 -1.15162706e-02 -6.67792748e-03 -6.34777173e-02\n -1.28724466e-02 -3.19388770e-03  3.72879101e-02  6.80944210e-02\n -6.23494544e-02 -2.18357552e-02  1.28684765e-02  4.82037220e-02\n -2.67934565e-02 -8.00952893e-02  4.30659853e-02  6.39816738e-03\n  7.60382863e-02  1.61195806e-02  1.04470980e-02  1.57153874e-02\n  4.74881665e-02 -3.39647566e-03  4.25682437e-02 -8.18957985e-02\n -9.99425886e-02  1.01479498e-01 -2.74488698e-02  3.88942612e-02\n  3.48795034e-02 -6.30539597e-02 -9.61107758e-02 -2.20958918e-02\n  5.21553176e-03  5.10913702e-02 -1.09651127e-02  6.11926341e-02\n -2.81968054e-02  1.03958087e-02 -1.40593450e-02 -4.38312147e-03\n -4.15606644e-02 -7.15028241e-03 -4.09682559e-03  2.94833932e-02\n -6.47242564e-02 -5.28085279e-02  2.22829405e-02 -1.81002230e-02\n  5.56993492e-02 -1.17216557e-02 -8.38164092e-03  2.94403110e-02\n  7.89064970e-03 -1.29428241e-02  2.27415436e-02 -6.62184063e-04\n -5.32119900e-02 -7.26887608e-04 -1.32425244e-02 -2.97901371e-02\n -4.28290855e-02 -2.06525807e-02 -5.70552879e-03  6.39578739e-02\n  6.32670286e-02  4.09602195e-02 -3.77268297e-02  5.36049135e-03\n -7.58462657e-03  3.99814513e-02  3.23368996e-02  3.67292178e-03\n -1.18306637e-03 -2.44927566e-02 -2.72224753e-02  7.46084731e-02\n  1.99077092e-02  2.88026925e-02 -6.40626586e-02  4.42266539e-03\n  2.48693918e-02 -1.62406770e-02  2.78335835e-02 -5.67662737e-02\n -1.38384826e-02  1.81485266e-03 -1.08305813e-02  1.32847537e-02\n  4.56084180e-02  5.94186823e-02 -3.45238464e-02  2.26064225e-02\n -2.43217604e-02 -3.60886234e-03 -2.51840039e-02  2.63223971e-02\n  2.11075655e-02 -5.66854373e-02  3.78267887e-02 -1.72046481e-02\n -2.55984655e-02 -3.76629263e-02 -1.75718682e-03 -4.16402436e-02\n  2.43030922e-02  8.67850057e-03 -4.37816210e-02 -1.20986793e-02\n -4.30054269e-03 -1.77714463e-02  3.14758258e-02  2.49245141e-02\n  5.53522153e-03 -3.01820819e-02 -1.46665568e-02 -6.40855194e-03\n  1.50524752e-02 -3.87897388e-02  2.69766605e-02 -1.37657512e-02\n  3.66229638e-02 -2.92435056e-02  1.57601317e-02  1.67634611e-02\n -2.32958346e-02 -9.33188107e-03  1.61604065e-02 -5.31259429e-02\n -1.57259663e-02  5.76466059e-02 -8.49186526e-03 -2.32710577e-02\n  2.90951793e-02  6.37005445e-03 -8.95428901e-03  3.26873677e-03\n  5.01591124e-03 -1.13647470e-02  1.71646032e-02 -3.44291665e-02\n -1.46314623e-02 -3.43118047e-02 -4.04514709e-03 -2.33022456e-03\n  3.76911329e-02 -9.82197885e-03  3.41404418e-02 -1.88543123e-02\n  1.59584037e-02 -2.64945134e-02  5.87028327e-02  3.43228326e-02\n -4.50506136e-03 -1.89628322e-02  1.24710382e-02  1.39012412e-02\n -1.43159741e-02  1.38757982e-03 -2.12869796e-02 -1.24273396e-02\n -4.73782918e-02  9.17631921e-03 -3.68676072e-02  8.85750239e-03\n  3.19357904e-02  1.48213827e-02  8.11787642e-04 -5.06121986e-03\n  6.21752811e-03 -1.02659645e-02  1.86230306e-02  2.13775600e-02\n  1.50029665e-02 -2.20459553e-02 -1.09735996e-02  1.65609874e-03\n -1.13774494e-02 -1.80169298e-02 -7.02313788e-02 -1.09106603e-02\n  3.38899193e-02 -1.68830257e-03 -1.74751232e-03  1.17659866e-02\n -1.49495712e-02  2.05932873e-02  4.74549993e-03  7.27791347e-03\n -1.68098996e-02  4.84633512e-03  1.64989022e-02  2.13887311e-02\n  2.50391451e-02 -3.91247665e-02  1.45623090e-02 -9.06398902e-03\n -2.02161925e-02  2.32413632e-02  1.48710437e-02  1.00830293e-02\n  1.45607327e-02 -2.40110471e-02 -5.22900272e-03  1.98362887e-02\n  1.71283245e-02 -3.12125855e-03 -4.90591746e-03 -1.50743166e-02\n -1.71874372e-02 -1.66721875e-03 -6.82436742e-03 -3.35406756e-02\n -4.62125369e-03  1.55656807e-02 -1.41865656e-02 -9.88305070e-03\n  6.39890130e-03 -7.22679579e-03  2.75782729e-02  1.55248478e-02\n -1.24821849e-02  4.87696117e-02  2.68652640e-02  3.05540926e-02\n  1.20360106e-02  3.59798399e-02 -7.99099631e-03  2.71205336e-04\n  3.34464650e-03 -1.59768795e-02  5.92732123e-04  1.30280225e-02\n -6.58330202e-03 -6.91739499e-03  2.92236242e-03 -7.96074922e-03\n  2.04380782e-02  1.70817944e-02 -2.24355344e-02  2.08475646e-02\n  1.06802564e-02  1.70988336e-02  2.00281228e-02 -7.90715191e-03\n -8.25807539e-03 -1.99555384e-03  2.12734724e-02  6.96826056e-03\n -2.19774619e-02 -4.85669832e-04 -4.47728673e-03 -7.88204820e-03\n  1.29065471e-02 -2.25996995e-02  1.95498783e-02  8.47591807e-03\n -1.49403905e-02  2.43803769e-03 -2.47762580e-02 -5.17996330e-03\n -2.41172208e-02 -1.46182612e-03 -7.64142105e-03 -1.64245014e-02\n -2.46304981e-02 -2.07228524e-02  1.30247906e-02 -2.50787199e-02\n  1.09179309e-02 -4.59552116e-03 -2.29089762e-02 -6.45809495e-04\n  2.47994114e-02  1.86300804e-02  9.36932349e-03 -1.15446992e-02\n  9.10980172e-03 -1.64812812e-03  1.77135480e-02  1.11838419e-02\n  1.96650913e-02 -7.13249878e-04  1.79155108e-02 -1.94227739e-02\n  8.57554694e-03 -6.41204037e-03  2.03064702e-02  6.07056653e-03\n  7.55866393e-03 -1.08279291e-02 -5.45714286e-03  1.89638955e-02\n -2.37178950e-03  2.93702579e-03 -1.98591582e-03  9.07785580e-03\n  1.02387043e-02  9.55760130e-03 -4.13389455e-03  4.88869911e-03\n -2.09022322e-03  2.29941579e-02  1.95913979e-02  5.89818267e-03\n -1.76999275e-02 -1.39575763e-03 -3.96989552e-03  2.59356605e-03\n -9.84072415e-03  1.20844070e-02  1.10212548e-02 -5.58410040e-03\n  6.41596830e-03  2.01676547e-02 -1.48129290e-02 -2.19954202e-02\n  6.51234635e-03 -1.23302481e-02 -9.50452013e-03 -1.95074456e-03\n  2.39532568e-03 -1.91585446e-02  2.37710772e-03 -1.24778701e-02\n -3.83117125e-03 -1.83892233e-02 -9.96373364e-04 -6.43887176e-03\n  8.68554593e-05  7.47053602e-03  1.04026012e-02 -1.17320581e-02\n  1.76894549e-02  1.41085456e-03  1.06000560e-02 -3.85038987e-03\n -1.46247771e-02 -2.21060480e-03 -5.90728965e-03 -6.23198894e-03\n -4.73098585e-05 -1.28427291e-02 -1.06276575e-02  3.46175375e-02\n  2.34909371e-03  1.25130731e-02  1.44695976e-02 -2.85020570e-02\n  2.14169890e-02  6.42639528e-04 -6.61425810e-03  1.23803303e-02\n -1.30130406e-02  1.31847416e-02  6.95291316e-03 -1.01713530e-02\n -2.34586231e-02  7.55352391e-03 -2.42339073e-03  2.81531881e-03\n -8.09330556e-03  1.46024531e-03  8.43866256e-03  1.76729136e-02\n -9.42561830e-03  1.05115808e-02  6.17952298e-04  7.84409793e-05\n -2.67414306e-03  1.06539005e-02 -1.15745035e-02  1.10435138e-03\n  2.12729128e-02 -1.09123877e-02 -1.19853956e-02  8.70849197e-03\n  2.32998518e-02  7.06018536e-04 -1.66798712e-02 -1.38597907e-02\n  3.62417458e-03 -2.77894973e-02  3.28176160e-03 -1.83243444e-03\n -4.52588018e-03  1.63081797e-02 -6.88991989e-03  1.77839810e-02\n  1.35698450e-02  1.67258163e-02  1.93471265e-02  5.59415874e-03\n -1.32735965e-02  3.44645002e-03  2.14482082e-03  7.30462373e-03\n  8.88912335e-03 -8.27817873e-03  1.44185893e-02 -1.46221008e-02\n  1.31656450e-02 -5.08927061e-03  1.05760559e-02 -1.14050906e-02\n  6.97374535e-03 -1.06324138e-02 -5.30765090e-03  1.00861448e-03\n -5.32815149e-03 -1.52846624e-03  2.73358638e-03  1.13078303e-02\n -4.25339287e-03 -4.06290885e-03  1.41369977e-02  7.26195743e-04\n  1.82635643e-02  2.61428305e-03  3.97988506e-03  1.02040000e-02\n -2.01286733e-02 -4.05070307e-03  1.38874235e-02 -8.47791786e-03\n  2.00162367e-02 -2.97540123e-03 -2.12315891e-02 -1.17929912e-02\n -3.32077867e-03  2.66884772e-02 -7.68446976e-03  1.21469055e-02\n  1.46967955e-02  1.86047594e-02 -1.86064577e-03 -1.58553611e-02\n -1.63635472e-02 -5.22816021e-03 -5.35368904e-04 -9.33406581e-03\n -1.60323882e-02 -6.93583905e-03 -8.09893449e-03 -1.47886628e-03\n -8.36648820e-03 -5.74765142e-03  9.44841058e-03 -8.67920182e-03\n  3.24347524e-03  9.23062037e-03 -6.66867291e-03  9.37055588e-03\n  5.64726880e-03 -4.82323780e-03  1.29579190e-02  3.95707388e-03\n -2.14546525e-03  4.77907282e-03 -1.96449036e-02  7.79797377e-03\n  1.31870217e-02  8.75614106e-03 -2.92136899e-03  1.02947378e-02\n -3.61717487e-04  7.77991087e-03  5.22757502e-04  5.10654686e-03\n  3.07824254e-03 -2.40533003e-02  1.12723283e-02  1.35363973e-04\n -1.31675256e-02  1.38240503e-02 -3.23948942e-03 -1.66935924e-03\n -1.43890252e-02  9.06985149e-03  6.71542946e-03  8.74083428e-03\n  8.72935450e-03  9.33055251e-03 -7.74201424e-03 -1.35733213e-02\n  6.81518287e-04  9.26638232e-03 -3.91287975e-03  1.51576702e-03\n  1.55870726e-02  1.00972389e-02 -1.72920046e-02 -9.91703306e-03\n  4.60226226e-03  2.94762515e-03 -2.19707932e-03 -3.95474115e-03\n -1.40430818e-02  2.04716961e-03  9.68675741e-03  6.03418300e-03\n  1.02645113e-02 -3.45892108e-03  1.51065844e-02  3.81631677e-03\n  5.89740172e-03 -8.23732540e-04 -2.85351708e-03 -1.05487256e-03\n  6.77485551e-03  5.35714924e-03 -2.68086090e-03  3.31994213e-03\n  7.22070936e-03  8.04787461e-03  1.04342827e-02 -5.22315143e-04\n  5.13894754e-03  5.39331786e-03 -3.26409752e-03  2.04352700e-03\n -7.29248238e-03 -6.07035044e-03  5.46225558e-03  3.73279083e-03\n -4.46884648e-03 -1.18644566e-02 -1.57749948e-03  2.03771117e-02\n  5.27676034e-03  1.28701506e-02  9.65089837e-05 -4.02354667e-03\n -1.76346230e-03 -3.85166420e-03 -3.55916200e-03  9.60274292e-03\n -1.32697491e-02  2.54464450e-03  1.28002780e-02  7.71107722e-03\n -4.99809720e-03 -4.80023877e-03  5.62744991e-03 -4.75425928e-03\n  3.38257789e-03 -5.01587973e-03 -9.01290220e-04 -5.42780265e-03\n -6.68530462e-03  1.34614665e-02 -3.52229999e-03  5.70222751e-03\n -7.16615533e-03 -5.28735241e-04 -1.02203287e-02 -4.86041879e-03\n  6.12408058e-03  5.58205943e-03 -3.07058549e-03 -5.88339302e-03\n  1.74858904e-03  2.96937219e-03  1.03337996e-02  1.39285822e-03\n  1.52525256e-02  1.36108182e-02  3.63184032e-04  3.91598506e-03\n  3.85077132e-03  7.54374590e-03  3.99080506e-03 -7.91427478e-03\n  2.62019828e-04 -9.35120638e-03 -7.82059491e-03 -4.38934759e-04\n -1.36110138e-02 -2.49737838e-04 -7.29809561e-03  9.21317982e-03\n  6.43437658e-03 -1.05915123e-02 -7.05699796e-03 -3.24304649e-03\n -2.79762593e-03 -6.47662125e-03  1.29665415e-02 -1.87423938e-03\n -1.20749461e-02  2.20969282e-03 -7.10219863e-03 -4.75683114e-03\n -2.08496801e-03  5.23237196e-03  3.71426304e-03  5.08586923e-03\n  2.64793146e-03  1.95044071e-02 -3.50508417e-03 -1.64426422e-03\n -1.04724257e-02  8.82063765e-03  1.39913835e-02  1.20964546e-02\n -1.47525602e-02 -7.62910728e-03 -1.76981172e-04  1.43171710e-02\n  4.68170915e-03 -5.75607240e-03  5.37776039e-03 -2.28745260e-03\n  2.97194042e-03 -4.68033053e-03  5.65034178e-03  7.66705473e-03\n -5.61849313e-04  1.01230277e-02 -2.45885691e-03 -4.89986857e-03\n -7.12890874e-03  1.06600321e-02 -2.79022939e-03  7.31888288e-03\n -1.35842643e-03  2.39856982e-03  5.49204787e-04  2.26671261e-03\n -4.89896501e-03  3.55565174e-04  9.59399528e-03 -2.99849326e-03\n  5.06401275e-03 -1.52519754e-02  8.75230430e-04 -2.73474932e-04\n -8.27155875e-03 -2.67827378e-03 -4.35239157e-03  3.55941694e-03\n -5.94553642e-03  1.64414365e-02  9.22347837e-03  4.42588385e-03\n -7.09824092e-03  1.04549310e-02  5.59684676e-03  1.29586059e-02\n -9.23996985e-03 -1.75359743e-03  2.36299326e-03  1.67257963e-03\n -1.01142728e-03 -3.35516370e-03 -7.06759314e-03  4.12278111e-03\n  1.57749469e-03 -9.92251843e-03  9.75901418e-03 -1.09232700e-03\n -1.09242651e-02 -3.69798640e-04  7.92662972e-03  2.61483785e-03\n  8.77548964e-03 -5.99986101e-03  7.16663142e-03  1.09090807e-02]'

In [206]:
xxx['feature3'][0][0]

'['

In [207]:
# Chuyển string vector thành numpy array
def parse_vector_string(vector_string):
    # Loại bỏ dấu ngoặc vuông và split theo khoảng trắng
    vector = vector_string.strip('[]').split()
    # Chuyển đổi sang float
    return np.array([float(x) for x in vector])

image_embeddings = np.vstack(
    xxx['feature3'].apply(parse_vector_string).values
)

In [208]:
image_embeddings[0]

array([-1.81861841e-01, -1.42801828e-01, -1.73801487e-01,  2.22816044e-01,
       -1.85576959e-01, -8.72849977e-02, -7.47555686e-02,  8.47545173e-02,
       -2.18261067e-01, -1.26205035e-01,  6.62624919e-02, -9.84610015e-02,
       -6.17713053e-02,  3.41829938e-02,  1.95979812e-02, -3.35348070e-02,
        6.84568964e-02, -1.70965173e-01, -6.08901110e-03, -3.71863768e-02,
        2.76397530e-02, -3.35425869e-02, -5.18217055e-02,  2.60866879e-02,
       -2.95264551e-02,  3.93884742e-02, -2.28475665e-02, -6.89586382e-02,
        9.07938965e-02, -7.01272184e-02, -4.31429562e-02, -4.44394261e-02,
       -3.99916836e-02, -8.57988959e-02, -4.65823002e-02, -8.67159560e-02,
       -5.90027168e-02, -7.47831357e-02, -1.00582427e-01,  1.54308927e-01,
       -1.92014151e-03,  9.11744429e-02,  6.61664115e-02,  1.91523421e-02,
        1.40991686e-02, -8.40122541e-02,  2.08141831e-02,  1.13986433e-01,
        3.70342419e-02,  3.29378373e-02,  6.19243480e-02,  2.39760128e-02,
        2.95271117e-03,  5.63252171e-02, -1.82790384e-02,  4.76904814e-02,
       -9.42604760e-02, -3.50648880e-02, -5.34658016e-03,  3.61661725e-02,
        6.59257134e-04,  4.07869373e-02,  5.19227367e-03, -7.01502402e-02,
        8.63378827e-02,  6.07805008e-02,  1.56899465e-02, -3.39765667e-02,
        1.18362905e-02, -2.14111143e-02, -2.11360247e-02, -2.59754405e-02,
        3.32091137e-02, -2.93350397e-02, -5.97348112e-02, -6.67539339e-02,
        8.17051480e-02, -9.15452824e-02,  6.08664786e-02,  2.83306240e-02,
       -1.11373187e-02, -4.78292216e-02,  6.27127057e-02,  4.47246085e-02,
        1.81832393e-02,  2.97440950e-02,  1.54823698e-02,  7.44846277e-02,
       -1.06191514e-01,  4.31075798e-02,  4.87904172e-02, -3.31321455e-02,
       -2.53165045e-02,  5.09542409e-02,  1.49928772e-02, -3.13048450e-02,
       -4.31680086e-02, -9.70238077e-03,  3.49189270e-02, -5.00607629e-02,
       -2.78644524e-02, -1.15162706e-02, -6.67792748e-03, -6.34777173e-02,
       -1.28724466e-02, -3.19388770e-03,  3.72879101e-02,  6.80944210e-02,
       -6.23494544e-02, -2.18357552e-02,  1.28684765e-02,  4.82037220e-02,
       -2.67934565e-02, -8.00952893e-02,  4.30659853e-02,  6.39816738e-03,
        7.60382863e-02,  1.61195806e-02,  1.04470980e-02,  1.57153874e-02,
        4.74881665e-02, -3.39647566e-03,  4.25682437e-02, -8.18957985e-02,
       -9.99425886e-02,  1.01479498e-01, -2.74488698e-02,  3.88942612e-02,
        3.48795034e-02, -6.30539597e-02, -9.61107758e-02, -2.20958918e-02,
        5.21553176e-03,  5.10913702e-02, -1.09651127e-02,  6.11926341e-02,
       -2.81968054e-02,  1.03958087e-02, -1.40593450e-02, -4.38312147e-03,
       -4.15606644e-02, -7.15028241e-03, -4.09682559e-03,  2.94833932e-02,
       -6.47242564e-02, -5.28085279e-02,  2.22829405e-02, -1.81002230e-02,
        5.56993492e-02, -1.17216557e-02, -8.38164092e-03,  2.94403110e-02,
        7.89064970e-03, -1.29428241e-02,  2.27415436e-02, -6.62184063e-04,
       -5.32119900e-02, -7.26887608e-04, -1.32425244e-02, -2.97901371e-02,
       -4.28290855e-02, -2.06525807e-02, -5.70552879e-03,  6.39578739e-02,
        6.32670286e-02,  4.09602195e-02, -3.77268297e-02,  5.36049135e-03,
       -7.58462657e-03,  3.99814513e-02,  3.23368996e-02,  3.67292178e-03,
       -1.18306637e-03, -2.44927566e-02, -2.72224753e-02,  7.46084731e-02,
        1.99077092e-02,  2.88026925e-02, -6.40626586e-02,  4.42266539e-03,
        2.48693918e-02, -1.62406770e-02,  2.78335835e-02, -5.67662737e-02,
       -1.38384826e-02,  1.81485266e-03, -1.08305813e-02,  1.32847537e-02,
        4.56084180e-02,  5.94186823e-02, -3.45238464e-02,  2.26064225e-02,
       -2.43217604e-02, -3.60886234e-03, -2.51840039e-02,  2.63223971e-02,
        2.11075655e-02, -5.66854373e-02,  3.78267887e-02, -1.72046481e-02,
       -2.55984655e-02, -3.76629263e-02, -1.75718682e-03, -4.16402436e-02,
        2.43030922e-02,  8.67850057e-03, -4.37816210e-02, -1.20986793e-02,
       -4.30054269e-03, -1.77714463e-02,  3.14758258e-02,  2.49245141e-02,
        5.53522153e-03, -3.01820819e-02, -1.46665568e-02, -6.40855194e-03,
        1.50524752e-02, -3.87897388e-02,  2.69766605e-02, -1.37657512e-02,
        3.66229638e-02, -2.92435056e-02,  1.57601317e-02,  1.67634611e-02,
       -2.32958346e-02, -9.33188107e-03,  1.61604065e-02, -5.31259429e-02,
       -1.57259663e-02,  5.76466059e-02, -8.49186526e-03, -2.32710577e-02,
        2.90951793e-02,  6.37005445e-03, -8.95428901e-03,  3.26873677e-03,
        5.01591124e-03, -1.13647470e-02,  1.71646032e-02, -3.44291665e-02,
       -1.46314623e-02, -3.43118047e-02, -4.04514709e-03, -2.33022456e-03,
        3.76911329e-02, -9.82197885e-03,  3.41404418e-02, -1.88543123e-02,
        1.59584037e-02, -2.64945134e-02,  5.87028327e-02,  3.43228326e-02,
       -4.50506136e-03, -1.89628322e-02,  1.24710382e-02,  1.39012412e-02,
       -1.43159741e-02,  1.38757982e-03, -2.12869796e-02, -1.24273396e-02,
       -4.73782918e-02,  9.17631921e-03, -3.68676072e-02,  8.85750239e-03,
        3.19357904e-02,  1.48213827e-02,  8.11787642e-04, -5.06121986e-03,
        6.21752811e-03, -1.02659645e-02,  1.86230306e-02,  2.13775600e-02,
        1.50029665e-02, -2.20459553e-02, -1.09735996e-02,  1.65609874e-03,
       -1.13774494e-02, -1.80169298e-02, -7.02313788e-02, -1.09106603e-02,
        3.38899193e-02, -1.68830257e-03, -1.74751232e-03,  1.17659866e-02,
       -1.49495712e-02,  2.05932873e-02,  4.74549993e-03,  7.27791347e-03,
       -1.68098996e-02,  4.84633512e-03,  1.64989022e-02,  2.13887311e-02,
        2.50391451e-02, -3.91247665e-02,  1.45623090e-02, -9.06398902e-03,
       -2.02161925e-02,  2.32413632e-02,  1.48710437e-02,  1.00830293e-02,
        1.45607327e-02, -2.40110471e-02, -5.22900272e-03,  1.98362887e-02,
        1.71283245e-02, -3.12125855e-03, -4.90591746e-03, -1.50743166e-02,
       -1.71874372e-02, -1.66721875e-03, -6.82436742e-03, -3.35406756e-02,
       -4.62125369e-03,  1.55656807e-02, -1.41865656e-02, -9.88305070e-03,
        6.39890130e-03, -7.22679579e-03,  2.75782729e-02,  1.55248478e-02,
       -1.24821849e-02,  4.87696117e-02,  2.68652640e-02,  3.05540926e-02,
        1.20360106e-02,  3.59798399e-02, -7.99099631e-03,  2.71205336e-04,
        3.34464650e-03, -1.59768795e-02,  5.92732123e-04,  1.30280225e-02,
       -6.58330202e-03, -6.91739499e-03,  2.92236242e-03, -7.96074922e-03,
        2.04380782e-02,  1.70817944e-02, -2.24355344e-02,  2.08475646e-02,
        1.06802564e-02,  1.70988336e-02,  2.00281228e-02, -7.90715191e-03,
       -8.25807539e-03, -1.99555384e-03,  2.12734724e-02,  6.96826056e-03,
       -2.19774619e-02, -4.85669832e-04, -4.47728673e-03, -7.88204820e-03,
        1.29065471e-02, -2.25996995e-02,  1.95498783e-02,  8.47591807e-03,
       -1.49403905e-02,  2.43803769e-03, -2.47762580e-02, -5.17996330e-03,
       -2.41172208e-02, -1.46182612e-03, -7.64142105e-03, -1.64245014e-02,
       -2.46304981e-02, -2.07228524e-02,  1.30247906e-02, -2.50787199e-02,
        1.09179309e-02, -4.59552116e-03, -2.29089762e-02, -6.45809495e-04,
        2.47994114e-02,  1.86300804e-02,  9.36932349e-03, -1.15446992e-02,
        9.10980172e-03, -1.64812812e-03,  1.77135480e-02,  1.11838419e-02,
        1.96650913e-02, -7.13249878e-04,  1.79155108e-02, -1.94227739e-02,
        8.57554694e-03, -6.41204037e-03,  2.03064702e-02,  6.07056653e-03,
        7.55866393e-03, -1.08279291e-02, -5.45714286e-03,  1.89638955e-02,
       -2.37178950e-03,  2.93702579e-03, -1.98591582e-03,  9.07785580e-03,
        1.02387043e-02,  9.55760130e-03, -4.13389455e-03,  4.88869911e-03,
       -2.09022322e-03,  2.29941579e-02,  1.95913979e-02,  5.89818267e-03,
       -1.76999275e-02, -1.39575763e-03, -3.96989552e-03,  2.59356605e-03,
       -9.84072415e-03,  1.20844070e-02,  1.10212548e-02, -5.58410040e-03,
        6.41596830e-03,  2.01676547e-02, -1.48129290e-02, -2.19954202e-02,
        6.51234635e-03, -1.23302481e-02, -9.50452013e-03, -1.95074456e-03,
        2.39532568e-03, -1.91585446e-02,  2.37710772e-03, -1.24778701e-02,
       -3.83117125e-03, -1.83892233e-02, -9.96373364e-04, -6.43887176e-03,
        8.68554593e-05,  7.47053602e-03,  1.04026012e-02, -1.17320581e-02,
        1.76894549e-02,  1.41085456e-03,  1.06000560e-02, -3.85038987e-03,
       -1.46247771e-02, -2.21060480e-03, -5.90728965e-03, -6.23198894e-03,
       -4.73098585e-05, -1.28427291e-02, -1.06276575e-02,  3.46175375e-02,
        2.34909371e-03,  1.25130731e-02,  1.44695976e-02, -2.85020570e-02,
        2.14169890e-02,  6.42639528e-04, -6.61425810e-03,  1.23803303e-02,
       -1.30130406e-02,  1.31847416e-02,  6.95291316e-03, -1.01713530e-02,
       -2.34586231e-02,  7.55352391e-03, -2.42339073e-03,  2.81531881e-03,
       -8.09330556e-03,  1.46024531e-03,  8.43866256e-03,  1.76729136e-02,
       -9.42561830e-03,  1.05115808e-02,  6.17952298e-04,  7.84409793e-05,
       -2.67414306e-03,  1.06539005e-02, -1.15745035e-02,  1.10435138e-03,
        2.12729128e-02, -1.09123877e-02, -1.19853956e-02,  8.70849197e-03,
        2.32998518e-02,  7.06018536e-04, -1.66798712e-02, -1.38597907e-02,
        3.62417458e-03, -2.77894973e-02,  3.28176160e-03, -1.83243444e-03,
       -4.52588018e-03,  1.63081797e-02, -6.88991989e-03,  1.77839810e-02,
        1.35698450e-02,  1.67258163e-02,  1.93471265e-02,  5.59415874e-03,
       -1.32735965e-02,  3.44645002e-03,  2.14482082e-03,  7.30462373e-03,
        8.88912335e-03, -8.27817873e-03,  1.44185893e-02, -1.46221008e-02,
        1.31656450e-02, -5.08927061e-03,  1.05760559e-02, -1.14050906e-02,
        6.97374535e-03, -1.06324138e-02, -5.30765090e-03,  1.00861448e-03,
       -5.32815149e-03, -1.52846624e-03,  2.73358638e-03,  1.13078303e-02,
       -4.25339287e-03, -4.06290885e-03,  1.41369977e-02,  7.26195743e-04,
        1.82635643e-02,  2.61428305e-03,  3.97988506e-03,  1.02040000e-02,
       -2.01286733e-02, -4.05070307e-03,  1.38874235e-02, -8.47791786e-03,
        2.00162367e-02, -2.97540123e-03, -2.12315891e-02, -1.17929912e-02,
       -3.32077867e-03,  2.66884772e-02, -7.68446976e-03,  1.21469055e-02,
        1.46967955e-02,  1.86047594e-02, -1.86064577e-03, -1.58553611e-02,
       -1.63635472e-02, -5.22816021e-03, -5.35368904e-04, -9.33406581e-03,
       -1.60323882e-02, -6.93583905e-03, -8.09893449e-03, -1.47886628e-03,
       -8.36648820e-03, -5.74765142e-03,  9.44841058e-03, -8.67920182e-03,
        3.24347524e-03,  9.23062037e-03, -6.66867291e-03,  9.37055588e-03,
        5.64726880e-03, -4.82323780e-03,  1.29579190e-02,  3.95707388e-03,
       -2.14546525e-03,  4.77907282e-03, -1.96449036e-02,  7.79797377e-03,
        1.31870217e-02,  8.75614106e-03, -2.92136899e-03,  1.02947378e-02,
       -3.61717487e-04,  7.77991087e-03,  5.22757502e-04,  5.10654686e-03,
        3.07824254e-03, -2.40533003e-02,  1.12723283e-02,  1.35363973e-04,
       -1.31675256e-02,  1.38240503e-02, -3.23948942e-03, -1.66935924e-03,
       -1.43890252e-02,  9.06985149e-03,  6.71542946e-03,  8.74083428e-03,
        8.72935450e-03,  9.33055251e-03, -7.74201424e-03, -1.35733213e-02,
        6.81518287e-04,  9.26638232e-03, -3.91287975e-03,  1.51576702e-03,
        1.55870726e-02,  1.00972389e-02, -1.72920046e-02, -9.91703306e-03,
        4.60226226e-03,  2.94762515e-03, -2.19707932e-03, -3.95474115e-03,
       -1.40430818e-02,  2.04716961e-03,  9.68675741e-03,  6.03418300e-03,
        1.02645113e-02, -3.45892108e-03,  1.51065844e-02,  3.81631677e-03,
        5.89740172e-03, -8.23732540e-04, -2.85351708e-03, -1.05487256e-03,
        6.77485551e-03,  5.35714924e-03, -2.68086090e-03,  3.31994213e-03,
        7.22070936e-03,  8.04787461e-03,  1.04342827e-02, -5.22315143e-04,
        5.13894754e-03,  5.39331786e-03, -3.26409752e-03,  2.04352700e-03,
       -7.29248238e-03, -6.07035044e-03,  5.46225558e-03,  3.73279083e-03,
       -4.46884648e-03, -1.18644566e-02, -1.57749948e-03,  2.03771117e-02,
        5.27676034e-03,  1.28701506e-02,  9.65089837e-05, -4.02354667e-03,
       -1.76346230e-03, -3.85166420e-03, -3.55916200e-03,  9.60274292e-03,
       -1.32697491e-02,  2.54464450e-03,  1.28002780e-02,  7.71107722e-03,
       -4.99809720e-03, -4.80023877e-03,  5.62744991e-03, -4.75425928e-03,
        3.38257789e-03, -5.01587973e-03, -9.01290220e-04, -5.42780265e-03,
       -6.68530462e-03,  1.34614665e-02, -3.52229999e-03,  5.70222751e-03,
       -7.16615533e-03, -5.28735241e-04, -1.02203287e-02, -4.86041879e-03,
        6.12408058e-03,  5.58205943e-03, -3.07058549e-03, -5.88339302e-03,
        1.74858904e-03,  2.96937219e-03,  1.03337996e-02,  1.39285822e-03,
        1.52525256e-02,  1.36108182e-02,  3.63184032e-04,  3.91598506e-03,
        3.85077132e-03,  7.54374590e-03,  3.99080506e-03, -7.91427478e-03,
        2.62019828e-04, -9.35120638e-03, -7.82059491e-03, -4.38934759e-04,
       -1.36110138e-02, -2.49737838e-04, -7.29809561e-03,  9.21317982e-03,
        6.43437658e-03, -1.05915123e-02, -7.05699796e-03, -3.24304649e-03,
       -2.79762593e-03, -6.47662125e-03,  1.29665415e-02, -1.87423938e-03,
       -1.20749461e-02,  2.20969282e-03, -7.10219863e-03, -4.75683114e-03,
       -2.08496801e-03,  5.23237196e-03,  3.71426304e-03,  5.08586923e-03,
        2.64793146e-03,  1.95044071e-02, -3.50508417e-03, -1.64426422e-03,
       -1.04724257e-02,  8.82063765e-03,  1.39913835e-02,  1.20964546e-02,
       -1.47525602e-02, -7.62910728e-03, -1.76981172e-04,  1.43171710e-02,
        4.68170915e-03, -5.75607240e-03,  5.37776039e-03, -2.28745260e-03,
        2.97194042e-03, -4.68033053e-03,  5.65034178e-03,  7.66705473e-03,
       -5.61849313e-04,  1.01230277e-02, -2.45885691e-03, -4.89986857e-03,
       -7.12890874e-03,  1.06600321e-02, -2.79022939e-03,  7.31888288e-03,
       -1.35842643e-03,  2.39856982e-03,  5.49204787e-04,  2.26671261e-03,
       -4.89896501e-03,  3.55565174e-04,  9.59399528e-03, -2.99849326e-03,
        5.06401275e-03, -1.52519754e-02,  8.75230430e-04, -2.73474932e-04,
       -8.27155875e-03, -2.67827378e-03, -4.35239157e-03,  3.55941694e-03,
       -5.94553642e-03,  1.64414365e-02,  9.22347837e-03,  4.42588385e-03,
       -7.09824092e-03,  1.04549310e-02,  5.59684676e-03,  1.29586059e-02,
       -9.23996985e-03, -1.75359743e-03,  2.36299326e-03,  1.67257963e-03,
       -1.01142728e-03, -3.35516370e-03, -7.06759314e-03,  4.12278111e-03,
        1.57749469e-03, -9.92251843e-03,  9.75901418e-03, -1.09232700e-03,
       -1.09242651e-02, -3.69798640e-04,  7.92662972e-03,  2.61483785e-03,
        8.77548964e-03, -5.99986101e-03,  7.16663142e-03,  1.09090807e-02])

In [209]:
len(image_embeddings)

2194

In [210]:
len(image_embeddings[0])

768

## Debug embeddings

In [211]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import normalize
from transformers import BertModel, BertTokenizer

e:\DoCode\CD2\source\Source\get_hrs_rs\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [224]:
from tqdm import tqdm

In [225]:
print("\n🤖 STEP 8 – BERT text embeddings")
xxx = pd.read_csv(os.path.join(ROOT, "items_features.csv"))

xxx["combined_text"]         = xxx["feature1"] + " " + xxx["feature2"]
xxx["cleaned_combined_text"] = xxx["combined_text"].apply(str.lower)

# ── GPU / CPU ──────────────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"   Device: {device}")

print("   Loading bert-base-uncased ...")
tokenizer  = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model = BertModel.from_pretrained("bert-base-uncased")
bert_model.to(device)
bert_model.eval()

BERT_BATCH = 32   # xử lý 32 text một lúc

def get_bert_embeddings_batch(texts: list) -> np.ndarray:
    """Trả về array (N, 768) cho một batch texts."""
    inputs = tokenizer(
        texts,
        return_tensors="pt",
        max_length=512,
        truncation=True,
        padding="max_length",
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = bert_model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).cpu().numpy()  # (N, 768)

texts = xxx["cleaned_combined_text"].tolist()
print(f"   Generating embeddings for {len(texts)} items  (batch={BERT_BATCH}) ...")

all_embeddings = []
from tqdm import tqdm as tqdm_std
for i in tqdm_std(range(0, len(texts), BERT_BATCH)):
    batch = texts[i : i + BERT_BATCH]
    all_embeddings.append(get_bert_embeddings_batch(batch))

text_embeddings = np.vstack(all_embeddings)

🤖 STEP 8 – BERT text embeddings
   Device: cpu
   Loading bert-base-uncased ...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2922.31it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

   Generating embeddings for 2194 items  (batch=32) ...

  0%|          | 0/69 [00:04<?, ?it/s]

KeyboardInterrupt:

In [219]:
xxx['combined_text'] = xxx['feature1'] + ' ' + xxx['feature2']
xxx['cleaned_combined_text'] = xxx['combined_text'].apply(preprocess_text)

# Tạo BERT embeddings cho văn bản
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4759.65it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [220]:
import torch

In [221]:
def get_bert_embeddings(text):
    inputs = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding='max_length')
    with torch.no_grad():
        outputs = model(**inputs)
    # BERT base có kích thước embedding là 768
    embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings

# text_embeddings = np.vstack(
#     xxx['cleaned_combined_text'].apply(lambda x: get_bert_embeddings(x)).to_numpy()
# )

In [222]:
text_embeddings = np.vstack(
    xxx['cleaned_combined_text'].apply(lambda x: get_bert_embeddings(x)).to_numpy()
)

KeyboardInterrupt:

In [ ]:
text_embeddings

array([[-1.32130712e-01, -4.80578125e-01,  2.61906356e-01,
         4.98509035e-04,  1.92617998e-02,  2.40128532e-01,
         1.13349840e-01,  1.76416248e-01, -1.37547314e-01,
        -3.16068172e-01, -9.78496224e-02, -1.42556384e-01,
        -1.66068539e-01,  5.95610365e-02, -1.39088720e-01,
         2.75807027e-02,  1.24800183e-01,  3.01254928e-01,
        -1.00319728e-01,  2.92990118e-01,  1.33612260e-01,
        -1.59170210e-01,  9.03117061e-02,  1.17086917e-01,
         4.02323544e-01, -5.27881086e-02, -1.23920990e-03,
         1.43134380e-02,  1.62785321e-01,  2.64486820e-01,
         1.20635331e-03, -6.07602671e-03,  1.51898682e-01,
        -1.17829554e-01,  4.28457148e-02, -3.87182057e-01,
        -1.99187919e-02, -3.18495594e-02, -4.16335613e-02,
        -9.95824933e-02, -2.50402868e-01, -6.39423504e-02,
         2.24446714e-01, -2.71887362e-01, -1.92225426e-01,
        -4.29721892e-01, -1.66247189e-01,  2.64995873e-01,
        -4.76105124e-01, -4.20513004e-02, -3.83637011e-01,
        -1.77786469e-01,  8.09589699e-02,  1.43876612e-01,
         6.85929060e-02,  3.08824003e-01, -1.33027598e-01,
         1.58328250e-01, -1.85837522e-01, -3.93068612e-01,
         7.37473667e-02, -3.24680269e-01,  9.23565477e-02,
         2.24616617e-01, -1.66878141e-02,  2.33029008e-01,
        -2.30094288e-02, -1.72935709e-01, -1.48305893e-01,
         1.46959424e-01, -8.96426067e-02,  2.45205551e-01,
         1.16420932e-01, -2.92239189e-01, -2.19903529e-01,
        -1.45852333e-02, -1.12884730e-01,  1.21205263e-01,
         3.75845909e-01,  9.38015729e-02, -2.72808429e-02,
         3.15641873e-02,  1.89835697e-01,  4.95841861e-01,
         6.45034462e-02,  2.67442882e-01, -6.55058622e-02,
         1.19342245e-01,  5.96749363e-03,  3.01417619e-01,
         7.26516321e-02, -9.98676643e-02,  2.35551953e-01,
         3.58365178e-02,  8.66854936e-02, -1.45180523e-01,
        -1.66113287e-01,  1.73596710e-01,  4.76680428e-01,
         2.35965475e-02, -3.00529063e-01, -1.35613620e-01,
        -4.73285206e-02,  2.06806660e-02, -2.90133595e-01,
        -2.01947778e-01, -8.54969304e-03, -3.78398895e-02,
         5.71457716e-03,  2.04489201e-01,  2.76107900e-02,
        -2.20877603e-02,  2.84488738e-01, -1.04900047e-01,
        -5.44357393e-03,  1.77052796e-01,  3.90127823e-02,
         1.46616064e-02,  3.07046697e-02,  1.79600060e-01,
         7.94766843e-03,  1.54295042e-01,  2.21931815e-01,
         2.96609640e-01, -3.69370803e-02,  1.22395858e-01,
        -6.40294775e-02,  3.93612772e-01, -1.47387860e-02,
        -1.19275481e-01,  7.98071828e-03,  7.46833980e-02,
        -1.68316469e-01,  1.07017815e-01, -5.10819554e-02,
        -1.64192706e-01,  1.51656657e-01,  1.03973737e-02,
         2.97844112e-01, -1.25153903e-02, -3.54179978e-01,
         4.62651491e-01,  2.71738052e-01, -2.86864877e-01,
         1.67007707e-02, -1.65912747e-01, -9.39880013e-02,
        -6.68347394e-03, -2.07736477e-01, -1.88567080e-02,
         2.92463422e-01, -1.22501709e-01,  1.73817396e-01,
        -2.03075141e-01, -1.89429879e-01,  1.92345291e-01,
         6.11555763e-03, -5.90242334e-02, -2.21425563e-01,
        -2.20615845e-02,  4.70936239e-01,  4.30437744e-01,
        -4.90242131e-02,  3.45554411e-01,  5.40286787e-02,
         1.07507808e-02, -6.75508678e-02,  4.17705923e-01,
         4.13872935e-02,  4.29504275e-01,  3.36332321e-01,
         1.98505938e-01,  4.49740797e-01,  2.27247313e-01,
        -1.90355048e-01,  2.64091611e-01, -5.97700849e-02,
         2.26201639e-01, -1.17000848e-01, -2.95819938e-02,
        -1.03406116e-01,  2.17995033e-01,  1.89359754e-01,
        -1.08523533e-01,  1.57556891e-01,  8.70022625e-02,
         7.84068406e-02,  7.28310347e-02,  7.11531099e-03,
        -2.51578271e-01, -3.23284924e-01, -2.58845389e-01,
        -4.18026373e-02, -4.62969020e-03,  4.35095541e-02,
        -2.21494824e-01, -4.32762802e-02,  4.10486877e-01,
        -1.20941982e-01,  2.37313628e-01,  4.26027864e-01,
         1.22738384e-01,  2.20431834e-01, -2.51361411e-02,
        -1.25416443e-01, -3.63363586e-02,  1.30986840e-01,
         2.89002024e-02, -1.10847510e-01, -1.94323286e-02,
         1.07715845e-01, -1.71375781e-01,  4.01002854e-01,
         5.19160479e-02,  9.02532190e-02, -4.18069735e-02,
         2.90577590e-01, -1.13077341e-02,  8.03397968e-02,
         1.52545189e-02,  3.70081306e-01, -9.31114107e-02,
        -3.56100112e-01,  1.03352115e-01, -2.13005245e-02,
         3.58622447e-02,  2.58834898e-01, -1.99628308e-01,
         1.44987702e-01,  3.55793715e-01, -2.47833490e-01,
        -2.67911732e-01, -8.53212774e-02,  8.06710571e-02,
        -9.09893811e-02,  1.84200466e-01, -1.15668746e-02,
        -9.15651023e-02,  2.16844857e-01, -1.06523603e-01,
         2.71142107e-02, -2.23270641e-03, -3.93080190e-02,
         6.92144632e-02, -2.50940442e-01, -2.84455102e-02,
         2.29143247e-01, -1.43797904e-01,  1.23462297e-01,
        -4.49476480e-01, -8.11484084e-02,  4.08695400e-01,
        -3.51869911e-02,  2.74552591e-02, -8.09885859e-02,
        -8.48175883e-02,  1.82121396e-01, -5.47155589e-02,
         2.79090226e-01,  4.20393169e-01,  4.81683873e-02,
         2.19369866e-02,  3.26988667e-01,  1.04671642e-01,
        -8.95101279e-02, -1.36081711e-03,  7.62939453e-04,
         1.76500618e-01,  1.81751043e-01,  6.48696423e-02,
        -1.74151719e-01,  8.47375989e-02, -1.79309145e-01,
         2.66606361e-01, -5.26512451e-02, -1.26955464e-01,
         1.90427542e-01,  1.17339091e-02, -1.47916168e-01,
        -1.28571644e-01, -2.14898944e-01,  2.70426311e-02,
         3.42338562e-01, -5.98337501e-02,  1.58745050e-01,
        -2.93859422e-01,  2.61856824e-01,  1.13292590e-01,
        -7.23389536e-02, -1.82122573e-01, -1.34235740e-01,
         4.31357324e-01, -2.16561005e-01, -3.69083226e-01,
         1.58360958e-01,  8.86119455e-02, -1.88984305e-01,
         2.97786176e-01,  2.37112969e-01, -9.26295519e-02,
         1.52231097e-01, -3.21977511e-02,  2.95609891e-01,
        -1.85104012e-01,  1.13354370e-01,  1.30484208e-01,
         9.59612429e-02, -3.40052843e-01, -6.40364170e+00,
         1.60598755e-01,  4.64463569e-02, -1.57005683e-01,
        -1.65389001e-01, -1.07510120e-01, -4.60514948e-02,
        -5.49661890e-02, -4.83550802e-02, -3.79212737e-01,
        -2.80465931e-04,  9.13467333e-02, -2.58339643e-01,
         3.92495543e-02, -1.34499907e-01,  3.61025095e-01,
         1.29643425e-01, -1.53862029e-01,  8.40432793e-02,
         1.53434321e-01,  9.38043296e-02, -5.11814505e-02,
         1.45528913e-01, -2.00451255e-01, -1.17974848e-01,
         1.53556019e-01,  1.13469800e-02, -2.23141149e-01,
        -2.22949624e-01, -2.25810409e-01, -6.20352104e-02,
        -1.12774789e-01,  2.10240334e-02,  2.23493315e-02,
         2.78976500e-01, -2.80020267e-01, -4.48191166e-02,
         1.65805593e-02,  3.12902451e-01,  1.46261543e-01,
         4.27815728e-02,  1.79360524e-01, -1.98173106e-01,
         3.47695559e-01,  2.40576267e-01, -2.55921692e-01,
         3.40188771e-01, -4.41722542e-01,  2.73976743e-01,
         2.26646274e-01,  4.95660678e-02, -1.18465394e-01,
        -1.85159832e-01, -4.51085418e-01, -2.00748295e-01,
         1.02644242e-01,  1.97818875e-03,  3.61489236e-01,
         5.93013316e-02, -2.72616416e-01, -2.27650911e-01,
         5.56510240e-02, -3.99764813e-03, -3.20810258e-01,
        -9.28988010e-02, -5.98195940e-04, -3.06954116e-01,
        -5.48616499e-02, -1.08850569e-01,  1.68130487e-01,
         2.26426676e-01,  6.69343118e-03,  2.31660139e-02,
        -3.06240857e-01,  1.23473763e-01, -1.01960406e-01,
         5.45359291e-02, -5.39351344e-01,  3.36780310e-01,
        -2.35310957e-01, -1.27840534e-01, -4.16934371e-01,
         3.78902495e-01,  3.09619844e-01, -1.28312737e-01,
        -3.33507992e-02,  1.79927260e-01,  2.99548600e-02,
        -1.37573957e-01,  1.79223418e-01,  3.97339463e-01,
        -8.42426866e-02, -1.90421596e-01, -3.84473689e-02,
        -3.93544324e-03,  6.52977079e-02,  1.53125376e-01,
        -5.51189065e-01,  6.19760677e-02, -2.30919868e-01,
         7.89422691e-02, -5.75489178e-02, -5.64390235e-02,
        -2.37775981e-01, -7.93055594e-02,  7.10738227e-02,
        -2.12780625e-01,  6.94753826e-02,  3.25845122e-01,
        -6.78929910e-02,  4.01482046e-01, -2.79131114e-01,
         1.42436296e-01, -2.25199252e-01,  2.83745416e-02,
        -1.10178985e-01, -8.04112479e-02,  1.28088295e-01,
        -2.13817488e-02, -1.76769763e-01,  1.01543859e-01,
         2.50536293e-01, -2.49424577e-01, -1.98201954e-01,
        -2.63947308e-01,  2.62322202e-02, -7.71389306e-02,
        -2.37330079e-01, -1.42233402e-01,  1.84340715e-01,
        -1.10091373e-01, -1.81779191e-01, -2.19640851e-01,
        -2.72523761e-01,  1.26054436e-01,  1.08669568e-02,
        -8.96360129e-02, -3.21447045e-01,  1.63200617e-01,
        -1.19876666e-02,  2.08650261e-01,  9.70781595e-02,
        -1.51902949e-03,  1.74628541e-01,  9.37879980e-02,
         3.19735169e-01, -1.73356652e-01, -9.60182548e-02,
        -9.46465805e-02,  9.64948088e-02,  9.91473049e-02,
        -1.03540674e-01, -3.32954042e-02, -1.43888772e-01,
        -2.27378398e-01, -1.33600399e-01,  3.55666041e-01,
         1.35063112e-01, -2.16268688e-01, -2.19009474e-01,
         2.63636321e-01, -2.79549479e-01, -9.23077166e-02,
         3.93938631e-01, -2.20613077e-01,  2.75668085e-01,
        -2.47801557e-01, -2.16111362e-01, -1.25634614e-02,
        -1.10986710e-01,  6.54742587e-03, -1.37484059e-01,
        -1.48470432e-01,  4.49475423e-02,  1.73663586e-01,
         2.61441350e-01,  4.64524217e-02, -6.36079013e-02,
        -1.75820634e-01,  1.73696697e-01,  1.30848736e-01,
        -1.86867058e-01,  6.67881593e-02,  8.17114264e-02,
         1.42999783e-01,  1.93829298e-01, -3.62111419e-01,
         2.28940964e-01,  6.34028241e-02,  1.55685425e-01,
         2.27758139e-01,  1.53904647e-01,  8.99831653e-02,
        -3.21790218e-01, -2.01508284e-01, -1.50936991e-01,
        -2.13749126e-01,  3.68751228e-01,  3.68827194e-01,
        -1.40332237e-01, -4.13230062e-01,  1.07777365e-01,
        -2.04547703e-01,  1.68401003e-01, -1.51613623e-01,
        -4.67998832e-02,  2.61930704e-01,  6.47733361e-02,
        -2.84100950e-01, -4.48811576e-02, -9.27679986e-03,
        -4.79344934e-01,  1.80348247e-01, -8.09885859e-02,
        -3.96406054e-01, -1.00402012e-01, -4.98737425e-01,
        -1.55996680e-01, -1.05450470e-02,  1.91057414e-01,
        -2.33687460e-01, -2.98494697e-01, -8.01328719e-02,
         1.47275031e-02, -1.46542415e-01,  1.80806816e-01,
         1.74796283e-01, -1.84591532e-01,  2.17041016e-01,
        -7.97411650e-02,  2.52437592e-01, -8.26918706e-02,
        -1.45545295e-02,  6.97630346e-02, -4.99196798e-02,
         1.53037207e-02, -3.99976611e-01, -1.13265350e-01,
         1.27385452e-01, -2.72009932e-02, -5.19805811e-02,
        -2.27151453e-01, -3.58947635e-01, -2.54014164e-01,
        -4.00681883e-01,  1.17322840e-01, -1.14154756e-01,
         9.59593430e-02, -2.14310274e-01,  3.96991491e-01,
        -6.81067780e-02, -2.46338755e-01, -3.53033878e-02,
        -4.61617112e-01, -1.25572205e-01, -4.14587975e-01,
         1.49934962e-01,  2.51317471e-01, -2.59223282e-01,
         3.92328016e-03, -5.19062765e-02,  1.24002710e-01,
        -3.29656564e-02,  3.92128676e-02, -1.76418480e-02,
         7.52978995e-02, -9.17313620e-03, -1.17343351e-01,
         2.79397927e-02,  2.00161621e-01,  1.02711782e-01,
         1.50723517e-01,  2.80332625e-01, -4.57366891e-02,
        -7.41845816e-02,  7.01623783e-02, -2.76270192e-02,
        -2.91334659e-01,  2.28041530e-01, -1.04562491e-01,
        -1.66420154e-02, -2.65286684e-01,  1.71705872e-01,
         1.77376255e-01,  7.23620877e-02, -5.60413301e-02,
        -3.88549566e-02, -1.36912435e-01, -2.11627662e-01,
         2.06987411e-01,  2.85155118e-01,  6.58864621e-03,
         4.33898997e-03, -2.03748628e-01, -1.59672827e-01,
         1.15332030e-01, -7.66973048e-02,  6.68710694e-02,
        -6.49619401e-02,  4.09574397e-02,  1.40597939e-01,
         2.46036857e-01,  2.10513696e-01, -2.41473690e-03,
         9.95092392e-02, -1.43140703e-02,  8.15885067e-02,
        -4.83965635e-01,  1.07608018e-02,  4.40208822e-01,
        -2.12363482e-01,  8.90740901e-02,  5.67807071e-02,
         2.63502419e-01, -3.64749610e-01, -1.41440243e-01,
        -2.49037951e-01, -3.24707218e-02,  8.37203488e-02,
         1.65735349e-01,  2.73644447e-01, -6.29359335e-02,
         1.53177261e-01,  1.49532214e-01, -3.05593282e-01,
         3.48349899e-01, -1.80983767e-01,  9.00380611e-02,
         1.81810427e-02,  2.17192635e-01, -6.86174491e-03,
         2.72285223e-01, -1.06113106e-02, -1.05980843e-01,
         2.91199327e-01,  1.11199141e-01, -3.23279530e-01,
        -1.42210096e-01, -5.32194525e-02,  1.46327373e-02,
         2.26535171e-01,  1.49452686e-01, -5.12509421e-02,
        -1.78770840e-01,  2.69635260e-01, -2.38245815e-01,
        -4.19224575e-02, -9.71343219e-02,  1.71081305e-01,
         1.10933036e-02,  1.31059423e-01, -6.29256293e-02,
        -1.46857500e-02, -1.47503287e-01, -8.01455081e-02,
         3.06143556e-02,  2.58365124e-01, -1.49316400e-01,
        -2.40121543e-01,  3.50208551e-01, -1.13466550e-02,
         2.35987768e-01, -2.97457367e-01, -1.82918180e-03,
        -1.98214144e-01,  1.55831557e-02, -1.02725938e-01,
         1.02697229e-02, -2.11898416e-01,  1.27640963e-01,
        -8.58409517e-03,  4.83402982e-03, -1.13053709e-01,
         1.17605038e-01,  5.78330234e-02,  2.59228677e-01,
         3.02422140e-03,  4.26272333e-01, -1.84674501e-01,
         3.39900911e-01, -1.40031695e-01,  1.52660996e-01,
        -1.39585480e-01, -8.91129225e-02, -1.89286202e-01,
        -3.79654944e-01, -1.51710361e-01,  2.51011923e-04,
        -6.84879720e-04, -4.44948673e-02, -3.22230766e-03,
        -2.45268553e-01, -4.91974801e-02,  9.12382230e-02,
         4.44179624e-02, -1.97152585e-01,  3.40343595e-01,
         3.96182269e-01,  2.36212790e-01,  9.15680826e-02,
         1.64490446e-01,  5.21150678e-02, -4.88291904e-02,
         2.10357770e-01, -4.61411960e-02,  1.20537356e-01,
         2.05589905e-01,  1.40147805e-01, -1.05749391e-01,
        -7.99807757e-02, -1.15914308e-02,  2.64871657e-01,
        -2.37172633e-01,  2.20415294e-01,  4.52686101e-02,
        -2.48215884e-01,  8.12888592e-02, -1.58735942e-02,
        -1.67199016e-01, -2.54656821e-01, -2.68456072e-01,
        -3.55147570e-01,  6.88820779e-02,  1.80961475e-01,
         1.58511221e-01,  2.25879148e-01, -9.79743712e-03,
         1.81285858e-01,  8.05563033e-02,  1.46003831e-02,
        -2.07978129e-01, -6.19591698e-02, -1.68775618e-01,
         1.28434896e-01, -2.14846760e-01,  1.81692719e-01,
        -7.06792772e-02, -2.14030460e-01, -3.53491306e-02,
        -1.53296635e-01,  6.58661723e-02, -2.47017264e-01,
        -6.35286421e-02,  4.63183522e-02,  1.94279671e-01,
         2.65250802e-01, -2.28229851e-01,  2.50935465e-01,
        -2.41400585e-01, -2.94322461e-01, -2.10735667e-02,
        -3.52898896e-01,  3.84359509e-02, -1.28072709e-01,
        -1.87154815e-01, -3.21229577e-01,  5.28530926e-02,
         3.37179415e-02, -1.27532825e-01, -1.67819113e-01]], dtype=float32)

In [ ]:
# Chuyển đổi về float32
text_embeddings = text_embeddings.astype(np.float32)
image_embeddings = image_embeddings.astype(np.float32)

In [ ]:
# Kiểm tra kiểu dữ liệu (dtype), kích thước (shape), và số chiều (ndim)
print("Text Embeddings:")
print("Type:", type(text_embeddings))
print("Data type (dtype):", text_embeddings.dtype)
print("Shape:", text_embeddings.shape)
print("Number of dimensions (ndim):", text_embeddings.ndim)

print("\nImage Embeddings:")
print("Type:", type(image_embeddings))
print("Data type (dtype):", image_embeddings.dtype)
print("Shape:", image_embeddings.shape)
print("Number of dimensions (ndim):", image_embeddings.ndim)

Text Embeddings:
Type: <class 'numpy.ndarray'>
Data type (dtype): float32
Shape: (1, 768)
Number of dimensions (ndim): 2

Image Embeddings:
Type: <class 'numpy.ndarray'>
Data type (dtype): float32
Shape: (8944, 768)
Number of dimensions (ndim): 2