In [1]:
!lscpu

Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          46 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   4
  On-line CPU(s) list:    0-3
Vendor ID:                GenuineIntel
  Model name:             Intel(R) Xeon(R) CPU @ 2.00GHz
    CPU family:           6
    Model:                85
    Thread(s) per core:   2
    Core(s) per socket:   2
    Socket(s):            1
    Stepping:             3
    BogoMIPS:             4000.31
    Flags:                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge m
                          ca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht sysc
                          all nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xt
                          opology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq
                           ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt
                           aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dno
                          wprefetch pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust
                           bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f
                          avx512dq rdseed adx smap clflushopt clwb avx512cd avx5
                          12bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_c
                          lear arch_capabilities
Virtualization features:
  Hypervisor vendor:      KVM
  Virtualization type:    full
Caches (sum of all):
  L1d:                    64 KiB (2 instances)
  L1i:                    64 KiB (2 instances)
  L2:                     2 MiB (2 instances)
  L3:                     38.5 MiB (1 instance)
NUMA:
  NUMA node(s):           1
  NUMA node0 CPU(s):      0-3
Vulnerabilities:
  Gather data sampling:   Not affected
  Itlb multihit:          Not affected
  L1tf:                   Mitigation; PTE Inversion
  Mds:                    Mitigation; Clear CPU buffers; SMT Host state unknown
  Meltdown:               Mitigation; PTI
  Mmio stale data:        Vulnerable: Clear CPU buffers attempted, no microcode;
                           SMT Host state unknown
  Reg file data sampling: Not affected
  Retbleed:               Mitigation; IBRS
  Spec rstack overflow:   Not affected
  Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prct
                          l
  Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointe
                          r sanitization
  Spectre v2:             Mitigation; IBRS; IBPB conditional; STIBP conditional;
                           RSB filling; PBRSB-eIBRS Not affected; BHI SW loop, K
                          VM SW loop
  Srbds:                  Not affected
  Tsx async abort:        Mitigation; Clear CPU buffers; SMT Host state unknown

# Library

In [2]:
# Import các thư viện cần thiết

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Flatten, Input
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

import os
import cv2


import matplotlib.pyplot as plt
import seaborn as sns

# Mining Dataset

# Xử lý outfits

In [3]:
with open('/kaggle/input/vibrent-clothes-rental-dataset/outfits.csv', 'r') as f:
    lines = f.readlines()

# In các dòng đầu tiên để kiểm tra định dạng
for i in range(5):
    print(lines[i])

id;name;description;group;owner;timeCreated;retailPrice;pricePerWeek;pricePerMonth;outfit_tags;tag_categories

outfit.fffdaa715c3646f8b1c0f04d549ff07e;Out of stock - Asymmetric Frilled Dress;This fun, short dress features and asymmetric neckline and an eye catching metallic sheen. Concealed zipper fastening on the side.;group.50a586c78eb7626e294ba3bd07d12c79;o_00053;2017-12-30 11:28:01.000;4000.0000;600.0000;1200.0000;['Synthetic', 'Statement', 'Dresses', 'Metallic', 'Mini', 'Cotton', 'S', 'Black', 'Sandro'];['Material', 'Occasion', 'Category', 'Details', 'Length', 'Material', 'Size', 'Color', 'Brand']

outfit.fffa1b9a3db6415d806f3c48f8ab58d9;Yellow Shell Mellomholmene Blouse;This beautiful blouse features an adjustable neckline, a short and wide silhouette, and ruching details on the sleeves. The cotton fabric makes this the perfect blouse for warmer days. ;group.61ad2fcabb3e9197e3836376e6b67f2c;o_00577;2021-06-07 12:07:22.921;1300.0000;590.0000;1180.0000;['ILAG', 'Tops', 'Spring', 'Summer', 'M', 'Pattern', 'Yellow', 'Women', 'Blouses', 'Everyday', 'Cotton'];['Brand', 'Category', 'Seasons', 'Seasons', 'Size', 'Details', 'Color', 'Gender', 'Category', 'Occasion', 'Material']

outfit.fff175b13ceb453f9928625491412ede;Kaula Dress Black;Kaula from Rodebjer is a fitted dress made in mid-thigh length and sleeves in regular length. This dress is made in a vibrant seasonal print, printed on 100 % recycled polyester. Kaula is designed with an all over smock to create the perfect fit. Fits true to size: Choose your normal size.;group.37c2b59d63d3a9c2d58e07f532f71f7f;o_00336;2023-06-05 09:17:59.004;3100.0000;930.0000;1860.0000;['Black', 'Mini', 'M', 'Everyday', 'Multi Season', 'Women', 'Dresses', 'Synthetic', 'Rodebjer'];['Color', 'Length', 'Size', 'Occasion', 'Seasons', 'Gender', 'Category', 'Material', 'Brand']

outfit.ffef9d7c292a48b69076d2df2e32352f;For sale - Jarvis Blouse;This wrap blouse has mid length sleeves and a fun, floral pattern. The cotton feels light on your skin.;group.dfcaa57546b0b7a5e9eb204449b6cc1c;o_00030;2021-05-18 14:02:28.690;1500.0000;590.0000;1180.0000;['XS', 'Multi Season', 'Stylein', 'Tops', 'Cotton', 'Multicolor', 'Wrap', 'Floral', 'Women'];['Size', 'Seasons', 'Brand', 'Category', 'Material', 'Color', 'Fit', 'Details', 'Gender']

In [4]:
outfits = pd.read_csv('/kaggle/input/vibrent-clothes-rental-dataset/outfits.csv', sep=';', on_bad_lines='skip')

In [5]:
import ast

# Chuyển đổi chuỗi thành danh sách
outfits['outfit_tags'] = outfits['outfit_tags'].apply(ast.literal_eval)
outfits['tag_categories'] = outfits['tag_categories'].apply(ast.literal_eval)

In [6]:
outfits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15649 entries, 0 to 15648
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              15649 non-null  object
 1   name            15647 non-null  object
 2   description     15261 non-null  object
 3   group           15626 non-null  object
 4   owner           15649 non-null  object
 5   timeCreated     15649 non-null  object
 6   retailPrice     14489 non-null  float64
 7   pricePerWeek    15649 non-null  float64
 8   pricePerMonth   15649 non-null  float64
 9   outfit_tags     15649 non-null  object
 10  tag_categories  15649 non-null  object
dtypes: float64(3), object(8)
memory usage: 1.3+ MB

In [7]:
outfits.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
0,outfit.fffdaa715c3646f8b1c0f04d549ff07e,Out of stock - Asymmetric Frilled Dress,"This fun, short dress features and asymmetric ...",group.50a586c78eb7626e294ba3bd07d12c79,o_00053,2017-12-30 11:28:01.000,4000.0,600.0,1200.0,"[Synthetic, Statement, Dresses, Metallic, Mini...","[Material, Occasion, Category, Details, Length..."
1,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,"[ILAG, Tops, Spring, Summer, M, Pattern, Yello...","[Brand, Category, Seasons, Seasons, Size, Deta..."
2,outfit.fff175b13ceb453f9928625491412ede,Kaula Dress Black,Kaula from Rodebjer is a fitted dress made in ...,group.37c2b59d63d3a9c2d58e07f532f71f7f,o_00336,2023-06-05 09:17:59.004,3100.0,930.0,1860.0,"[Black, Mini, M, Everyday, Multi Season, Women...","[Color, Length, Size, Occasion, Seasons, Gende..."
3,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,"[XS, Multi Season, Stylein, Tops, Cotton, Mult...","[Size, Seasons, Brand, Category, Material, Col..."
4,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,"[Cotton, Black, Everyday, Knitwear, L, Winter,...","[Material, Color, Occasion, Category, Size, Se..."

In [8]:
outfits['outfit_tags'][0][0]

'Synthetic'

In [9]:
outfits['group'][0]

'group.50a586c78eb7626e294ba3bd07d12c79'

In [10]:
outfits.isnull().sum()

id                   0
name                 2
description        388
group               23
owner                0
timeCreated          0
retailPrice       1160
pricePerWeek         0
pricePerMonth        0
outfit_tags          0
tag_categories       0
dtype: int64

In [11]:
print(outfits[['name', 'description']].isnull().sum())

name             2
description    388
dtype: int64

In [12]:
# Lấy các dòng có cột 'name' là null
outfits_null_name = outfits[outfits['name'].isnull()]

# Hiển thị kết quả
outfits_null_name

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
10624,outfit.5faafa92b722481ab1414e07380fa463,NaN,NaN,NaN,o_00530,2018-03-22 10:53:01.000,NaN,850.0,1200.0,"[Viscose, Dresses, Reformation, M, Midi, Blue]","[Material, Category, Brand, Size, Length, Color]"
15555,outfit.01b2284d2ea24bfda29e1edc6f2fc0f9,NaN,NaN,group.d2ae7472df69e50536b2f36d37f62861,o_00530,2018-11-26 15:17:49.000,NaN,0.0,0.0,[byTiMo],[Brand]

In [13]:
null_outfit_ids = outfits[outfits['name'].isnull()]['id']
null_outfit_ids

10624    outfit.5faafa92b722481ab1414e07380fa463
15555    outfit.01b2284d2ea24bfda29e1edc6f2fc0f9
Name: id, dtype: object

với cột name loại bỏ missing

In [14]:
outfits = outfits.dropna(subset=['name'])

vơí cột des giữ nguyên thay missing bằng "No description available" nghĩa là không mô tả khả dụng, đảm bảo đầu vào cho mô hình ( tùy trường hợp )

In [15]:
outfits['description'] = outfits['description'].fillna('No description available')

In [16]:
outfits.reset_index(drop=True, inplace=True)  # Đặt lại chỉ mục

In [17]:
outfits.isnull().sum()

id                   0
name                 0
description          0
group               22
owner                0
timeCreated          0
retailPrice       1158
pricePerWeek         0
pricePerMonth        0
outfit_tags          0
tag_categories       0
dtype: int64

In [18]:
outfits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15647 entries, 0 to 15646
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              15647 non-null  object
 1   name            15647 non-null  object
 2   description     15647 non-null  object
 3   group           15625 non-null  object
 4   owner           15647 non-null  object
 5   timeCreated     15647 non-null  object
 6   retailPrice     14489 non-null  float64
 7   pricePerWeek    15647 non-null  float64
 8   pricePerMonth   15647 non-null  float64
 9   outfit_tags     15647 non-null  object
 10  tag_categories  15647 non-null  object
dtypes: float64(3), object(8)
memory usage: 1.3+ MB

In [19]:
outfits.describe()

        retailPrice  pricePerWeek  pricePerMonth
count  14489.000000  15647.000000   15647.000000
mean    2669.603699    671.680769    1314.135361
std     2806.482337    214.003414     461.197713
min        0.000000      0.000000       0.000000
25%     1500.000000    590.000000    1180.000000
50%     2000.000000    590.000000    1180.000000
75%     3000.000000    810.000000    1620.000000
max    80000.000000   5250.000000   10500.000000

In [20]:
outfits.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
0,outfit.fffdaa715c3646f8b1c0f04d549ff07e,Out of stock - Asymmetric Frilled Dress,"This fun, short dress features and asymmetric ...",group.50a586c78eb7626e294ba3bd07d12c79,o_00053,2017-12-30 11:28:01.000,4000.0,600.0,1200.0,"[Synthetic, Statement, Dresses, Metallic, Mini...","[Material, Occasion, Category, Details, Length..."
1,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,"[ILAG, Tops, Spring, Summer, M, Pattern, Yello...","[Brand, Category, Seasons, Seasons, Size, Deta..."
2,outfit.fff175b13ceb453f9928625491412ede,Kaula Dress Black,Kaula from Rodebjer is a fitted dress made in ...,group.37c2b59d63d3a9c2d58e07f532f71f7f,o_00336,2023-06-05 09:17:59.004,3100.0,930.0,1860.0,"[Black, Mini, M, Everyday, Multi Season, Women...","[Color, Length, Size, Occasion, Seasons, Gende..."
3,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,"[XS, Multi Season, Stylein, Tops, Cotton, Mult...","[Size, Seasons, Brand, Category, Material, Col..."
4,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,"[Cotton, Black, Everyday, Knitwear, L, Winter,...","[Material, Color, Occasion, Category, Size, Se..."

# Xử lý picture_triplets

In [21]:
with open('/kaggle/input/vibrent-clothes-rental-dataset/picture_triplets.csv', 'r') as f:
    lines = f.readlines()

# In các dòng đầu tiên để kiểm tra định dạng
for i in range(5):
    print(lines[i])

picture.id;outfit.id;displayOrder;file_name

picture.0000cdba64314d84a49ed1c266589cc0;outfit.794483397da8425a813301eecf9828c6;0;0000cdba64314d84a49ed1c266589cc0.jpg

picture.00058abb53434872ae9bb4270ae21f8e;outfit.98f32aaf08bc4ff09c44e6e11e9199bc;2;00058abb53434872ae9bb4270ae21f8e.jpg

picture.00063f52c36d43ada95da45f819b30b4;outfit.9fd1c42c3db543c5b6e53b0db1ee8c0f;3;00063f52c36d43ada95da45f819b30b4.jpg

picture.0008443461814f5c988f123718bbd20e;outfit.a7539783b6e94591bdf4e10339afc1d7;3;0008443461814f5c988f123718bbd20e.jpg

In [22]:

pictures= pd.read_csv('/kaggle/input/vibrent-clothes-rental-dataset/picture_triplets.csv' , sep=';', on_bad_lines='skip')

In [23]:
pictures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50193 entries, 0 to 50192
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    50193 non-null  object
 1   outfit.id     50193 non-null  object
 2   displayOrder  50193 non-null  int64
 3   file_name     50193 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.5+ MB

In [24]:
pictures.head()

,picture.id,outfit.id,displayOrder,file_name
0,picture.0000cdba64314d84a49ed1c266589cc0,outfit.794483397da8425a813301eecf9828c6,0,0000cdba64314d84a49ed1c266589cc0.jpg
1,picture.00058abb53434872ae9bb4270ae21f8e,outfit.98f32aaf08bc4ff09c44e6e11e9199bc,2,00058abb53434872ae9bb4270ae21f8e.jpg
2,picture.00063f52c36d43ada95da45f819b30b4,outfit.9fd1c42c3db543c5b6e53b0db1ee8c0f,3,00063f52c36d43ada95da45f819b30b4.jpg
3,picture.0008443461814f5c988f123718bbd20e,outfit.a7539783b6e94591bdf4e10339afc1d7,3,0008443461814f5c988f123718bbd20e.jpg
4,picture.000a5db3362049aebcc1eb2bf7bde95f,outfit.745fa2bc8156478bac6c0f7d46dadbda,1,000a5db3362049aebcc1eb2bf7bde95f.jpg

In [25]:
null_outfit_ids

10624    outfit.5faafa92b722481ab1414e07380fa463
15555    outfit.01b2284d2ea24bfda29e1edc6f2fc0f9
Name: id, dtype: object

In [26]:
# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
pictures_filter = pictures[pictures['outfit.id'].isin(null_outfit_ids)]
pictures_filter

Empty DataFrame
Columns: [picture.id, outfit.id, displayOrder, file_name]
Index: []

In [27]:
# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
pictures = pictures[~pictures['outfit.id'].isin(null_outfit_ids)]

In [28]:
pictures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50193 entries, 0 to 50192
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    50193 non-null  object
 1   outfit.id     50193 non-null  object
 2   displayOrder  50193 non-null  int64
 3   file_name     50193 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.5+ MB

# Xử lý user_activity_triplets

In [29]:
with open('/kaggle/input/vibrent-clothes-rental-dataset/user_activity_triplets.csv', 'r') as f:
    lines = f.readlines()

# In các dòng đầu tiên để kiểm tra định dạng
for i in range(5):
    print(lines[i])

customer.id;outfit.id;rentalPeriod.start;rentalPeriod.end

03448;outfit.5c081909537b42239e465d2d615c705f;2023-03-26;2023-04-25

02924;outfit.c34969dd8b334064aa90bfb60c8ec308;2023-03-27;2023-04-26

02924;outfit.aef4cc93eebf40ca8820790deb7a8323;2023-01-27;2023-02-26

01128;outfit.3de5df48a14b4a9aba6d8e41d11e9351;2021-11-16;2021-12-15

In [30]:

transactions = pd.read_csv('/kaggle/input/vibrent-clothes-rental-dataset/user_activity_triplets.csv' , sep=';', on_bad_lines='skip')

In [31]:
transactions['rentalPeriod.start'] = pd.to_datetime(transactions['rentalPeriod.start'])
transactions['rentalPeriod.end'] = pd.to_datetime(transactions['rentalPeriod.end'])

In [32]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64419 entries, 0 to 64418
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer.id         64419 non-null  int64
 1   outfit.id           64419 non-null  object
 2   rentalPeriod.start  64419 non-null  datetime64[ns]
 3   rentalPeriod.end    64419 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 2.0+ MB

In [33]:
transactions.head()

,customer.id,outfit.id,rentalPeriod.start,rentalPeriod.end
0,3448,outfit.5c081909537b42239e465d2d615c705f,2023-03-26,2023-04-25
1,2924,outfit.c34969dd8b334064aa90bfb60c8ec308,2023-03-27,2023-04-26
2,2924,outfit.aef4cc93eebf40ca8820790deb7a8323,2023-01-27,2023-02-26
3,1128,outfit.3de5df48a14b4a9aba6d8e41d11e9351,2021-11-16,2021-12-15
4,1128,outfit.0eaa358af14e469894062591bd42f38b,2021-10-11,2021-11-11

In [34]:
null_outfit_ids

10624    outfit.5faafa92b722481ab1414e07380fa463
15555    outfit.01b2284d2ea24bfda29e1edc6f2fc0f9
Name: id, dtype: object

In [35]:
# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
transactions_filter = transactions[transactions['outfit.id'].isin(null_outfit_ids)]
transactions_filter

Empty DataFrame
Columns: [customer.id, outfit.id, rentalPeriod.start, rentalPeriod.end]
Index: []

In [36]:

# Bước 2: Loại bỏ các giao dịch liên quan đến các outfit.id đó
transactions_cleaned = transactions[~transactions['outfit.id'].isin(null_outfit_ids)]

In [37]:
transactions_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64419 entries, 0 to 64418
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer.id         64419 non-null  int64
 1   outfit.id           64419 non-null  object
 2   rentalPeriod.start  64419 non-null  datetime64[ns]
 3   rentalPeriod.end    64419 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 2.0+ MB

# Preprocessing

In [38]:
outfits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15647 entries, 0 to 15646
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              15647 non-null  object
 1   name            15647 non-null  object
 2   description     15647 non-null  object
 3   group           15625 non-null  object
 4   owner           15647 non-null  object
 5   timeCreated     15647 non-null  object
 6   retailPrice     14489 non-null  float64
 7   pricePerWeek    15647 non-null  float64
 8   pricePerMonth   15647 non-null  float64
 9   outfit_tags     15647 non-null  object
 10  tag_categories  15647 non-null  object
dtypes: float64(3), object(8)
memory usage: 1.3+ MB

In [39]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = outfits['id'].nunique()
print(f"Số phần tử không trùng lặpe: {unique_count}")

Số phần tử không trùng lặpe: 15647

In [40]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64419 entries, 0 to 64418
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer.id         64419 non-null  int64
 1   outfit.id           64419 non-null  object
 2   rentalPeriod.start  64419 non-null  datetime64[ns]
 3   rentalPeriod.end    64419 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 2.0+ MB

In [41]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = transactions['outfit.id'].nunique()
print(f"Số phần tử không trùng lặp: {unique_count}")

Số phần tử không trùng lặp: 10986

In [42]:
pictures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50193 entries, 0 to 50192
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    50193 non-null  object
 1   outfit.id     50193 non-null  object
 2   displayOrder  50193 non-null  int64
 3   file_name     50193 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.5+ MB

In [43]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = pictures['outfit.id'].nunique()
print(f"Số phần tử không trùng lặp: {unique_count}")

Số phần tử không trùng lặp: 15157

In [44]:
# Lấy danh sách các outfit.id từ outfits và transactions
outfit_ids = set(outfits['id'])  # Cột 'id' từ outfits
transaction_outfit_ids = set(transactions['outfit.id'])  # Cột 'outfit.id' từ transactions

# Tìm các id có trong transactions nhưng không có trong outfits
foreign_ids = transaction_outfit_ids - outfit_ids

# Kết quả
if foreign_ids:
    print("Các outfit.id ngoại lai (có trong transactions nhưng không có trong outfits):")
    print(foreign_ids)
else:
    print("Không có outfit.id ngoại lai.")

Không có outfit.id ngoại lai.

In [45]:
# Lấy danh sách các outfit.id từ outfits và transactions
pictures_ids = set(pictures['outfit.id'])  # Cột 'id' từ outfits
transaction_outfit_ids = set(transactions['outfit.id'])  # Cột 'outfit.id' từ transactions

# Tìm các id có trong transactions nhưng không có trong outfits
foreign_ids = transaction_outfit_ids - pictures_ids

# Kết quả
if foreign_ids:
    print("Các outfit.id (trong pictures ) ngoại lai (có trong transactions nhưng không có trong outfits):")
    print(foreign_ids)
else:
    print("Không có outfit.id (trong pictures ) ngoại lai.")

Các outfit.id (trong pictures ) ngoại lai (có trong transactions nhưng không có trong outfits):
{'outfit.95a1fba81c574a949ad15d8f18d5027e', 'outfit.53d2ed6b352a419e816708ea2b866bc9', 'outfit.b10df378b77f4ed8acc9c4442b17f924', 'outfit.b41ded69e1bc4182bb558994a9be55fa', 'outfit.acdb17c12e86b6b3', 'outfit.b0a0b74e3e374f95b7b7b41c63b1b5c7'}

In [46]:
transactions = transactions[transactions['outfit.id'].isin(pictures['outfit.id'])]

In [47]:
# Kiểm tra các id có trong transactions nhưng không có trong outfits
foreign_ids_df = transactions[~transactions['outfit.id'].isin(outfits['id'])]

# Kết quả
if not foreign_ids_df.empty:
    print("Các giao dịch có outfit.id không tồn tại trong outfits:")
    print(foreign_ids_df)
else:
    print("Tất cả outfit.id trong transactions đều có trong outfits.")

Tất cả outfit.id trong transactions đều có trong outfits.

In [48]:
# Kiểm tra các id có trong transactions nhưng không có trong pictures
foreign_ids_df = transactions[~transactions['outfit.id'].isin(pictures['outfit.id'])]

# Kết quả
if not foreign_ids_df.empty:
    print("Các giao dịch có outfit.id không tồn tại trong pictures:")
    print(foreign_ids_df)
else:
    print("Tất cả outfit.id trong transactions đều có trong pictures.")

Tất cả outfit.id trong transactions đều có trong pictures.

In [49]:
import time

# Đổi tên cột
data_collect = transactions.rename(columns={
    "outfit.id": "item_id_original",
    "customer.id": "user_id_original",
    "rentalPeriod.start": "time"
})

# Chuyển cột "time" thành UNIX Timestamp (Epoch Time)
data_collect["time"] = pd.to_datetime(data_collect["time"])
data_collect["time"] = data_collect["time"].apply(lambda x: int(time.mktime(x.timetuple())))


data_collect = data_collect[['user_id_original', 'item_id_original' , 'time']]

# Lưu DataFrame đã xử lý thành file CSV mới
output_path = "dataset_VCR.csv"
data_collect.to_csv(output_path, index=False)

# Hiển thị dữ liệu đã xử lý
data_collect.head()

   user_id_original                         item_id_original        time
0              3448  outfit.5c081909537b42239e465d2d615c705f  1679788800
1              2924  outfit.c34969dd8b334064aa90bfb60c8ec308  1679875200
2              2924  outfit.aef4cc93eebf40ca8820790deb7a8323  1674777600
3              1128  outfit.3de5df48a14b4a9aba6d8e41d11e9351  1637020800
4              1128  outfit.0eaa358af14e469894062591bd42f38b  1633910400

In [50]:
data_collect.shape

(64413, 3)

In [51]:
data_collect["user_id_original"].nunique()

2293

In [52]:
data_collect["item_id_original"].nunique()

10980

# Xử lý default df

In [53]:
# Đọc file CSV
df = pd.read_csv("/kaggle/working/dataset_VCR.csv")

# Lấy 3 cột chính
df

       user_id_original                         item_id_original        time
0                  3448  outfit.5c081909537b42239e465d2d615c705f  1679788800
1                  2924  outfit.c34969dd8b334064aa90bfb60c8ec308  1679875200
2                  2924  outfit.aef4cc93eebf40ca8820790deb7a8323  1674777600
3                  1128  outfit.3de5df48a14b4a9aba6d8e41d11e9351  1637020800
4                  1128  outfit.0eaa358af14e469894062591bd42f38b  1633910400
...                 ...                                      ...         ...
64408              7376  outfit.5bedabce07614c608b03fbb369d9abe7  1626652800
64409              5837                  outfit.bb35c791b2bfa191  1620000000
64410              5837                  outfit.ad6f853b5c31b6f5  1620000000
64411              1767  outfit.73393583c562454cbf1c00ce3cac0862  1703721600
64412              3448  outfit.a452840fe7e74c25962d1718f346c4b5  1658793600

[64413 rows x 3 columns]

In [54]:
df.shape

(64413, 3)

In [55]:
df['user_id_original'].value_counts()

user_id_original
3854    356
6482    348
6425    340
2567    328
617     328
       ...
1572      1
3395      1
6750      1
1955      1
1155      1
Name: count, Length: 2293, dtype: int64

In [56]:
df['item_id_original'].value_counts()

item_id_original
outfit.925c69db26f6bbae                    38
outfit.aa76777d3b9d4073a342e2093e4ea1e2    34
outfit.a9f2bcb6885fe60a                    32
outfit.9e28084ee8e94a1d8afe4abe643fa8d5    32
outfit.95a9732c69cb1e4c                    31
                                           ..
outfit.c7f52c21ccfb48ef87e304a98182d2d3     1
outfit.b71028a6c2b44ff7806086aa3d1a7ebe     1
outfit.4299225cd0214ba693bb1df3a5640d3f     1
outfit.20edc86dd20b42c0beda4c6ad90f5c3a     1
outfit.092ee39646f34dafac13607ee3c17215     1
Name: count, Length: 10980, dtype: int64

In [57]:


def process_data(df, random_percent=0.1, n_core=10, random_state=42):
    """
    Xử lý dataframe theo quy trình
    1. Lấy random k% số phần tử và lưu lại 
       - random_percent: phần trăm dữ liệu muốn lấy (0-1)
       - random_state: tái tạo kết quả
    2. Áp dụng n-core
       - n_core: số lượng tương tác tối thiểu
    3. Mapping ID cho User và Item
    4. Chia thành train/val/test
    
    """
    
    # 1. Lấy random k% số phần tử
    np.random.seed(random_state)
    n_samples = int(len(df) * random_percent)
    sampled_df = df.sample(n=n_samples, random_state=random_state)
    
    # Lưu file csv với k% phần tử
    # sampled_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}.csv', index=False)
    
    # 2. Áp dụng n-core
    # Đếm số lượng tương tác của mỗi user và item
    user_counts = sampled_df['user_id_original'].value_counts()
    # item_counts = sampled_df['item_id_original'].value_counts()
    
    # Lọc các user và item có ít nhất n tương tác
    valid_users = user_counts[user_counts >= n_core].index
    # valid_items = item_counts[item_counts >= n_core].index
    
    # filtered_df = sampled_df[
    #     sampled_df['user_id_original'].isin(valid_users) & 
    #     sampled_df['item_id_original'].isin(valid_items)
    # ]
    
    # Giữ lại dữ liệu của các user hợp lệ
    filtered_df = sampled_df[sampled_df['user_id_original'].isin(valid_users)]
    
    # 3. Mapping ID
    # Tạo mapping cho user
    unique_users = filtered_df['user_id_original'].unique()
    user_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_users , start=0)}
    
    # Tạo mapping cho item
    unique_items = filtered_df['item_id_original'].unique()
    item_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_items , start=0)}
    
    # Áp dụng mapping
    mapped_df = filtered_df.copy()
    mapped_df['user_id'] = mapped_df['user_id_original'].map(user_id_map)
    mapped_df['item_id'] = mapped_df['item_id_original'].map(item_id_map)

    print(mapped_df.head())
    # Lưu file csv sau mapping
    mapped_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}.csv', index=False)
    
    # # 4. Chia thành train/val/test
    # # Sắp xếp theo thời gian
    # mapped_df = mapped_df.sort_values('time')
    
    # # Chia theo tỷ lệ 70/15/15
    # train_df, temp_df = train_test_split(mapped_df, test_size=0.3, shuffle=False)
    # val_df, test_df = train_test_split(temp_df, test_size=0.5, shuffle=False)
    
    # Lưu các file
    # train_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}_train.csv', index=False)
    # val_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}_val.csv', index=False)
    # test_df.to_csv(f'dataset_VCR_{random_percent}_{random_state}_{n_core}_test.csv', index=False)
    
    # return train_df, val_df, test_df, user_id_map, item_id_map

# Sử dụng hàm
process_data(
    df, 
    random_percent=0.5,  # Lấy 20% dữ liệu
    n_core=10,           # Loại bỏ user/item có ít hơn 5 tương tác
    random_state=42     # Seed để tái tạo kết quả
)

# In thông tin về kết quả
# print(f"Số lượng users sau khi mapping: {len(user_mapping)}")
# print(f"Số lượng items sau khi mapping: {len(item_mapping)}")
# print("\nKích thước các tập dữ liệu:")
# print(f"Train: {len(train)} rows")
# print(f"Validation: {len(val)} rows")
# print(f"Test: {len(test)} rows")

       user_id_original                         item_id_original        time  \
17808              4960  outfit.b3fa81fe8aa241018fe08ca7eeddba28  1683590400
17992              1625  outfit.be3bd18f74b9420b991a871b4790de26  1704240000
47089              1557  outfit.557da3a4e43b4aa18835708e7320f359  1638144000
16521              3605  outfit.b3683ce7eccb4054adbcd73bf6f02d44  1702598400
28836               849  outfit.4173c7cc17484404a9724ff7465cbef2  1708387200

       user_id  item_id
17808        0        0
17992        1        1
47089        2        2
16521        3        3
28836        4        4

In [58]:


# def process_data(df, n_core=10, random_state=42):
#     """
#     Xử lý dataframe theo quy trình
#     1. Áp dụng n-core
#        - n_core: số lượng tương tác tối thiểu
#     2. Mapping ID cho User và Item
#     3. Chia thành train/val/test
#     """
    
#     # 1. Áp dụng n-core
#     # Đếm số lượng tương tác của mỗi user
#     user_counts = df['user_id_original'].value_counts()
    
#     # Lọc các user có ít nhất n tương tác
#     valid_users = user_counts[user_counts >= n_core].index
    
#     # Giữ lại dữ liệu của các user hợp lệ
#     filtered_df = df[df['user_id_original'].isin(valid_users)]
    
#     # 2. Mapping ID
#     # Tạo mapping cho user
#     unique_users = filtered_df['user_id_original'].unique()
#     user_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_users, start=0)}
    
#     # Tạo mapping cho item
#     unique_items = filtered_df['item_id_original'].unique()
#     item_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_items, start=0)}
    
#     # Áp dụng mapping
#     mapped_df = filtered_df.copy()
#     mapped_df['user_id'] = mapped_df['user_id_original'].map(user_id_map)
#     mapped_df['item_id'] = mapped_df['item_id_original'].map(item_id_map)

#     print(mapped_df.head())

#     # Sắp xếp theo thời gian
#     mapped_df = mapped_df.sort_values('time')
    
#     # Lưu file csv sau mapping
#     mapped_df.to_csv(f'dataset_VCR_full_{n_core}.csv', index=False)
    
#     # # 3. Chia thành train/val/test
#     # # Sắp xếp theo thời gian
#     # mapped_df = mapped_df.sort_values('time')
    
#     # # Chia theo tỷ lệ 70/15/15
#     # train_df, temp_df = train_test_split(mapped_df, test_size=0.3, shuffle=False)
#     # val_df, test_df = train_test_split(temp_df, test_size=0.5, shuffle=False)
    
#     # # Lưu các file
#     # train_df.to_csv(f'dataset_VCR_full_{n_core}_train.csv', index=False)
#     # val_df.to_csv(f'dataset_VCR_full_{n_core}_val.csv', index=False)
#     # test_df.to_csv(f'dataset_VCR_full_{n_core}_test.csv', index=False)
    
#     # return train_df, val_df, test_df, user_id_map, item_id_map

# # Sử dụng hàm
# process_data(
#     df, 
#     n_core=10,           # Loại bỏ user/item có ít hơn 10 tương tác
#     random_state=42     # Seed để tái tạo kết quả
# )

# # # In thông tin về kết quả
# # print(f"Số lượng users sau khi mapping: {len(user_mapping)}")
# # print(f"Số lượng items sau khi mapping: {len(item_mapping)}")
# # print("\nKích thước các tập dữ liệu:")
# # print(f"Train: {len(train)} rows")
# # print(f"Validation: {len(val)} rows")
# # print(f"Test: {len(test)} rows")

# Xử lý sample df

In [59]:
# Đọc file CSV
df = pd.read_csv("/kaggle/working/dataset_VCR_0.5_42_10.csv")
# df = pd.read_csv("/kaggle/working/dataset_VCR_full_10.csv")

In [60]:
df.head(10)

,user_id_original,item_id_original,time,user_id,item_id
0,4960,outfit.b3fa81fe8aa241018fe08ca7eeddba28,1683590400,0,0
1,1625,outfit.be3bd18f74b9420b991a871b4790de26,1704240000,1,1
2,1557,outfit.557da3a4e43b4aa18835708e7320f359,1638144000,2,2
3,3605,outfit.b3683ce7eccb4054adbcd73bf6f02d44,1702598400,3,3
4,849,outfit.4173c7cc17484404a9724ff7465cbef2,1708387200,4,4
5,6011,outfit.63fc53c3d8784dd39553a33d54ff4921,1696118400,5,5
6,2703,outfit.8069d486b105482394bb94abdc6d10dc,1676505600,6,6
7,3245,outfit.1b3e2ad0256b4c839afe49dcfcd50b40,1667001600,7,7
8,7364,outfit.57ea8cdb48974c93a9e5b65c5711750c,1698796800,8,8
9,96,outfit.d39ea6485a024bb2a6529ce15d2739d7,1707782400,9,9

In [61]:
# df = df[['user_id' , 'item_id' , 'time']]

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27522 entries, 0 to 27521
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  27522 non-null  int64
 1   item_id_original  27522 non-null  object
 2   time              27522 non-null  int64
 3   user_id           27522 non-null  int64
 4   item_id           27522 non-null  int64
dtypes: int64(4), object(1)
memory usage: 1.1+ MB

In [63]:
# Sắp xếp dữ liệu theo `user_id` và `time`
df = df.sort_values(by=["user_id", "time"]).reset_index(drop=True)

In [64]:
df.head(10)

,user_id_original,item_id_original,time,user_id,item_id
0,4960,outfit.395fb0e3bb64425787592badb5a34346,1628726400,0,1537
1,4960,outfit.5a117a61fd6e4a2b903d63e961758be7,1631232000,0,1018
2,4960,outfit.20ae7885d88441348ab7a255bcc2173e,1631232000,0,1698
3,4960,outfit.2405f2beaf9241f590e020d163f6fb66,1633651200,0,548
4,4960,outfit.253fb654ace04cbb9280e54d54b62ed8,1633651200,0,4554
5,4960,outfit.f4d096191c4a47d081617a472280443d,1636329600,0,1908
6,4960,outfit.e1bf11e29fe64246b39043783fefa3a4,1636329600,0,3662
7,4960,outfit.801f1b35886e42f6907ec4709420c7e3,1636329600,0,1607
8,4960,outfit.7e8bee4b2c5e4caea0cdcb681b676bd0,1638835200,0,871
9,4960,outfit.652d01e9a0cd459da602c2fd70f558a5,1638835200,0,315

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27522 entries, 0 to 27521
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  27522 non-null  int64
 1   item_id_original  27522 non-null  object
 2   time              27522 non-null  int64
 3   user_id           27522 non-null  int64
 4   item_id           27522 non-null  int64
dtypes: int64(4), object(1)
memory usage: 1.1+ MB

# Tạo user list

In [66]:
user_df = df[['user_id_original', 'user_id']]

In [67]:
user_df = user_df.drop_duplicates()

In [68]:

# Sắp xếp theo giá trị user_id tăng dần
user_list_df = user_df.sort_values(by='user_id')

# Ghi vào file user_list.txt, không bao gồm dòng tên cột
user_list_df.to_csv('user_list.txt', sep=' ', index=False, header=False)

print("File user_list.txt đã được tạo.")

File user_list.txt đã được tạo.

In [69]:
user_list_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 909 entries, 0 to 27512
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  909 non-null    int64
 1   user_id           909 non-null    int64
dtypes: int64(2)
memory usage: 21.3 KB

# Tạo item list

In [70]:
item_df = df[['item_id_original', 'item_id']]

In [71]:
item_df = item_df.drop_duplicates()

In [72]:
# Sắp xếp theo giá trị user_id tăng dần
item_list_df = item_df.sort_values(by='item_id')

# Ghi vào file user_list.txt, không bao gồm dòng tên cột
item_list_df.to_csv('item_list.txt', sep=' ', index=False, header=False)

print("File item_list.txt đã được tạo.")

File item_list.txt đã được tạo.

In [73]:
item_list_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8944 entries, 70 to 16476
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  8944 non-null   object
 1   item_id           8944 non-null   int64
dtypes: int64(1), object(1)
memory usage: 209.6+ KB

In [74]:
item_list_df.head()

                            item_id_original  item_id
70   outfit.b3fa81fe8aa241018fe08ca7eeddba28        0
119  outfit.be3bd18f74b9420b991a871b4790de26        1
127  outfit.557da3a4e43b4aa18835708e7320f359        2
226  outfit.b3683ce7eccb4054adbcd73bf6f02d44        3
263  outfit.4173c7cc17484404a9724ff7465cbef2        4

# Tạo interactions matrix

In [75]:
# Tạo dictionary lưu quan hệ user và danh sách item
user_item_interactions = df.groupby('user_id')['item_id'].apply(lambda x: sorted(x)).to_dict()

# Ghi file intersection_user.txt
with open('intersection_user.txt', 'w') as f:
    for user_id in sorted(user_item_interactions.keys()):  # Sắp xếp user_id theo thứ tự tăng dần
        # Lấy danh sách item_id đã được sắp xếp và chuyển thành chuỗi cách nhau bởi khoảng trắng
        item_list_str = ' '.join(map(str, user_item_interactions[user_id]))
        # Ghi user_id và danh sách item vào file
        f.write(f"{user_id} {item_list_str}\n")

print("File intersection_user.txt đã được tạo.")

File intersection_user.txt đã được tạo.

In [76]:
# # Tạo dictionary lưu quan hệ item và danh sách user
# item_user_interactions = df.groupby('item_id')['user_id'].apply(lambda x: sorted(x)).to_dict()

# # Ghi file intersection_item.txt
# with open('intersection_item.txt', 'w') as f:
#     for item_id in sorted(item_user_interactions.keys()):  # Sắp xếp item_id theo thứ tự tăng dần
#         # Lấy danh sách user_id và chuyển thành chuỗi cách nhau bởi khoảng trắng
#         user_list_str = ' '.join(map(str, item_user_interactions[item_id]))  # Sắp xếp user_id
#         # Ghi item_id và danh sách user vào file
#         f.write(f"{item_id} {user_list_str}\n")

## **=> Kiểm tra lại dữ liệu**

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27522 entries, 0 to 27521
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  27522 non-null  int64
 1   item_id_original  27522 non-null  object
 2   time              27522 non-null  int64
 3   user_id           27522 non-null  int64
 4   item_id           27522 non-null  int64
dtypes: int64(4), object(1)
memory usage: 1.1+ MB

In [78]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = user_df['user_id_original'].nunique()
print(f"Số phần tử không trùng lặp trong cột user_id_original: {unique_count}")

Số phần tử không trùng lặp trong cột user_id_original: 909

In [79]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = item_df['item_id_original'].nunique()
print(f"Số phần tử không trùng lặp trong cột item_id_original: {unique_count}")

Số phần tử không trùng lặp trong cột item_id_original: 8944

In [80]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = item_df['item_id'].max()
print(f"phần tử lớn nhất trong cột item_id: {unique_count}")

phần tử lớn nhất trong cột item_id: 8943

In [81]:
# Số phần tử không trùng lặp trong cột 'column_name'
unique_count = user_df['user_id'].max()
print(f"phần tử lớn nhất trong cột user_id: {unique_count}")

phần tử lớn nhất trong cột user_id: 908

# Chia train / test

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27522 entries, 0 to 27521
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id_original  27522 non-null  int64
 1   item_id_original  27522 non-null  object
 2   time              27522 non-null  int64
 3   user_id           27522 non-null  int64
 4   item_id           27522 non-null  int64
dtypes: int64(4), object(1)
memory usage: 1.1+ MB

In [83]:
df.tail(10)

,user_id_original,item_id_original,time,user_id,item_id
27512,550,outfit.39e26260f13d466b946601bafd691d36,1599696000,908,927
27513,550,outfit.9a5eec4507c14f97b35b6dd8735dd427,1607558400,908,1162
27514,550,outfit.01601322d21a422fbc2db49c7866e264,1607558400,908,1407
27515,550,outfit.871f15bc73153001,1607558400,908,7258
27516,550,outfit.59a743b5952a415daa0d455a49536872,1671494400,908,6866
27517,550,outfit.3da003afd88d48cc92c189a1d980e358,1671494400,908,8554
27518,550,outfit.27e23087772c4641a0513714504be082,1671494400,908,4975
27519,550,outfit.b3683ce7eccb4054adbcd73bf6f02d44,1674172800,908,3
27520,550,outfit.fc049a65942344bda48d3e5c798a485c,1700438400,908,6167
27521,550,outfit.6a4856dd876644e1aa6a36f8d94cdd39,1703030400,908,783

In [84]:

# Thêm cột `rank` cho từng `user_id`
df["rank"] = df.groupby("user_id").cumcount() + 1

In [85]:
# Tính toán số lượng tương tác và ngưỡng phân chia
user_counts = df.groupby("user_id")["rank"].max().reset_index()
user_counts.rename(columns={"rank": "total_interactions"}, inplace=True)
user_counts["train_threshold"] = (user_counts["total_interactions"] * 0.8).astype(int)

In [86]:
# Gộp ngưỡng với DataFrame ban đầu
df = df.merge(user_counts, on="user_id", how="inner")

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27522 entries, 0 to 27521
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id_original    27522 non-null  int64
 1   item_id_original    27522 non-null  object
 2   time                27522 non-null  int64
 3   user_id             27522 non-null  int64
 4   item_id             27522 non-null  int64
 5   rank                27522 non-null  int64
 6   total_interactions  27522 non-null  int64
 7   train_threshold     27522 non-null  int64
dtypes: int64(7), object(1)
memory usage: 1.7+ MB

In [88]:
df.head(10)

,user_id_original,item_id_original,time,user_id,item_id,rank,total_interactions,train_threshold
0,4960,outfit.395fb0e3bb64425787592badb5a34346,1628726400,0,1537,1,101,80
1,4960,outfit.5a117a61fd6e4a2b903d63e961758be7,1631232000,0,1018,2,101,80
2,4960,outfit.20ae7885d88441348ab7a255bcc2173e,1631232000,0,1698,3,101,80
3,4960,outfit.2405f2beaf9241f590e020d163f6fb66,1633651200,0,548,4,101,80
4,4960,outfit.253fb654ace04cbb9280e54d54b62ed8,1633651200,0,4554,5,101,80
5,4960,outfit.f4d096191c4a47d081617a472280443d,1636329600,0,1908,6,101,80
6,4960,outfit.e1bf11e29fe64246b39043783fefa3a4,1636329600,0,3662,7,101,80
7,4960,outfit.801f1b35886e42f6907ec4709420c7e3,1636329600,0,1607,8,101,80
8,4960,outfit.7e8bee4b2c5e4caea0cdcb681b676bd0,1638835200,0,871,9,101,80
9,4960,outfit.652d01e9a0cd459da602c2fd70f558a5,1638835200,0,315,10,101,80

In [89]:
df.tail(10)

,user_id_original,item_id_original,time,user_id,item_id,rank,total_interactions,train_threshold
27512,550,outfit.39e26260f13d466b946601bafd691d36,1599696000,908,927,1,10,8
27513,550,outfit.9a5eec4507c14f97b35b6dd8735dd427,1607558400,908,1162,2,10,8
27514,550,outfit.01601322d21a422fbc2db49c7866e264,1607558400,908,1407,3,10,8
27515,550,outfit.871f15bc73153001,1607558400,908,7258,4,10,8
27516,550,outfit.59a743b5952a415daa0d455a49536872,1671494400,908,6866,5,10,8
27517,550,outfit.3da003afd88d48cc92c189a1d980e358,1671494400,908,8554,6,10,8
27518,550,outfit.27e23087772c4641a0513714504be082,1671494400,908,4975,7,10,8
27519,550,outfit.b3683ce7eccb4054adbcd73bf6f02d44,1674172800,908,3,8,10,8
27520,550,outfit.fc049a65942344bda48d3e5c798a485c,1700438400,908,6167,9,10,8
27521,550,outfit.6a4856dd876644e1aa6a36f8d94cdd39,1703030400,908,783,10,10,8

In [90]:
# Tạo ma trận train và test từ DataFrame
train_interactions = {}
test_interactions = {}

for user_id, user_df in df.groupby('user_id'):
    # Lấy ngưỡng train_threshold cho user hiện tại
    train_threshold = user_df['train_threshold'].iloc[0]

    # Phân chia item_id thành train và test
    train_items = user_df[user_df['rank'] <= train_threshold]['item_id'].tolist()
    test_items = user_df[user_df['rank'] > train_threshold]['item_id'].tolist()

    # Lưu vào dictionary
    train_interactions[user_id] = train_items
    test_interactions[user_id] = test_items

In [91]:
len(train_interactions)

909

In [92]:
len(train_interactions[0])

80

In [93]:
len(test_interactions)

909

In [94]:
len(test_interactions[0])

21

In [95]:
# Ghi file train.txt
with open('train.txt', 'w') as f:
    for user_id, item_list in train_interactions.items():
        item_list_str = ' '.join(map(str, item_list))  # Chuyển danh sách item_id thành chuỗi
        f.write(f"{user_id} {item_list_str}\n")  # Ghi user_id và item_id cách nhau bởi khoảng trắng

# Ghi file test.txt
with open('test.txt', 'w') as f:
    for user_id, item_list in test_interactions.items():
        item_list_str = ' '.join(map(str, item_list))  # Chuyển danh sách item_id thành chuỗi
        f.write(f"{user_id} {item_list_str}\n")  # Ghi user_id và item_id cách nhau bởi khoảng trắng

print("Files train.txt và test.txt đã được tạo.")

Files train.txt và test.txt đã được tạo.

In [96]:
# # Chia dữ liệu
# train_df = df[df["rank"] <= df["train_threshold"]]
# test_df = df[df["rank"] > df["train_threshold"]]

In [97]:
# # Lưu tập train và test thành file
# train_df[["user_id", "item_id"]].to_csv("train.txt", header=False, index=False, sep=" ")
# test_df[["user_id", "item_id"]].to_csv("test.txt", header=False, index=False, sep=" ")

# print("Train and Test data saved to train.txt and test.txt")

=> đang sai chia lại theo hướng , mỗi người dùng , đều có trong train và test (đã fix)

In [98]:
# import pandas as pd
# from sklearn.model_selection import train_test_split

# # Đọc file vào danh sách
# with open("/kaggle/working/intersection.txt", "r") as file:
#     lines = file.readlines()

# # Chia dữ liệu bằng train_test_split
# train, test = train_test_split(lines, test_size=0.2, random_state=42)

# # Lưu kết quả lại thành file
# with open("train.txt", "w") as train_file:
#     train_file.writelines(train)

# with open("test.txt", "w") as test_file:
#     test_file.writelines(test)

# print("Train and Test data saved to train.txt and test.txt")

In [99]:
# len(lines)

In [100]:
# len(train)

In [101]:
# len(test)

# Tạo items_features

## Xử lý feature1 và 2

In [102]:
item_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8944 entries, 0 to 27517
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  8944 non-null   object
 1   item_id           8944 non-null   int64
dtypes: int64(1), object(1)
memory usage: 209.6+ KB

In [103]:
item_df.reset_index(drop=True, inplace=True)  # Đặt lại chỉ mục

In [104]:
item_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  8944 non-null   object
 1   item_id           8944 non-null   int64
dtypes: int64(1), object(1)
memory usage: 139.9+ KB

In [105]:
item_df.head()

                          item_id_original  item_id
0  outfit.395fb0e3bb64425787592badb5a34346     1537
1  outfit.5a117a61fd6e4a2b903d63e961758be7     1018
2  outfit.20ae7885d88441348ab7a255bcc2173e     1698
3  outfit.2405f2beaf9241f590e020d163f6fb66      548
4  outfit.253fb654ace04cbb9280e54d54b62ed8     4554

In [106]:
outfits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15647 entries, 0 to 15646
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              15647 non-null  object
 1   name            15647 non-null  object
 2   description     15647 non-null  object
 3   group           15625 non-null  object
 4   owner           15647 non-null  object
 5   timeCreated     15647 non-null  object
 6   retailPrice     14489 non-null  float64
 7   pricePerWeek    15647 non-null  float64
 8   pricePerMonth   15647 non-null  float64
 9   outfit_tags     15647 non-null  object
 10  tag_categories  15647 non-null  object
dtypes: float64(3), object(8)
memory usage: 1.3+ MB

In [107]:
outfits.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories
0,outfit.fffdaa715c3646f8b1c0f04d549ff07e,Out of stock - Asymmetric Frilled Dress,"This fun, short dress features and asymmetric ...",group.50a586c78eb7626e294ba3bd07d12c79,o_00053,2017-12-30 11:28:01.000,4000.0,600.0,1200.0,"[Synthetic, Statement, Dresses, Metallic, Mini...","[Material, Occasion, Category, Details, Length..."
1,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,"[ILAG, Tops, Spring, Summer, M, Pattern, Yello...","[Brand, Category, Seasons, Seasons, Size, Deta..."
2,outfit.fff175b13ceb453f9928625491412ede,Kaula Dress Black,Kaula from Rodebjer is a fitted dress made in ...,group.37c2b59d63d3a9c2d58e07f532f71f7f,o_00336,2023-06-05 09:17:59.004,3100.0,930.0,1860.0,"[Black, Mini, M, Everyday, Multi Season, Women...","[Color, Length, Size, Occasion, Seasons, Gende..."
3,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,"[XS, Multi Season, Stylein, Tops, Cotton, Mult...","[Size, Seasons, Brand, Category, Material, Col..."
4,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,"[Cotton, Black, Everyday, Knitwear, L, Winter,...","[Material, Color, Occasion, Category, Size, Se..."

In [108]:
item_df['item_id_original'].nunique()

8944

In [109]:
outfits['id'].nunique()

15647

In [110]:
merged_df = pd.merge(outfits, item_df, left_on='id', right_on='item_id_original', how='inner')

In [111]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                8944 non-null   object
 1   name              8944 non-null   object
 2   description       8944 non-null   object
 3   group             8944 non-null   object
 4   owner             8944 non-null   object
 5   timeCreated       8944 non-null   object
 6   retailPrice       8939 non-null   float64
 7   pricePerWeek      8944 non-null   float64
 8   pricePerMonth     8944 non-null   float64
 9   outfit_tags       8944 non-null   object
 10  tag_categories    8944 non-null   object
 11  item_id_original  8944 non-null   object
 12  item_id           8944 non-null   int64
dtypes: float64(3), int64(1), object(9)
memory usage: 908.5+ KB

In [112]:
merged_df['id'].nunique()

8944

In [113]:
merged_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id
0,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,"[ILAG, Tops, Spring, Summer, M, Pattern, Yello...","[Brand, Category, Seasons, Seasons, Size, Deta...",outfit.fffa1b9a3db6415d806f3c48f8ab58d9,2846
1,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,"[XS, Multi Season, Stylein, Tops, Cotton, Mult...","[Size, Seasons, Brand, Category, Material, Col...",outfit.ffef9d7c292a48b69076d2df2e32352f,2712
2,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,"[Cotton, Black, Everyday, Knitwear, L, Winter,...","[Material, Color, Occasion, Category, Size, Se...",outfit.ffeef842238f4dbdabc6c730a75aa2bd,6747
3,outfit.ffebad2c479045a78adecdcd8f07427d,Bumble Dress Black Burnout Maxi,The Bumble Maxi Dress from Høst & Vår is a ful...,group.10995bb4c49c8a25a48fed9dc025beac,o_00089,2023-01-05 09:12:43.847,1800.0,590.0,1180.0,"[Summer, Dressed-up, Women, S, Spring, Dresses...","[Seasons, Occasion, Gender, Size, Seasons, Cat...",outfit.ffebad2c479045a78adecdcd8f07427d,5871
4,outfit.ffe617f43d244ebc81228915cfcc6c8e,Platinum Blazer,Platinum Blazer is a classic and narrow suit j...,group.f2b0d1fde7052ef61a89b4ad3539b55c,o_00413,2022-04-01 12:25:15.312,2800.0,840.0,1680.0,"[Women, Business, Everyday, Black, Wool, Sprin...","[Gender, Occasion, Occasion, Color, Material, ...",outfit.ffe617f43d244ebc81228915cfcc6c8e,75

In [114]:
merged_df.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         [ILAG, Tops, Spring, Summer, M, Pattern, Yello...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
Name: 0, dtype: object

## Xử lý feature3 ( embedings đặc trưng hình ảnh )

In [115]:
pictures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50193 entries, 0 to 50192
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   picture.id    50193 non-null  object
 1   outfit.id     50193 non-null  object
 2   displayOrder  50193 non-null  int64
 3   file_name     50193 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.5+ MB

In [116]:
pictures.head()

,picture.id,outfit.id,displayOrder,file_name
0,picture.0000cdba64314d84a49ed1c266589cc0,outfit.794483397da8425a813301eecf9828c6,0,0000cdba64314d84a49ed1c266589cc0.jpg
1,picture.00058abb53434872ae9bb4270ae21f8e,outfit.98f32aaf08bc4ff09c44e6e11e9199bc,2,00058abb53434872ae9bb4270ae21f8e.jpg
2,picture.00063f52c36d43ada95da45f819b30b4,outfit.9fd1c42c3db543c5b6e53b0db1ee8c0f,3,00063f52c36d43ada95da45f819b30b4.jpg
3,picture.0008443461814f5c988f123718bbd20e,outfit.a7539783b6e94591bdf4e10339afc1d7,3,0008443461814f5c988f123718bbd20e.jpg
4,picture.000a5db3362049aebcc1eb2bf7bde95f,outfit.745fa2bc8156478bac6c0f7d46dadbda,1,000a5db3362049aebcc1eb2bf7bde95f.jpg

In [117]:
pictures['outfit.id'].nunique()

15157

In [118]:
print(pictures['outfit.id'].isna().sum())

0

In [119]:
import pandas as pd

# Giả định df là DataFrame của bạn
grouped_sorted_df = (
    pictures.sort_values(by=['outfit.id', 'displayOrder'])  # Sắp xếp theo outfit.id và displayOrder
      .groupby('outfit.id', as_index=False)
      .agg({
          'picture.id': lambda x: list(x),
          'file_name': lambda x: list(x),
          'displayOrder': lambda x: list(x)
      })
)

In [120]:
grouped_sorted_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15157 entries, 0 to 15156
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   outfit.id     15157 non-null  object
 1   picture.id    15157 non-null  object
 2   file_name     15157 non-null  object
 3   displayOrder  15157 non-null  object
dtypes: object(4)
memory usage: 473.8+ KB

In [121]:
grouped_sorted_df.head()

,outfit.id,picture.id,file_name,displayOrder
0,outfit.00004b4d01ca4ab0a70cf073ba74fefa,"[picture.a2b794c7ef83495a8997e7b0c318d65a, pic...","[a2b794c7ef83495a8997e7b0c318d65a.jpg, ba62226...","[1, 2]"
1,outfit.0013691ff35b440e9dcfe1748ec184c7,"[picture.9c821ecbecb14c959f35078010fb91f3, pic...","[9c821ecbecb14c959f35078010fb91f3.jpg, 4d000a0...","[1, 2, 3, 4]"
2,outfit.0014a5c89b244077a3d7cffd4549718e,"[picture.b9aa39eb40f5410fa4fe101236241b19, pic...","[b9aa39eb40f5410fa4fe101236241b19.jpg, d6c3531...","[1, 2, 3]"
3,outfit.0018701ce6b049ebadc314d16623caa8,"[picture.b944a50f20fd4c7f954213dc7c38a776, pic...","[b944a50f20fd4c7f954213dc7c38a776.jpg, e73da8b...","[1, 2, 3]"
4,outfit.001bf665330140cf854dcfb1cbff6b5f,"[picture.21a37e763d1842dca26e7d3276f284c5, pic...","[21a37e763d1842dca26e7d3276f284c5.jpg, 594f077...","[0, 0, 0, 0, 0, 0]"

In [122]:
grouped_sorted_df['outfit.id'].nunique()

15157

In [123]:
grouped_sorted_df.iloc[10000]

outfit.id                 outfit.a92f8950491a4ec893eeef1901ee726e
picture.id      [picture.48eb698319524837bbd8501affb40974, pic...
file_name       [48eb698319524837bbd8501affb40974.jpg, b63c912...
displayOrder                                         [1, 2, 3, 4]
Name: 10000, dtype: object

In [124]:
grouped_sorted_df.iloc[10000]['picture.id']

['picture.48eb698319524837bbd8501affb40974',
 'picture.b63c912ae98d4c2bb7fb07caed8bfaae',
 'picture.9ee12805fc80465f93ab838c9cef336d',
 'picture.e389392f09d743ed9105f6052e4728b7']

In [125]:
grouped_sorted_df.iloc[10000]['picture.id'][0]

'picture.48eb698319524837bbd8501affb40974'

In [126]:
print(merged_df.isna().sum())

id                  0
name                0
description         0
group               0
owner               0
timeCreated         0
retailPrice         5
pricePerWeek        0
pricePerMonth       0
outfit_tags         0
tag_categories      0
item_id_original    0
item_id             0
dtype: int64

In [127]:
print(grouped_sorted_df.isna().sum())

outfit.id       0
picture.id      0
file_name       0
displayOrder    0
dtype: int64

In [128]:
# Kiểm tra các giá trị trong 'id' của merged_df không tồn tại trong 'outfit.id' của grouped_sorted_df
non_matching_ids = merged_df[~merged_df['id'].isin(grouped_sorted_df['outfit.id'])]

# Hiển thị các giá trị không khớp
print(non_matching_ids[['id']])

Empty DataFrame
Columns: [id]
Index: []

In [129]:
import pandas as pd

# Giả định df_a và df_b đã được đọc vào
items_features_df = pd.merge(
    merged_df, grouped_sorted_df,
    left_on='item_id_original',     # Cột tham chiếu từ df_a
    right_on='outfit.id',  # Cột tham chiếu từ df_b
    how='inner'       # Merge theo cách "inner" để giữ lại các hàng khớp
)

In [130]:
items_features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                8944 non-null   object
 1   name              8944 non-null   object
 2   description       8944 non-null   object
 3   group             8944 non-null   object
 4   owner             8944 non-null   object
 5   timeCreated       8944 non-null   object
 6   retailPrice       8939 non-null   float64
 7   pricePerWeek      8944 non-null   float64
 8   pricePerMonth     8944 non-null   float64
 9   outfit_tags       8944 non-null   object
 10  tag_categories    8944 non-null   object
 11  item_id_original  8944 non-null   object
 12  item_id           8944 non-null   int64
 13  outfit.id         8944 non-null   object
 14  picture.id        8944 non-null   object
 15  file_name         8944 non-null   object
 16  displayOrder      8944 non-null   object
dtypes: float64(3), int64(1), object(13)
memory usage: 1.2+ MB

In [131]:
print(items_features_df.isna().sum())

id                  0
name                0
description         0
group               0
owner               0
timeCreated         0
retailPrice         5
pricePerWeek        0
pricePerMonth       0
outfit_tags         0
tag_categories      0
item_id_original    0
item_id             0
outfit.id           0
picture.id          0
file_name           0
displayOrder        0
dtype: int64

In [132]:
items_features_df['outfit.id'].nunique()

8944

In [133]:
items_features_df['id'].nunique()

8944

In [134]:
items_features_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id,outfit.id,picture.id,file_name,displayOrder
0,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,"[ILAG, Tops, Spring, Summer, M, Pattern, Yello...","[Brand, Category, Seasons, Seasons, Size, Deta...",outfit.fffa1b9a3db6415d806f3c48f8ab58d9,2846,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,"[picture.649ea4f38ffa47eb92556af7d3195ba4, pic...","[649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...","[1, 2, 3, 4, 5]"
1,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,"[XS, Multi Season, Stylein, Tops, Cotton, Mult...","[Size, Seasons, Brand, Category, Material, Col...",outfit.ffef9d7c292a48b69076d2df2e32352f,2712,outfit.ffef9d7c292a48b69076d2df2e32352f,"[picture.7d86226f09f040bd81ef18fd24cf4e04, pic...","[7d86226f09f040bd81ef18fd24cf4e04.jpg, e88231a...","[1, 2]"
2,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,"[Cotton, Black, Everyday, Knitwear, L, Winter,...","[Material, Color, Occasion, Category, Size, Se...",outfit.ffeef842238f4dbdabc6c730a75aa2bd,6747,outfit.ffeef842238f4dbdabc6c730a75aa2bd,"[picture.b9342b85e6a94a6988e37cdb4f3fd0bb, pic...","[b9342b85e6a94a6988e37cdb4f3fd0bb.jpg, 723499a...","[1, 2, 3]"
3,outfit.ffebad2c479045a78adecdcd8f07427d,Bumble Dress Black Burnout Maxi,The Bumble Maxi Dress from Høst & Vår is a ful...,group.10995bb4c49c8a25a48fed9dc025beac,o_00089,2023-01-05 09:12:43.847,1800.0,590.0,1180.0,"[Summer, Dressed-up, Women, S, Spring, Dresses...","[Seasons, Occasion, Gender, Size, Seasons, Cat...",outfit.ffebad2c479045a78adecdcd8f07427d,5871,outfit.ffebad2c479045a78adecdcd8f07427d,"[picture.4a6ba45b29df49949d311ef1709b07fe, pic...","[4a6ba45b29df49949d311ef1709b07fe.jpg, 7c9cb5d...","[1, 2]"
4,outfit.ffe617f43d244ebc81228915cfcc6c8e,Platinum Blazer,Platinum Blazer is a classic and narrow suit j...,group.f2b0d1fde7052ef61a89b4ad3539b55c,o_00413,2022-04-01 12:25:15.312,2800.0,840.0,1680.0,"[Women, Business, Everyday, Black, Wool, Sprin...","[Gender, Occasion, Occasion, Color, Material, ...",outfit.ffe617f43d244ebc81228915cfcc6c8e,75,outfit.ffe617f43d244ebc81228915cfcc6c8e,"[picture.ae0d6fbd73e0496dac7d657c97da7acd, pic...","[ae0d6fbd73e0496dac7d657c97da7acd.jpg, e3bc772...","[1, 2, 3]"

In [135]:
items_features_df.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         [ILAG, Tops, Spring, Summer, M, Pattern, Yello...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
Name: 0, dtype: object

In [136]:
# # Thực hiện merge với how='left'
# left_merged_df = pd.merge(
#     merged_df, grouped_sorted_df,
#     left_on='id',     # Cột tham chiếu từ df_a
#     right_on='outfit.id',  # Cột tham chiếu từ df_b
#     how='left'       # Merge theo cách "left" để giữ lại tất cả các hàng từ merged_df
# )

# # Lọc ra các hàng không khớp
# non_matching_rows = left_merged_df[left_merged_df['outfit.id'].isna()]

# # Hiển thị các hàng không khớp
# non_matching_rows.head()

In [137]:
# left_merged_df.info()

## Tạo image_list

In [138]:
image_list_df = items_features_df[['item_id_original' ,'item_id', 'file_name']]

In [139]:
image_list_df.head()

,item_id_original,item_id,file_name
0,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,2846,"[649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724..."
1,outfit.ffef9d7c292a48b69076d2df2e32352f,2712,"[7d86226f09f040bd81ef18fd24cf4e04.jpg, e88231a..."
2,outfit.ffeef842238f4dbdabc6c730a75aa2bd,6747,"[b9342b85e6a94a6988e37cdb4f3fd0bb.jpg, 723499a..."
3,outfit.ffebad2c479045a78adecdcd8f07427d,5871,"[4a6ba45b29df49949d311ef1709b07fe.jpg, 7c9cb5d..."
4,outfit.ffe617f43d244ebc81228915cfcc6c8e,75,"[ae0d6fbd73e0496dac7d657c97da7acd.jpg, e3bc772..."

In [140]:
image_list_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  8944 non-null   object
 1   item_id           8944 non-null   int64
 2   file_name         8944 non-null   object
dtypes: int64(1), object(2)
memory usage: 209.8+ KB

In [141]:
# Sắp xếp theo giá trị user_id tăng dần
image_list_df = image_list_df.sort_values(by='item_id')

image_list_df.reset_index(drop=True, inplace=True)  # Đặt lại chỉ mục

In [142]:
image_list_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id_original  8944 non-null   object
 1   item_id           8944 non-null   int64
 2   file_name         8944 non-null   object
dtypes: int64(1), object(2)
memory usage: 209.8+ KB

In [143]:
image_list_df.head()

,item_id_original,item_id,file_name
0,outfit.b3fa81fe8aa241018fe08ca7eeddba28,0,"[41e17240d3a446bc97224905cee017a0.jpg, 55dced0..."
1,outfit.be3bd18f74b9420b991a871b4790de26,1,"[1ff1010a0fe54cdb857dc729f3c10670.jpg, 5746396..."
2,outfit.557da3a4e43b4aa18835708e7320f359,2,"[8022c15822b741e1b3e7ec38d2c6e7a8.jpg, fedf158..."
3,outfit.b3683ce7eccb4054adbcd73bf6f02d44,3,[9c9b6d38d2084b78a2e99d3f5348957b.jpg]
4,outfit.4173c7cc17484404a9724ff7465cbef2,4,"[5fc2ac1892404c37ab5919714e8b63fa.jpg, 8d64bce..."

In [144]:
# Ghi vào file user_list.txt, không bao gồm dòng tên cột
image_list_df.to_csv('image_list.txt', sep=' ', index=False, header=False)

print("File image_list.txt đã được tạo.")

File image_list.txt đã được tạo.

## Tạo file items_features

In [145]:
# Tạo cột item_id từ cột index trong df_b
fe_df = items_features_df.copy()

fe_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id,outfit.id,picture.id,file_name,displayOrder
0,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,"[ILAG, Tops, Spring, Summer, M, Pattern, Yello...","[Brand, Category, Seasons, Seasons, Size, Deta...",outfit.fffa1b9a3db6415d806f3c48f8ab58d9,2846,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,"[picture.649ea4f38ffa47eb92556af7d3195ba4, pic...","[649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...","[1, 2, 3, 4, 5]"
1,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,"[XS, Multi Season, Stylein, Tops, Cotton, Mult...","[Size, Seasons, Brand, Category, Material, Col...",outfit.ffef9d7c292a48b69076d2df2e32352f,2712,outfit.ffef9d7c292a48b69076d2df2e32352f,"[picture.7d86226f09f040bd81ef18fd24cf4e04, pic...","[7d86226f09f040bd81ef18fd24cf4e04.jpg, e88231a...","[1, 2]"
2,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,"[Cotton, Black, Everyday, Knitwear, L, Winter,...","[Material, Color, Occasion, Category, Size, Se...",outfit.ffeef842238f4dbdabc6c730a75aa2bd,6747,outfit.ffeef842238f4dbdabc6c730a75aa2bd,"[picture.b9342b85e6a94a6988e37cdb4f3fd0bb, pic...","[b9342b85e6a94a6988e37cdb4f3fd0bb.jpg, 723499a...","[1, 2, 3]"
3,outfit.ffebad2c479045a78adecdcd8f07427d,Bumble Dress Black Burnout Maxi,The Bumble Maxi Dress from Høst & Vår is a ful...,group.10995bb4c49c8a25a48fed9dc025beac,o_00089,2023-01-05 09:12:43.847,1800.0,590.0,1180.0,"[Summer, Dressed-up, Women, S, Spring, Dresses...","[Seasons, Occasion, Gender, Size, Seasons, Cat...",outfit.ffebad2c479045a78adecdcd8f07427d,5871,outfit.ffebad2c479045a78adecdcd8f07427d,"[picture.4a6ba45b29df49949d311ef1709b07fe, pic...","[4a6ba45b29df49949d311ef1709b07fe.jpg, 7c9cb5d...","[1, 2]"
4,outfit.ffe617f43d244ebc81228915cfcc6c8e,Platinum Blazer,Platinum Blazer is a classic and narrow suit j...,group.f2b0d1fde7052ef61a89b4ad3539b55c,o_00413,2022-04-01 12:25:15.312,2800.0,840.0,1680.0,"[Women, Business, Everyday, Black, Wool, Sprin...","[Gender, Occasion, Occasion, Color, Material, ...",outfit.ffe617f43d244ebc81228915cfcc6c8e,75,outfit.ffe617f43d244ebc81228915cfcc6c8e,"[picture.ae0d6fbd73e0496dac7d657c97da7acd, pic...","[ae0d6fbd73e0496dac7d657c97da7acd.jpg, e3bc772...","[1, 2, 3]"

## => Tạo feature1 và feature2

In [146]:
# Chuyển 'tag_categories' thành chuỗi, nối các phần tử trong danh sách với khoảng trắng
fe_df['outfit_tags'] = fe_df['outfit_tags'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x)

# Tạo cột feature1: kết hợp name và tag_categories với dấu cách giữa chúng
fe_df['feature1'] = fe_df['name'] + ' ' + fe_df['outfit_tags']

# Tạo cột feature2: là cột description từ df_a
fe_df['feature2'] = fe_df['description']

In [147]:
fe_df.head()

,id,name,description,group,owner,timeCreated,retailPrice,pricePerWeek,pricePerMonth,outfit_tags,tag_categories,item_id_original,item_id,outfit.id,picture.id,file_name,displayOrder,feature1,feature2
0,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,Yellow Shell Mellomholmene Blouse,This beautiful blouse features an adjustable n...,group.61ad2fcabb3e9197e3836376e6b67f2c,o_00577,2021-06-07 12:07:22.921,1300.0,590.0,1180.0,ILAG Tops Spring Summer M Pattern Yellow Women...,"[Brand, Category, Seasons, Seasons, Size, Deta...",outfit.fffa1b9a3db6415d806f3c48f8ab58d9,2846,outfit.fffa1b9a3db6415d806f3c48f8ab58d9,"[picture.649ea4f38ffa47eb92556af7d3195ba4, pic...","[649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...","[1, 2, 3, 4, 5]",Yellow Shell Mellomholmene Blouse ILAG Tops Sp...,This beautiful blouse features an adjustable n...
1,outfit.ffef9d7c292a48b69076d2df2e32352f,For sale - Jarvis Blouse,This wrap blouse has mid length sleeves and a ...,group.dfcaa57546b0b7a5e9eb204449b6cc1c,o_00030,2021-05-18 14:02:28.690,1500.0,590.0,1180.0,XS Multi Season Stylein Tops Cotton Multicolor...,"[Size, Seasons, Brand, Category, Material, Col...",outfit.ffef9d7c292a48b69076d2df2e32352f,2712,outfit.ffef9d7c292a48b69076d2df2e32352f,"[picture.7d86226f09f040bd81ef18fd24cf4e04, pic...","[7d86226f09f040bd81ef18fd24cf4e04.jpg, e88231a...","[1, 2]",For sale - Jarvis Blouse XS Multi Season Style...,This wrap blouse has mid length sleeves and a ...
2,outfit.ffeef842238f4dbdabc6c730a75aa2bd,Black Amber Pants,"Feel slack and nice dressed with this pant, ma...",group.ee297c977905eb21a123a4aea5fbb6d2,o_00602,2021-07-16 14:02:30.643,1200.0,590.0,1180.0,Cotton Black Everyday Knitwear L Winter Fall T...,"[Material, Color, Occasion, Category, Size, Se...",outfit.ffeef842238f4dbdabc6c730a75aa2bd,6747,outfit.ffeef842238f4dbdabc6c730a75aa2bd,"[picture.b9342b85e6a94a6988e37cdb4f3fd0bb, pic...","[b9342b85e6a94a6988e37cdb4f3fd0bb.jpg, 723499a...","[1, 2, 3]",Black Amber Pants Cotton Black Everyday Knitwe...,"Feel slack and nice dressed with this pant, ma..."
3,outfit.ffebad2c479045a78adecdcd8f07427d,Bumble Dress Black Burnout Maxi,The Bumble Maxi Dress from Høst & Vår is a ful...,group.10995bb4c49c8a25a48fed9dc025beac,o_00089,2023-01-05 09:12:43.847,1800.0,590.0,1180.0,Summer Dressed-up Women S Spring Dresses Flora...,"[Seasons, Occasion, Gender, Size, Seasons, Cat...",outfit.ffebad2c479045a78adecdcd8f07427d,5871,outfit.ffebad2c479045a78adecdcd8f07427d,"[picture.4a6ba45b29df49949d311ef1709b07fe, pic...","[4a6ba45b29df49949d311ef1709b07fe.jpg, 7c9cb5d...","[1, 2]",Bumble Dress Black Burnout Maxi Summer Dressed...,The Bumble Maxi Dress from Høst & Vår is a ful...
4,outfit.ffe617f43d244ebc81228915cfcc6c8e,Platinum Blazer,Platinum Blazer is a classic and narrow suit j...,group.f2b0d1fde7052ef61a89b4ad3539b55c,o_00413,2022-04-01 12:25:15.312,2800.0,840.0,1680.0,Women Business Everyday Black Wool Spring Ricc...,"[Gender, Occasion, Occasion, Color, Material, ...",outfit.ffe617f43d244ebc81228915cfcc6c8e,75,outfit.ffe617f43d244ebc81228915cfcc6c8e,"[picture.ae0d6fbd73e0496dac7d657c97da7acd, pic...","[ae0d6fbd73e0496dac7d657c97da7acd.jpg, e3bc772...","[1, 2, 3]",Platinum Blazer Women Business Everyday Black ...,Platinum Blazer is a classic and narrow suit j...

In [148]:
fe_df.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         ILAG Tops Spring Summer M Pattern Yellow Women...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
feature1            Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2            This beautiful blouse features an adjustable n...
Name: 0, dtype: object

=> path sẵn có từ dữ liệu gốc ( chưa detect phần thừa )

In [149]:
# import numpy as np
# import os
# # Tạo cột feature3: là danh sách embedings từ df_a

# # Thư mục chứa các file embeddings
# embeddings_dir = '/kaggle/input/vibrent-clothes-rental-dataset/embeddings/EfficientNet_V2_L_final'

# # Hàm tạo danh sách đường dẫn đầy đủ đến tệp .npy
# def create_embedding_paths(picture_ids):
#     return [os.path.join(embeddings_dir, f"{pic_id}.npy") for pic_id in picture_ids]

# # Sử dụng function
# fe_df['embedding_paths'] = fe_df['picture.id'].apply(create_embedding_paths)

=> path mới (đã detect phần thừa lưu ý số chiều )

In [150]:
import numpy as np
import os

# Thư mục chứa các file embeddings
embeddings_dir = '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full'

# Hàm tạo danh sách đường dẫn đầy đủ đến tệp .npy
def create_embedding_paths(picture_ids):
    return [os.path.join(embeddings_dir, f"{pic_id.split('.')[1]}.npy") for pic_id in picture_ids]

# Sử dụng function
fe_df['embedding_paths'] = fe_df['picture.id'].apply(create_embedding_paths)

## combine feature3 embeddings#1 ( mean )

In [151]:
cbf_f31 = fe_df.copy()

In [152]:
cbf_f31.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         ILAG Tops Spring Summer M Pattern Yellow Women...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
feature1            Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2            This beautiful blouse features an adjustable n...
embedding_paths     [/kaggle/input/mobilenet-emb/embeddings_MBNV2_...
Name: 0, dtype: object

In [153]:
cbf_f31.iloc[0]['embedding_paths']

['/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/649ea4f38ffa47eb92556af7d3195ba4.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/fb47724315704dc980a27311bed834e2.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c975446e9479495dac2713529edc4230.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/4685852ed93c439a944ca8ccdd3d1c52.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c2d4bb2bf67e4490bdb1c82a9f5bead3.npy']

In [154]:

def load_mean_embeddings(paths):
    """
    Load và combine embeddings của các ảnh trong một outfit
    paths: list các đường dẫn đến embedding files của một outfit
    """
    outfit_embeddings = []
    
    for path in paths:
        if os.path.isfile(path):
            # Load embedding và giữ nguyên shape
            embedding = np.load(path)
            # Print để debug
            # print("Single image embedding shape:", embedding.shape)  # Should be (1280,)
            outfit_embeddings.append(embedding.astype(np.float32))
    
    if outfit_embeddings:
        # Đảm bảo mỗi embedding là 1D array
        outfit_embeddings = [emb.flatten() for emb in outfit_embeddings]
        # Combine embeddings
        combined_embedding = np.mean(outfit_embeddings, axis=0)
        # Print để debug
        # print("Combined embedding shape:", combined_embedding.shape)  # Should be (1280,)
        return combined_embedding.tolist()
    return [0] * 1280  # Return zero vector nếu không có embedding


# Sử dụng function
cbf_f31['feature3'] = cbf_f31['embedding_paths'].apply(load_mean_embeddings)

# Kiểm tra sau khi load
print("Sample of feature3 first element:", len(cbf_f31['feature3'].iloc[0]))  # Should be 1280

Sample of feature3 first element: 1280

## combine feature3 embeddings#2 ( weighted )

In [155]:
cbf_f32 = fe_df.copy()

In [156]:
cbf_f32.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         ILAG Tops Spring Summer M Pattern Yellow Women...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
feature1            Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2            This beautiful blouse features an adjustable n...
embedding_paths     [/kaggle/input/mobilenet-emb/embeddings_MBNV2_...
Name: 0, dtype: object

In [157]:
cbf_f32.iloc[0]['embedding_paths']

['/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/649ea4f38ffa47eb92556af7d3195ba4.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/fb47724315704dc980a27311bed834e2.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c975446e9479495dac2713529edc4230.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/4685852ed93c439a944ca8ccdd3d1c52.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c2d4bb2bf67e4490bdb1c82a9f5bead3.npy']

In [158]:

def load_weighted_embeddings(paths, display_orders):
    """
    Load và combine embeddings của các ảnh trong một outfit với trọng số dựa trên display order.
    paths: list các đường dẫn đến embedding files của một outfit.
    display_orders: list thứ tự ưu tiên của các ảnh trong outfit.
    """
    outfit_embeddings = []
    valid_orders = []

    for idx, path in enumerate(paths):
        if os.path.isfile(path):
            embedding = np.load(path).flatten().astype(np.float32)
            outfit_embeddings.append(embedding)
            valid_orders.append(display_orders[idx])

    if outfit_embeddings:
        # Tính trọng số dựa vào displayOrder
        weights = 1 / (np.array(valid_orders) + 1)
        weights = weights / np.sum(weights)  # Chuẩn hóa trọng số
        
        # Áp dụng trọng số vào embeddings
        weighted_embedding = np.sum([w * emb for w, emb in zip(weights, outfit_embeddings)], axis=0)
        
        return weighted_embedding.tolist()

    # Trả về vector zero nếu không có embedding hợp lệ
    return [0] * 1280

# Áp dụng cho DataFrame fe_df
cbf_f32['feature3'] = cbf_f32.apply(
    lambda row: load_weighted_embeddings(row['embedding_paths'], row['displayOrder']),
    axis=1
)

# Kiểm tra kết quả
print("Feature3 sample embedding length:", len(cbf_f32['feature3'].iloc[1998]))  # Should be 1280

Feature3 sample embedding length: 1280

## combine feature3 embeddings#3 ( max )

In [159]:
cbf_f33 = fe_df.copy()

In [160]:
cbf_f33.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         ILAG Tops Spring Summer M Pattern Yellow Women...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
feature1            Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2            This beautiful blouse features an adjustable n...
embedding_paths     [/kaggle/input/mobilenet-emb/embeddings_MBNV2_...
Name: 0, dtype: object

In [161]:
cbf_f33.iloc[0]['embedding_paths']

['/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/649ea4f38ffa47eb92556af7d3195ba4.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/fb47724315704dc980a27311bed834e2.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c975446e9479495dac2713529edc4230.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/4685852ed93c439a944ca8ccdd3d1c52.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c2d4bb2bf67e4490bdb1c82a9f5bead3.npy']

In [162]:

def load_max_embeddings(paths):
    """
    Load và combine embeddings của các ảnh trong một outfit
    paths: list các đường dẫn đến embedding files của một outfit
    """
    outfit_embeddings = []
    
    for path in paths:
        if os.path.isfile(path):
            # Load embedding và giữ nguyên shape
            embedding = np.load(path)
            # Print để debug
            # print("Single image embedding shape:", embedding.shape)  # Should be (1280,)
            outfit_embeddings.append(embedding.astype(np.float32))
    
    if outfit_embeddings:
        # Đảm bảo mỗi embedding là 1D array
        outfit_embeddings = [emb.flatten() for emb in outfit_embeddings]
        # Combine embeddings
        combined_embedding = np.max(outfit_embeddings, axis=0)
        # Print để debug
        # print("Combined embedding shape:", combined_embedding.shape)  # Should be (1280,)
        return combined_embedding.tolist()
    return [0] * 1280  # Return zero vector nếu không có embedding


# Sử dụng function
cbf_f33['feature3'] = cbf_f33['embedding_paths'].apply(load_max_embeddings)

# Kiểm tra sau khi load
print("Sample of feature3 first element:", len(cbf_f33['feature3'].iloc[0]))  # Should be 1280

Sample of feature3 first element: 1280

## Dimensionality reduction with PCA

In [163]:
cbf_f31['feature3'].head()

0    [0.1985788643360138, 0.45808306336402893, 0.0,...
1    [1.552445888519287, 0.0, 1.1862998008728027, 1...
2    [0.49159327149391174, 0.96891850233078, 1.6426...
3    [0.21148864924907684, 0.0, 0.1682272106409073,...
4    [0.44339534640312195, 0.0, 0.15799225866794586...
Name: feature3, dtype: object

In [164]:
cbf_f32['feature3'].head()

0    [0.14888234436511993, 0.44530025124549866, 0.0...
1    [1.2419567108154297, 0.0, 0.9671372771263123, ...
2    [0.4549598693847656, 0.70406174659729, 1.73687...
3    [0.2537863850593567, 0.0, 0.1345817744731903, ...
4    [0.30722206830978394, 0.0, 0.14793531596660614...
Name: feature3, dtype: object

In [165]:
cbf_f33['feature3'].head()

0    [0.8535438776016235, 0.7846497297286987, 0.0, ...
1    [3.104891777038574, 0.0, 2.2821121215820312, 2...
2    [0.6065975427627563, 2.641875982284546, 2.1089...
3    [0.4229772984981537, 0.0, 0.3364544212818146, ...
4    [1.326857089996338, 0.0, 0.46035075187683105, ...
Name: feature3, dtype: object

In [166]:
# Gán lại kết quả vào fe_df sau khi kiểm tra
#mean
fe_df['feature3'] = cbf_f31['feature3']
#weight
# fe_df['feature3'] = cbf_f32['feature3']
#max
# fe_df['feature3'] = cbf_f33['feature3']

# Kiểm tra sau khi load
print("Sample of feature3 first element:", len(fe_df['feature3'].iloc[0]))  # Should be 1280

Sample of feature3 first element: 1280

In [167]:
fe_df.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         ILAG Tops Spring Summer M Pattern Yellow Women...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
feature1            Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2            This beautiful blouse features an adjustable n...
embedding_paths     [/kaggle/input/mobilenet-emb/embeddings_MBNV2_...
feature3            [0.1985788643360138, 0.45808306336402893, 0.0,...
Name: 0, dtype: object

In [168]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize
import numpy as np

# Kiểm tra và thay thế NaN bằng vector zero có cùng số chiều
image_embeddings = np.vstack([
    np.array(emb).reshape(1, -1) if isinstance(emb, list) else emb.reshape(1, -1)
    for emb in fe_df['feature3']
])
print("Image embeddings shape before normalization:", image_embeddings.shape)

# Thay thế NaN bằng vector zero
image_embeddings = np.nan_to_num(image_embeddings)

# Chuẩn hóa embeddings trước khi áp dụng PCA
image_embeddings_normalized = normalize(image_embeddings)

# Xác định số chiều mong muốn cho PCA
n_samples, n_features = image_embeddings_normalized.shape
n_components = min(768, n_features, n_samples)

# Áp dụng PCA
pca = PCA(n_components=n_components)
image_embeddings_reduced = pca.fit_transform(image_embeddings_normalized)

# Cập nhật cột feature3 mà không làm thay đổi thứ tự ban đầu
fe_df['feature3'] = list(image_embeddings_reduced)

# Kiểm tra kết quả
print("Feature3 vector size:", len(fe_df['feature3'].iloc[0]))

Image embeddings shape before normalization: (8944, 1280)
Feature3 vector size: 768

In [169]:
print(len(fe_df['feature3'].iloc[0]))  # Kiểm tra vector sau giảm chiều
print("Tổng số mẫu:", len(fe_df))

768
Tổng số mẫu: 8944

In [170]:
fe_df.iloc[0]

id                            outfit.fffa1b9a3db6415d806f3c48f8ab58d9
name                                Yellow Shell Mellomholmene Blouse
description         This beautiful blouse features an adjustable n...
group                          group.61ad2fcabb3e9197e3836376e6b67f2c
owner                                                         o_00577
timeCreated                                   2021-06-07 12:07:22.921
retailPrice                                                    1300.0
pricePerWeek                                                    590.0
pricePerMonth                                                  1180.0
outfit_tags         ILAG Tops Spring Summer M Pattern Yellow Women...
tag_categories      [Brand, Category, Seasons, Seasons, Size, Deta...
item_id_original              outfit.fffa1b9a3db6415d806f3c48f8ab58d9
item_id                                                          2846
outfit.id                     outfit.fffa1b9a3db6415d806f3c48f8ab58d9
picture.id          [picture.649ea4f38ffa47eb92556af7d3195ba4, pic...
file_name           [649ea4f38ffa47eb92556af7d3195ba4.jpg, fb47724...
displayOrder                                          [1, 2, 3, 4, 5]
feature1            Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2            This beautiful blouse features an adjustable n...
embedding_paths     [/kaggle/input/mobilenet-emb/embeddings_MBNV2_...
feature3            [0.10964352284348017, 0.09651304239120508, 0.0...
Name: 0, dtype: object

In [171]:
fe_df['displayOrder'].head(10)

0    [1, 2, 3, 4, 5]
1             [1, 2]
2          [1, 2, 3]
3             [1, 2]
4          [1, 2, 3]
5                [1]
6                [0]
7       [1, 2, 3, 4]
8          [1, 2, 3]
9       [1, 2, 3, 4]
Name: displayOrder, dtype: object

In [172]:
fe_df['displayOrder'].tail(10)

8934    [1, 2, 3, 4]
8935       [1, 2, 3]
8936    [1, 2, 3, 4]
8937    [0, 0, 0, 0]
8938             [1]
8939    [1, 2, 3, 4]
8940       [1, 2, 3]
8941    [1, 2, 3, 4]
8942    [1, 2, 3, 4]
8943          [1, 2]
Name: displayOrder, dtype: object

In [173]:
fe_df.iloc[0]['embedding_paths']

['/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/649ea4f38ffa47eb92556af7d3195ba4.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/fb47724315704dc980a27311bed834e2.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c975446e9479495dac2713529edc4230.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/4685852ed93c439a944ca8ccdd3d1c52.npy',
 '/kaggle/input/mobilenet-emb/embeddings_MBNV2_full/c2d4bb2bf67e4490bdb1c82a9f5bead3.npy']

In [174]:
fe_df.iloc[0]['picture.id']

['picture.649ea4f38ffa47eb92556af7d3195ba4',
 'picture.fb47724315704dc980a27311bed834e2',
 'picture.c975446e9479495dac2713529edc4230',
 'picture.4685852ed93c439a944ca8ccdd3d1c52',
 'picture.c2d4bb2bf67e4490bdb1c82a9f5bead3']

In [175]:
len(fe_df.iloc[0]['feature3'])

768

In [176]:
# Chọn chỉ các cột cần thiết để tạo df_c
df_c = fe_df[['item_id', 'feature1', 'feature2' ,'feature3']]

# Hiển thị kết quả
df_c.head()

,item_id,feature1,feature2,feature3
0,2846,Yellow Shell Mellomholmene Blouse ILAG Tops Sp...,This beautiful blouse features an adjustable n...,"[0.10964352284348017, 0.09651304239120508, 0.0..."
1,2712,For sale - Jarvis Blouse XS Multi Season Style...,This wrap blouse has mid length sleeves and a ...,"[-0.13004627777502137, -0.2083090105890317, 0...."
2,6747,Black Amber Pants Cotton Black Everyday Knitwe...,"Feel slack and nice dressed with this pant, ma...","[-0.19392558043462788, -0.1586011855766103, 0...."
3,5871,Bumble Dress Black Burnout Maxi Summer Dressed...,The Bumble Maxi Dress from Høst & Vår is a ful...,"[-0.35813668018597444, -0.018954081450289352, ..."
4,75,Platinum Blazer Women Business Everyday Black ...,Platinum Blazer is a classic and narrow suit j...,"[-0.4170340325049188, -0.16846395736268407, -0..."

In [177]:
df_c['item_id'][0]

2846

In [178]:
df_c.iloc[0]

item_id                                                  2846
feature1    Yellow Shell Mellomholmene Blouse ILAG Tops Sp...
feature2    This beautiful blouse features an adjustable n...
feature3    [0.10964352284348017, 0.09651304239120508, 0.0...
Name: 0, dtype: object

In [179]:
df_c['feature1'][0]

'Yellow Shell Mellomholmene Blouse ILAG Tops Spring Summer M Pattern Yellow Women Blouses Everyday Cotton'

In [180]:
df_c['feature2'][0]

'This beautiful blouse features an adjustable neckline, a short and wide silhouette, and ruching details on the sleeves. The cotton fabric makes this the perfect blouse for warmer days. '

In [181]:
df_c['feature3'][1998][0]

0.1755824442470876

In [182]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   8944 non-null   int64
 1   feature1  8944 non-null   object
 2   feature2  8944 non-null   object
 3   feature3  8944 non-null   object
dtypes: int64(1), object(3)
memory usage: 279.6+ KB

In [183]:
df_c.isnull().sum()

item_id     0
feature1    0
feature2    0
feature3    0
dtype: int64

In [184]:
# Lưu DataFrame df_c vào file CSV
df_c.to_csv('items_features.csv', index=False)

# Hiển thị thông báo lưu thành công
print("DataFrame đã được lưu vào items_features.csv")

DataFrame đã được lưu vào items_features.csv

# Debug Item feature (sửa khi load items_features trong load_data)

In [185]:
xxx = pd.read_csv('/kaggle/working/items_features.csv')

In [186]:
xxx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8944 entries, 0 to 8943
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item_id   8944 non-null   int64
 1   feature1  8944 non-null   object
 2   feature2  8944 non-null   object
 3   feature3  8944 non-null   object
dtypes: int64(1), object(3)
memory usage: 279.6+ KB

In [187]:
xxx.head()

,item_id,feature1,feature2,feature3
0,2846,Yellow Shell Mellomholmene Blouse ILAG Tops Sp...,This beautiful blouse features an adjustable n...,[ 1.09643523e-01 9.65130424e-02 8.44811590e-...
1,2712,For sale - Jarvis Blouse XS Multi Season Style...,This wrap blouse has mid length sleeves and a ...,[-1.30046278e-01 -2.08309011e-01 7.91625547e-...
2,6747,Black Amber Pants Cotton Black Everyday Knitwe...,"Feel slack and nice dressed with this pant, ma...",[-1.93925580e-01 -1.58601186e-01 1.79685231e-...
3,5871,Bumble Dress Black Burnout Maxi Summer Dressed...,The Bumble Maxi Dress from Høst & Vår is a ful...,[-3.58136680e-01 -1.89540815e-02 -1.35791300e-...
4,75,Platinum Blazer Women Business Everyday Black ...,Platinum Blazer is a classic and narrow suit j...,[-4.17034033e-01 -1.68463957e-01 -1.12388731e-...

In [188]:
xxx['feature3'][0]

'[ 1.09643523e-01  9.65130424e-02  8.44811590e-02 -1.86984879e-02\n -1.09450685e-01  1.57179867e-01  1.20255944e-01 -1.46143766e-01\n -9.74966429e-03  1.13435408e-01 -1.16760295e-02  2.91654603e-02\n -4.34674899e-02 -1.24051679e-01  4.79845393e-03 -7.93851824e-02\n -2.73531832e-02 -5.75467683e-02  3.55287791e-02 -4.61642157e-02\n -4.53384866e-02 -5.15398766e-02 -5.34103725e-02  3.58137725e-02\n  1.59658213e-02 -1.58451934e-02 -2.63646160e-02 -2.93628023e-02\n -6.52932002e-02  1.17712693e-02  4.21524681e-02 -6.74482470e-02\n -6.17109343e-03 -7.00347933e-02 -7.65909480e-03  6.25067573e-02\n -4.74212383e-03 -5.48204285e-02  4.29739546e-02  1.52694513e-02\n -2.87110627e-02  2.30776753e-02 -9.41021669e-03 -8.21608884e-03\n  2.93901950e-02  2.55357349e-02 -5.84884700e-03  1.89265239e-02\n  2.06973889e-02 -1.19271445e-02 -6.40919987e-02 -4.67790165e-02\n -1.09818095e-02 -1.78093350e-02  2.20604100e-02 -4.30548764e-02\n -3.31586766e-02 -1.94563732e-02  4.98048852e-02 -2.41408310e-02\n -1.54471089e-02  1.29872610e-02 -5.49488342e-02 -3.78764012e-03\n  2.11193424e-03 -4.52356079e-02 -4.07783365e-02  2.25073452e-02\n -1.28133734e-02  1.71669950e-02  2.95003774e-02 -2.66826169e-02\n  2.39324645e-02  1.69016476e-02 -1.54633386e-02 -2.51666042e-02\n -3.26603859e-02  8.30880753e-04 -2.37605728e-02  7.02554596e-02\n  2.69700945e-04  9.27374651e-03  3.46761766e-02  3.15167494e-02\n -1.41719914e-02  6.00515813e-03  2.77675891e-04  1.37829836e-02\n  2.54886963e-02 -2.93211634e-02 -7.52837845e-03 -4.91219373e-02\n -1.85255353e-02  3.08161113e-03 -5.52850618e-04 -1.78823914e-02\n  1.68616757e-02  3.43023728e-03 -3.35036157e-02 -2.04678370e-02\n  3.82972851e-02  7.85614677e-03 -5.17875831e-03  4.82907105e-02\n -2.18551100e-02 -3.22003825e-02 -3.55519700e-02  3.16825303e-03\n  3.68108166e-02  3.23527540e-03 -9.23175995e-03  3.05453134e-02\n  8.75427331e-03 -7.78510091e-03  3.29569479e-02 -2.72379699e-02\n -1.69372865e-02 -7.96496464e-04 -2.44571419e-02 -1.29766858e-02\n -8.05004520e-03  1.75536502e-02  1.38671739e-04 -2.77539650e-02\n -1.60076631e-02 -2.11878917e-02  7.55152395e-03 -2.27179706e-02\n  3.19851897e-03 -1.29591680e-02 -2.82880079e-02 -3.13820288e-02\n  8.40521923e-03 -2.42545449e-02 -9.47309017e-03  1.84097213e-02\n  7.02698139e-03  1.38199928e-02  1.44972218e-02  1.38207454e-02\n  1.11306158e-02  2.43608771e-02 -3.84341641e-02  3.97895991e-03\n  2.07439092e-02 -4.48130905e-03 -1.29383197e-02  2.18846624e-02\n  1.90238391e-02  1.86706819e-02  1.13621084e-02 -4.26210659e-02\n  2.08021918e-02 -1.77135756e-02 -1.11247092e-02  1.81607391e-02\n -1.46895678e-02  1.71899736e-02 -2.57794213e-04  2.02200035e-02\n  1.17443682e-02  5.52940741e-02 -6.89391228e-03  3.07409647e-02\n -1.30148412e-02  3.91994864e-02  3.97185481e-03  7.52609096e-04\n -1.23020621e-03 -5.39635033e-03  2.94373517e-03 -1.43414227e-03\n  7.16542214e-04  3.14716660e-02 -2.31936681e-03  1.39229613e-02\n -3.09730366e-02 -5.94659643e-03  1.77961271e-02 -1.33864932e-02\n  4.87884495e-03  5.80328408e-03  2.29471570e-02 -1.54948435e-02\n  1.66768669e-03  2.10595343e-02 -1.46467338e-02 -6.00865894e-03\n  6.00357867e-03  1.88223650e-02 -1.33129324e-02 -2.12614319e-02\n -1.17104752e-02  3.68707222e-03 -7.06305429e-03 -3.55940085e-02\n  2.83691241e-02  1.72153917e-02  1.70792325e-03  1.49693550e-02\n -2.20038602e-02 -1.19804767e-02  8.70019932e-03 -1.60169937e-02\n  1.06786126e-03  2.52123631e-03 -5.04919466e-03 -2.61474268e-02\n  4.16964749e-03 -2.39426298e-02 -1.53199187e-03  6.75881167e-03\n  8.92537369e-03 -6.55877743e-03  1.46822412e-02 -1.34483313e-02\n -5.56068676e-03  8.64271435e-03  1.05681291e-02 -3.53616116e-04\n  7.51520711e-03  1.89942076e-03 -1.12829062e-02  1.24823454e-02\n  3.79550895e-03 -1.62102023e-02 -6.10051878e-03  1.15537721e-02\n  7.91559802e-03  2.67304509e-02 -6.20836575e-03  5.11022586e-03\n  1.13795946e-02 -1.47115949e-02  9.98400054e-03 -2.88486217e-03\n  7.41743404e-03 -7.39548605e-03  5.86244394e-03  9.66726116e-03\n  2.72824498e-02  5.43846941e-03  2.38547797e-02  8.84021348e-04\n  4.68772102e-03  7.67957591e-03  2.02305097e-02  3.72222396e-04\n -4.19116864e-03  1.49268209e-02  1.67988830e-02 -2.95390926e-03\n  9.37238299e-03  5.66362415e-04  4.77293593e-03 -1.67986099e-02\n -4.92262090e-04 -1.50172961e-02 -1.59313657e-02  1.22178313e-02\n  6.83963633e-03 -2.16578737e-03  7.62498237e-03 -1.40344691e-02\n -1.61709299e-02 -4.05512421e-03  8.85103061e-03  7.27427177e-04\n  2.24729274e-03  1.10937031e-02  7.94880055e-03 -1.41788870e-02\n  5.63622988e-03  1.82267331e-02 -8.63660863e-03 -1.53129409e-02\n -1.88958339e-02 -2.83613562e-02  1.74142700e-02  3.72003141e-03\n -9.28785333e-03 -5.37923847e-03 -5.15746233e-03 -1.57283605e-02\n -3.92455460e-03 -6.00649691e-04 -1.12859696e-02 -1.18490455e-02\n  7.19750761e-03  5.93332885e-03 -1.35071572e-02  6.31956292e-03\n -7.11313778e-03  1.83695101e-02 -2.07954466e-03  1.27920738e-02\n -2.17146902e-03 -1.62080946e-02  4.36804220e-04 -9.02771943e-03\n  8.36846578e-03 -1.87999052e-02 -8.89688194e-03  2.66884219e-03\n  8.81706262e-03 -1.12746440e-02 -9.34280988e-03  1.28559757e-02\n  1.00546104e-03 -1.85092697e-02  2.90180845e-03  1.06819044e-02\n  1.13662540e-02  1.69335216e-02 -6.99413706e-03  8.01764540e-03\n -9.02197684e-03  2.77920309e-04 -7.87566011e-03 -3.91818439e-03\n -4.09373417e-03 -1.47336598e-02 -1.21758942e-02  1.59286446e-03\n -1.24712685e-02 -9.83554527e-03 -5.97063197e-03 -7.21730032e-03\n  1.15574716e-03 -1.25831736e-02  7.12163726e-04  1.26318316e-02\n  5.45266840e-03  4.59209825e-03  2.40762181e-03 -1.10668400e-02\n  3.29180479e-03 -9.35930472e-03  1.55408543e-02 -1.50649749e-02\n -3.75786926e-04  8.63847063e-03 -2.79132062e-02 -1.15491986e-02\n  1.13515240e-02 -7.94644637e-03  4.91133930e-03  1.99188961e-03\n -3.41970498e-03 -1.78597109e-03 -3.61411036e-03 -1.22152308e-02\n  5.64084072e-03  2.10962846e-02 -2.95406887e-03 -2.29196454e-03\n -2.07780026e-02  9.64712407e-03 -1.38934490e-02  1.35231548e-02\n  7.02192258e-04 -4.93811514e-03  1.14369549e-03 -1.66686893e-03\n  1.64904871e-02 -7.04577585e-03 -5.06501059e-03 -1.82151668e-02\n  9.04714218e-03  3.80024326e-03 -6.75275065e-03  8.11522706e-03\n -8.45735120e-03  2.83040971e-03  6.59138549e-03  4.40290174e-03\n -7.72921228e-03  2.96463041e-04 -1.92350842e-03  1.23191734e-02\n -4.77926393e-03  4.29258898e-03  7.31605669e-04  1.38225463e-02\n -1.49166218e-02 -9.61096657e-03 -1.00440982e-03 -9.67148405e-03\n  5.82565126e-03 -2.70532102e-02 -1.30953637e-02  3.16511775e-03\n  2.09071326e-02 -1.22663601e-02  1.68245722e-02 -4.27372998e-03\n  2.93297736e-02 -7.34112735e-04  9.30270467e-03 -7.15105053e-03\n -2.00282385e-03 -1.23084913e-02  1.69382293e-03 -2.17785676e-03\n  5.14765081e-03  3.08377969e-03  1.07130260e-02  4.34360247e-03\n -4.67651666e-03  1.67709036e-02 -1.48252942e-02  9.21367239e-04\n  4.47432399e-03  1.79258201e-02  4.70400427e-03  5.85418948e-03\n  1.74210454e-02  1.53547689e-02 -1.95434573e-02 -1.92398244e-03\n  1.58916176e-04  5.39830891e-03 -2.83276920e-02  1.31280150e-02\n  2.16750211e-03  1.33012722e-02 -2.39546517e-03  1.43738656e-03\n -6.99728658e-04 -6.24253531e-03 -4.52827989e-03  4.94454001e-03\n -3.42791964e-04 -6.84896537e-03  2.61988605e-03  6.48539208e-03\n -1.24867188e-02 -3.75809227e-03  3.23110571e-03 -5.89689792e-03\n  1.95225015e-03 -1.10603962e-02 -2.87689550e-04 -3.99887850e-03\n -5.70128938e-03  9.98992713e-03 -1.00613408e-03 -6.04489155e-03\n  7.32884901e-03  5.27675914e-04  7.51616276e-03 -1.71491934e-03\n -3.36483004e-03 -3.31511247e-03  3.64890827e-03  4.38660515e-03\n  5.86599733e-03 -8.45017019e-03  1.42204684e-02 -7.21043273e-03\n  2.52871828e-03  1.09289128e-02  2.28053458e-03  6.63519670e-03\n  9.28098043e-04 -7.93483191e-03 -4.74921363e-03 -1.10680664e-02\n  7.94794078e-03 -1.78913054e-02 -4.02793999e-03  1.14264585e-02\n -3.85316759e-03 -2.28145314e-03  5.97551419e-03 -8.27524433e-03\n -2.56184897e-03 -1.37006519e-02 -1.51792447e-02 -3.29738929e-03\n  1.70445171e-02 -5.17967747e-03  3.12653953e-03 -1.87572266e-03\n -4.07764430e-03 -1.13134173e-02 -7.67292451e-03  1.00620891e-02\n  9.31140941e-04  5.95909873e-03 -3.26368012e-03 -1.29271141e-04\n  1.16767145e-02  2.92930253e-03 -1.27451312e-03 -3.36946981e-03\n  5.72282940e-03 -1.24772111e-04 -5.67945045e-03 -7.11120677e-03\n  4.50042401e-03  2.52224805e-03  2.14936364e-03 -4.41701785e-03\n  2.88634443e-02 -1.70996592e-04  9.76890781e-04  7.54938862e-03\n  6.66327716e-03 -1.67367783e-03 -1.27772517e-03 -8.42372947e-04\n -1.10648576e-02 -7.74017477e-04  7.25163149e-03  1.10113511e-02\n  1.07839017e-02  1.77868255e-02  8.17801760e-03  2.37631310e-03\n  1.33346413e-03  7.57144466e-03 -1.50539535e-02 -5.92467941e-03\n  1.92592930e-03 -9.15219241e-03  3.95031147e-03 -6.19893209e-03\n -7.90335904e-03 -3.05912063e-03 -5.38219128e-03  5.26673288e-03\n -1.39147172e-03  2.87303960e-03 -5.47911621e-03 -1.97957967e-03\n -4.44110665e-03  4.11835385e-03  9.03293531e-04  5.85757911e-03\n -8.99894667e-03 -3.69951958e-03 -8.58166336e-03  6.78014480e-03\n -1.31685184e-02 -8.44430523e-03 -5.54095403e-03 -5.33499709e-03\n  5.49492860e-03  1.40999179e-02 -6.75101070e-03 -8.10116676e-04\n -6.55555632e-03  1.35999071e-03  6.99175097e-04  3.66522346e-03\n  1.07518202e-02  1.48572717e-03 -5.30832358e-03 -1.54271460e-04\n -3.75611390e-03 -3.97528461e-03 -8.78803952e-03 -1.17842761e-03\n  7.71529661e-03 -1.32787267e-02 -9.99958463e-03 -1.16858818e-02\n  1.23140264e-04 -4.74103900e-03 -5.56737620e-03  6.14724077e-03\n -3.06752692e-03  1.68636740e-02  1.77878047e-03  4.86924390e-03\n -3.19999986e-03 -4.27410726e-03  7.28418801e-03  5.15522054e-04\n -2.63149941e-03  6.97001752e-04 -7.77299897e-03 -4.40128707e-03\n -5.31377604e-03  6.82216169e-03  2.37959962e-03  6.13177619e-03\n  5.02704257e-03 -8.49634634e-03 -1.06686266e-03 -9.50401257e-03\n  2.00576261e-03  2.16556265e-03 -5.85695558e-03  1.21252235e-02\n  1.22748775e-02 -1.35092016e-03  8.46538679e-03 -8.58826638e-03\n -3.56286665e-03 -4.55207629e-03 -7.66348019e-03  9.64029700e-03\n  9.53410257e-03 -8.64278563e-03 -8.48802388e-03 -6.82254194e-03\n -2.07264086e-03  4.99097182e-03  1.12205263e-02  4.42629663e-03\n  5.60797245e-03  1.85667509e-02 -1.11683383e-02 -4.95597692e-03\n -1.08173243e-02  1.90128083e-03 -1.86026432e-02 -1.10044647e-03\n  1.06557335e-03  5.03669135e-03  5.79854581e-04  4.82871635e-03\n  1.09045492e-02 -3.93816454e-03  1.00661547e-02  6.76069871e-03\n  3.57309781e-03 -5.02485027e-03 -4.43077208e-03  1.75827836e-02\n  2.74798231e-03 -1.36455881e-02  9.40750596e-03 -4.03583066e-03\n  3.09208445e-03 -4.60438847e-03  1.07881867e-03 -2.69105966e-03\n  9.29076312e-03 -1.02075719e-02 -4.56475655e-03 -5.48535785e-03\n -1.72214980e-03 -5.63834354e-03  1.12616144e-02 -3.27179110e-04\n -9.15571740e-03  2.63780826e-03  5.12984198e-03  4.90999818e-03\n  2.57469844e-04  1.59815085e-04 -4.38298614e-03  1.53438070e-03\n -4.80002382e-03 -8.34059070e-03  6.46456169e-04 -1.74446060e-03\n  5.73759843e-03  4.41936952e-03  1.27058897e-03 -6.84153916e-03\n -1.09236296e-02 -2.97547737e-03  7.79326537e-03 -1.32040136e-02\n  5.92850938e-04 -5.29444578e-04 -2.86855383e-03 -7.87974426e-03\n  2.94517656e-03  6.46054501e-03  7.06202315e-03 -9.39617826e-04\n -6.93884712e-04  2.10606190e-03 -4.72945246e-03  1.51339534e-02\n -5.31839560e-03 -2.19557069e-03 -1.40836228e-02 -5.03989753e-03\n -4.84465267e-03  2.42098816e-03  2.10703140e-03 -7.69680845e-04\n  1.73602258e-03  4.08996958e-04  4.86715748e-03 -2.56294506e-03\n -2.74199648e-03 -7.89048358e-03 -2.55439276e-04 -2.16190956e-03\n -2.92109469e-03 -5.87252459e-03 -6.49980636e-03  6.36505303e-04\n  1.28434020e-03 -5.61182688e-03 -9.16142383e-03 -6.62694881e-03\n -3.57868713e-03  9.32033255e-03 -2.33926401e-03 -3.46759980e-03\n  1.07808051e-02 -1.12111083e-02 -3.36543763e-03 -5.24959393e-03\n  1.85433930e-03 -1.14632472e-02 -7.52728554e-03  6.51633667e-03\n  5.73530418e-03  4.46413681e-03 -3.54284948e-03 -2.10560735e-03\n -1.18606589e-02  6.23778841e-03 -4.79028589e-03 -4.92159987e-03\n -1.07947681e-02  8.49895503e-03  7.22171063e-03 -5.76148513e-03\n  2.05608948e-04  9.53402431e-03  3.55498443e-03  8.89695009e-04\n  9.27089388e-03 -9.28348992e-04  5.91706001e-03 -5.52630460e-03\n -3.40768031e-03 -3.31594105e-03 -2.41010975e-03  5.56045305e-03\n -9.50888900e-03 -1.50056179e-03  1.88776172e-03  4.55224291e-03\n -1.42024269e-04  3.49815211e-03 -2.53088867e-03  2.89083900e-03\n  1.56401866e-02 -6.58178006e-03 -4.37098822e-03 -3.28132370e-03\n -2.11843373e-03 -9.45008730e-03  4.54144000e-03  4.22816642e-05\n  3.04665656e-03  1.35111129e-03 -8.27425688e-03 -3.76932366e-03\n  1.18359330e-04 -8.71289368e-04  2.29643450e-03  8.69915405e-04\n -1.87922668e-03  6.60220542e-03  2.53626437e-03 -1.81909865e-04]'

In [189]:
xxx['feature3'][0][0]

'['

In [190]:
# Chuyển string vector thành numpy array
def parse_vector_string(vector_string):
    # Loại bỏ dấu ngoặc vuông và split theo khoảng trắng
    vector = vector_string.strip('[]').split()
    # Chuyển đổi sang float
    return np.array([float(x) for x in vector])

image_embeddings = np.vstack(
    xxx['feature3'].apply(parse_vector_string).values
)

In [191]:
image_embeddings[0]

array([ 1.09643523e-01,  9.65130424e-02,  8.44811590e-02, -1.86984879e-02,
       -1.09450685e-01,  1.57179867e-01,  1.20255944e-01, -1.46143766e-01,
       -9.74966429e-03,  1.13435408e-01, -1.16760295e-02,  2.91654603e-02,
       -4.34674899e-02, -1.24051679e-01,  4.79845393e-03, -7.93851824e-02,
       -2.73531832e-02, -5.75467683e-02,  3.55287791e-02, -4.61642157e-02,
       -4.53384866e-02, -5.15398766e-02, -5.34103725e-02,  3.58137725e-02,
        1.59658213e-02, -1.58451934e-02, -2.63646160e-02, -2.93628023e-02,
       -6.52932002e-02,  1.17712693e-02,  4.21524681e-02, -6.74482470e-02,
       -6.17109343e-03, -7.00347933e-02, -7.65909480e-03,  6.25067573e-02,
       -4.74212383e-03, -5.48204285e-02,  4.29739546e-02,  1.52694513e-02,
       -2.87110627e-02,  2.30776753e-02, -9.41021669e-03, -8.21608884e-03,
        2.93901950e-02,  2.55357349e-02, -5.84884700e-03,  1.89265239e-02,
        2.06973889e-02, -1.19271445e-02, -6.40919987e-02, -4.67790165e-02,
       -1.09818095e-02, -1.78093350e-02,  2.20604100e-02, -4.30548764e-02,
       -3.31586766e-02, -1.94563732e-02,  4.98048852e-02, -2.41408310e-02,
       -1.54471089e-02,  1.29872610e-02, -5.49488342e-02, -3.78764012e-03,
        2.11193424e-03, -4.52356079e-02, -4.07783365e-02,  2.25073452e-02,
       -1.28133734e-02,  1.71669950e-02,  2.95003774e-02, -2.66826169e-02,
        2.39324645e-02,  1.69016476e-02, -1.54633386e-02, -2.51666042e-02,
       -3.26603859e-02,  8.30880753e-04, -2.37605728e-02,  7.02554596e-02,
        2.69700945e-04,  9.27374651e-03,  3.46761766e-02,  3.15167494e-02,
       -1.41719914e-02,  6.00515813e-03,  2.77675891e-04,  1.37829836e-02,
        2.54886963e-02, -2.93211634e-02, -7.52837845e-03, -4.91219373e-02,
       -1.85255353e-02,  3.08161113e-03, -5.52850618e-04, -1.78823914e-02,
        1.68616757e-02,  3.43023728e-03, -3.35036157e-02, -2.04678370e-02,
        3.82972851e-02,  7.85614677e-03, -5.17875831e-03,  4.82907105e-02,
       -2.18551100e-02, -3.22003825e-02, -3.55519700e-02,  3.16825303e-03,
        3.68108166e-02,  3.23527540e-03, -9.23175995e-03,  3.05453134e-02,
        8.75427331e-03, -7.78510091e-03,  3.29569479e-02, -2.72379699e-02,
       -1.69372865e-02, -7.96496464e-04, -2.44571419e-02, -1.29766858e-02,
       -8.05004520e-03,  1.75536502e-02,  1.38671739e-04, -2.77539650e-02,
       -1.60076631e-02, -2.11878917e-02,  7.55152395e-03, -2.27179706e-02,
        3.19851897e-03, -1.29591680e-02, -2.82880079e-02, -3.13820288e-02,
        8.40521923e-03, -2.42545449e-02, -9.47309017e-03,  1.84097213e-02,
        7.02698139e-03,  1.38199928e-02,  1.44972218e-02,  1.38207454e-02,
        1.11306158e-02,  2.43608771e-02, -3.84341641e-02,  3.97895991e-03,
        2.07439092e-02, -4.48130905e-03, -1.29383197e-02,  2.18846624e-02,
        1.90238391e-02,  1.86706819e-02,  1.13621084e-02, -4.26210659e-02,
        2.08021918e-02, -1.77135756e-02, -1.11247092e-02,  1.81607391e-02,
       -1.46895678e-02,  1.71899736e-02, -2.57794213e-04,  2.02200035e-02,
        1.17443682e-02,  5.52940741e-02, -6.89391228e-03,  3.07409647e-02,
       -1.30148412e-02,  3.91994864e-02,  3.97185481e-03,  7.52609096e-04,
       -1.23020621e-03, -5.39635033e-03,  2.94373517e-03, -1.43414227e-03,
        7.16542214e-04,  3.14716660e-02, -2.31936681e-03,  1.39229613e-02,
       -3.09730366e-02, -5.94659643e-03,  1.77961271e-02, -1.33864932e-02,
        4.87884495e-03,  5.80328408e-03,  2.29471570e-02, -1.54948435e-02,
        1.66768669e-03,  2.10595343e-02, -1.46467338e-02, -6.00865894e-03,
        6.00357867e-03,  1.88223650e-02, -1.33129324e-02, -2.12614319e-02,
       -1.17104752e-02,  3.68707222e-03, -7.06305429e-03, -3.55940085e-02,
        2.83691241e-02,  1.72153917e-02,  1.70792325e-03,  1.49693550e-02,
       -2.20038602e-02, -1.19804767e-02,  8.70019932e-03, -1.60169937e-02,
        1.06786126e-03,  2.52123631e-03, -5.04919466e-03, -2.61474268e-02,
        4.16964749e-03, -2.39426298e-02, -1.53199187e-03,  6.75881167e-03,
        8.92537369e-03, -6.55877743e-03,  1.46822412e-02, -1.34483313e-02,
       -5.56068676e-03,  8.64271435e-03,  1.05681291e-02, -3.53616116e-04,
        7.51520711e-03,  1.89942076e-03, -1.12829062e-02,  1.24823454e-02,
        3.79550895e-03, -1.62102023e-02, -6.10051878e-03,  1.15537721e-02,
        7.91559802e-03,  2.67304509e-02, -6.20836575e-03,  5.11022586e-03,
        1.13795946e-02, -1.47115949e-02,  9.98400054e-03, -2.88486217e-03,
        7.41743404e-03, -7.39548605e-03,  5.86244394e-03,  9.66726116e-03,
        2.72824498e-02,  5.43846941e-03,  2.38547797e-02,  8.84021348e-04,
        4.68772102e-03,  7.67957591e-03,  2.02305097e-02,  3.72222396e-04,
       -4.19116864e-03,  1.49268209e-02,  1.67988830e-02, -2.95390926e-03,
        9.37238299e-03,  5.66362415e-04,  4.77293593e-03, -1.67986099e-02,
       -4.92262090e-04, -1.50172961e-02, -1.59313657e-02,  1.22178313e-02,
        6.83963633e-03, -2.16578737e-03,  7.62498237e-03, -1.40344691e-02,
       -1.61709299e-02, -4.05512421e-03,  8.85103061e-03,  7.27427177e-04,
        2.24729274e-03,  1.10937031e-02,  7.94880055e-03, -1.41788870e-02,
        5.63622988e-03,  1.82267331e-02, -8.63660863e-03, -1.53129409e-02,
       -1.88958339e-02, -2.83613562e-02,  1.74142700e-02,  3.72003141e-03,
       -9.28785333e-03, -5.37923847e-03, -5.15746233e-03, -1.57283605e-02,
       -3.92455460e-03, -6.00649691e-04, -1.12859696e-02, -1.18490455e-02,
        7.19750761e-03,  5.93332885e-03, -1.35071572e-02,  6.31956292e-03,
       -7.11313778e-03,  1.83695101e-02, -2.07954466e-03,  1.27920738e-02,
       -2.17146902e-03, -1.62080946e-02,  4.36804220e-04, -9.02771943e-03,
        8.36846578e-03, -1.87999052e-02, -8.89688194e-03,  2.66884219e-03,
        8.81706262e-03, -1.12746440e-02, -9.34280988e-03,  1.28559757e-02,
        1.00546104e-03, -1.85092697e-02,  2.90180845e-03,  1.06819044e-02,
        1.13662540e-02,  1.69335216e-02, -6.99413706e-03,  8.01764540e-03,
       -9.02197684e-03,  2.77920309e-04, -7.87566011e-03, -3.91818439e-03,
       -4.09373417e-03, -1.47336598e-02, -1.21758942e-02,  1.59286446e-03,
       -1.24712685e-02, -9.83554527e-03, -5.97063197e-03, -7.21730032e-03,
        1.15574716e-03, -1.25831736e-02,  7.12163726e-04,  1.26318316e-02,
        5.45266840e-03,  4.59209825e-03,  2.40762181e-03, -1.10668400e-02,
        3.29180479e-03, -9.35930472e-03,  1.55408543e-02, -1.50649749e-02,
       -3.75786926e-04,  8.63847063e-03, -2.79132062e-02, -1.15491986e-02,
        1.13515240e-02, -7.94644637e-03,  4.91133930e-03,  1.99188961e-03,
       -3.41970498e-03, -1.78597109e-03, -3.61411036e-03, -1.22152308e-02,
        5.64084072e-03,  2.10962846e-02, -2.95406887e-03, -2.29196454e-03,
       -2.07780026e-02,  9.64712407e-03, -1.38934490e-02,  1.35231548e-02,
        7.02192258e-04, -4.93811514e-03,  1.14369549e-03, -1.66686893e-03,
        1.64904871e-02, -7.04577585e-03, -5.06501059e-03, -1.82151668e-02,
        9.04714218e-03,  3.80024326e-03, -6.75275065e-03,  8.11522706e-03,
       -8.45735120e-03,  2.83040971e-03,  6.59138549e-03,  4.40290174e-03,
       -7.72921228e-03,  2.96463041e-04, -1.92350842e-03,  1.23191734e-02,
       -4.77926393e-03,  4.29258898e-03,  7.31605669e-04,  1.38225463e-02,
       -1.49166218e-02, -9.61096657e-03, -1.00440982e-03, -9.67148405e-03,
        5.82565126e-03, -2.70532102e-02, -1.30953637e-02,  3.16511775e-03,
        2.09071326e-02, -1.22663601e-02,  1.68245722e-02, -4.27372998e-03,
        2.93297736e-02, -7.34112735e-04,  9.30270467e-03, -7.15105053e-03,
       -2.00282385e-03, -1.23084913e-02,  1.69382293e-03, -2.17785676e-03,
        5.14765081e-03,  3.08377969e-03,  1.07130260e-02,  4.34360247e-03,
       -4.67651666e-03,  1.67709036e-02, -1.48252942e-02,  9.21367239e-04,
        4.47432399e-03,  1.79258201e-02,  4.70400427e-03,  5.85418948e-03,
        1.74210454e-02,  1.53547689e-02, -1.95434573e-02, -1.92398244e-03,
        1.58916176e-04,  5.39830891e-03, -2.83276920e-02,  1.31280150e-02,
        2.16750211e-03,  1.33012722e-02, -2.39546517e-03,  1.43738656e-03,
       -6.99728658e-04, -6.24253531e-03, -4.52827989e-03,  4.94454001e-03,
       -3.42791964e-04, -6.84896537e-03,  2.61988605e-03,  6.48539208e-03,
       -1.24867188e-02, -3.75809227e-03,  3.23110571e-03, -5.89689792e-03,
        1.95225015e-03, -1.10603962e-02, -2.87689550e-04, -3.99887850e-03,
       -5.70128938e-03,  9.98992713e-03, -1.00613408e-03, -6.04489155e-03,
        7.32884901e-03,  5.27675914e-04,  7.51616276e-03, -1.71491934e-03,
       -3.36483004e-03, -3.31511247e-03,  3.64890827e-03,  4.38660515e-03,
        5.86599733e-03, -8.45017019e-03,  1.42204684e-02, -7.21043273e-03,
        2.52871828e-03,  1.09289128e-02,  2.28053458e-03,  6.63519670e-03,
        9.28098043e-04, -7.93483191e-03, -4.74921363e-03, -1.10680664e-02,
        7.94794078e-03, -1.78913054e-02, -4.02793999e-03,  1.14264585e-02,
       -3.85316759e-03, -2.28145314e-03,  5.97551419e-03, -8.27524433e-03,
       -2.56184897e-03, -1.37006519e-02, -1.51792447e-02, -3.29738929e-03,
        1.70445171e-02, -5.17967747e-03,  3.12653953e-03, -1.87572266e-03,
       -4.07764430e-03, -1.13134173e-02, -7.67292451e-03,  1.00620891e-02,
        9.31140941e-04,  5.95909873e-03, -3.26368012e-03, -1.29271141e-04,
        1.16767145e-02,  2.92930253e-03, -1.27451312e-03, -3.36946981e-03,
        5.72282940e-03, -1.24772111e-04, -5.67945045e-03, -7.11120677e-03,
        4.50042401e-03,  2.52224805e-03,  2.14936364e-03, -4.41701785e-03,
        2.88634443e-02, -1.70996592e-04,  9.76890781e-04,  7.54938862e-03,
        6.66327716e-03, -1.67367783e-03, -1.27772517e-03, -8.42372947e-04,
       -1.10648576e-02, -7.74017477e-04,  7.25163149e-03,  1.10113511e-02,
        1.07839017e-02,  1.77868255e-02,  8.17801760e-03,  2.37631310e-03,
        1.33346413e-03,  7.57144466e-03, -1.50539535e-02, -5.92467941e-03,
        1.92592930e-03, -9.15219241e-03,  3.95031147e-03, -6.19893209e-03,
       -7.90335904e-03, -3.05912063e-03, -5.38219128e-03,  5.26673288e-03,
       -1.39147172e-03,  2.87303960e-03, -5.47911621e-03, -1.97957967e-03,
       -4.44110665e-03,  4.11835385e-03,  9.03293531e-04,  5.85757911e-03,
       -8.99894667e-03, -3.69951958e-03, -8.58166336e-03,  6.78014480e-03,
       -1.31685184e-02, -8.44430523e-03, -5.54095403e-03, -5.33499709e-03,
        5.49492860e-03,  1.40999179e-02, -6.75101070e-03, -8.10116676e-04,
       -6.55555632e-03,  1.35999071e-03,  6.99175097e-04,  3.66522346e-03,
        1.07518202e-02,  1.48572717e-03, -5.30832358e-03, -1.54271460e-04,
       -3.75611390e-03, -3.97528461e-03, -8.78803952e-03, -1.17842761e-03,
        7.71529661e-03, -1.32787267e-02, -9.99958463e-03, -1.16858818e-02,
        1.23140264e-04, -4.74103900e-03, -5.56737620e-03,  6.14724077e-03,
       -3.06752692e-03,  1.68636740e-02,  1.77878047e-03,  4.86924390e-03,
       -3.19999986e-03, -4.27410726e-03,  7.28418801e-03,  5.15522054e-04,
       -2.63149941e-03,  6.97001752e-04, -7.77299897e-03, -4.40128707e-03,
       -5.31377604e-03,  6.82216169e-03,  2.37959962e-03,  6.13177619e-03,
        5.02704257e-03, -8.49634634e-03, -1.06686266e-03, -9.50401257e-03,
        2.00576261e-03,  2.16556265e-03, -5.85695558e-03,  1.21252235e-02,
        1.22748775e-02, -1.35092016e-03,  8.46538679e-03, -8.58826638e-03,
       -3.56286665e-03, -4.55207629e-03, -7.66348019e-03,  9.64029700e-03,
        9.53410257e-03, -8.64278563e-03, -8.48802388e-03, -6.82254194e-03,
       -2.07264086e-03,  4.99097182e-03,  1.12205263e-02,  4.42629663e-03,
        5.60797245e-03,  1.85667509e-02, -1.11683383e-02, -4.95597692e-03,
       -1.08173243e-02,  1.90128083e-03, -1.86026432e-02, -1.10044647e-03,
        1.06557335e-03,  5.03669135e-03,  5.79854581e-04,  4.82871635e-03,
        1.09045492e-02, -3.93816454e-03,  1.00661547e-02,  6.76069871e-03,
        3.57309781e-03, -5.02485027e-03, -4.43077208e-03,  1.75827836e-02,
        2.74798231e-03, -1.36455881e-02,  9.40750596e-03, -4.03583066e-03,
        3.09208445e-03, -4.60438847e-03,  1.07881867e-03, -2.69105966e-03,
        9.29076312e-03, -1.02075719e-02, -4.56475655e-03, -5.48535785e-03,
       -1.72214980e-03, -5.63834354e-03,  1.12616144e-02, -3.27179110e-04,
       -9.15571740e-03,  2.63780826e-03,  5.12984198e-03,  4.90999818e-03,
        2.57469844e-04,  1.59815085e-04, -4.38298614e-03,  1.53438070e-03,
       -4.80002382e-03, -8.34059070e-03,  6.46456169e-04, -1.74446060e-03,
        5.73759843e-03,  4.41936952e-03,  1.27058897e-03, -6.84153916e-03,
       -1.09236296e-02, -2.97547737e-03,  7.79326537e-03, -1.32040136e-02,
        5.92850938e-04, -5.29444578e-04, -2.86855383e-03, -7.87974426e-03,
        2.94517656e-03,  6.46054501e-03,  7.06202315e-03, -9.39617826e-04,
       -6.93884712e-04,  2.10606190e-03, -4.72945246e-03,  1.51339534e-02,
       -5.31839560e-03, -2.19557069e-03, -1.40836228e-02, -5.03989753e-03,
       -4.84465267e-03,  2.42098816e-03,  2.10703140e-03, -7.69680845e-04,
        1.73602258e-03,  4.08996958e-04,  4.86715748e-03, -2.56294506e-03,
       -2.74199648e-03, -7.89048358e-03, -2.55439276e-04, -2.16190956e-03,
       -2.92109469e-03, -5.87252459e-03, -6.49980636e-03,  6.36505303e-04,
        1.28434020e-03, -5.61182688e-03, -9.16142383e-03, -6.62694881e-03,
       -3.57868713e-03,  9.32033255e-03, -2.33926401e-03, -3.46759980e-03,
        1.07808051e-02, -1.12111083e-02, -3.36543763e-03, -5.24959393e-03,
        1.85433930e-03, -1.14632472e-02, -7.52728554e-03,  6.51633667e-03,
        5.73530418e-03,  4.46413681e-03, -3.54284948e-03, -2.10560735e-03,
       -1.18606589e-02,  6.23778841e-03, -4.79028589e-03, -4.92159987e-03,
       -1.07947681e-02,  8.49895503e-03,  7.22171063e-03, -5.76148513e-03,
        2.05608948e-04,  9.53402431e-03,  3.55498443e-03,  8.89695009e-04,
        9.27089388e-03, -9.28348992e-04,  5.91706001e-03, -5.52630460e-03,
       -3.40768031e-03, -3.31594105e-03, -2.41010975e-03,  5.56045305e-03,
       -9.50888900e-03, -1.50056179e-03,  1.88776172e-03,  4.55224291e-03,
       -1.42024269e-04,  3.49815211e-03, -2.53088867e-03,  2.89083900e-03,
        1.56401866e-02, -6.58178006e-03, -4.37098822e-03, -3.28132370e-03,
       -2.11843373e-03, -9.45008730e-03,  4.54144000e-03,  4.22816642e-05,
        3.04665656e-03,  1.35111129e-03, -8.27425688e-03, -3.76932366e-03,
        1.18359330e-04, -8.71289368e-04,  2.29643450e-03,  8.69915405e-04,
       -1.87922668e-03,  6.60220542e-03,  2.53626437e-03, -1.81909865e-04])

In [192]:
len(image_embeddings)

8944

In [193]:
len(image_embeddings[0])

768

## Debug embeddings

In [194]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import normalize
from transformers import BertModel, BertTokenizer

In [195]:
def preprocess_text(text):
    text = text.lower()
    return text

In [196]:
xxx['combined_text'] = xxx['feature1'] + ' ' + xxx['feature2']
xxx['cleaned_combined_text'] = xxx['combined_text'].apply(preprocess_text)

# Tạo BERT embeddings cho văn bản
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [197]:
import torch

In [198]:
def get_bert_embeddings(text):
    inputs = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding='max_length')
    with torch.no_grad():
        outputs = model(**inputs)
    # BERT base có kích thước embedding là 768
    embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()
    return embeddings

# text_embeddings = np.vstack(
#     xxx['cleaned_combined_text'].apply(lambda x: get_bert_embeddings(x)).to_numpy()
# )

In [199]:
text_embeddings = np.vstack(get_bert_embeddings(xxx['cleaned_combined_text'][0]))

In [200]:
text_embeddings

array([[-1.32130712e-01, -4.80578125e-01,  2.61906356e-01,
         4.98509035e-04,  1.92617998e-02,  2.40128532e-01,
         1.13349840e-01,  1.76416248e-01, -1.37547314e-01,
        -3.16068172e-01, -9.78496224e-02, -1.42556384e-01,
        -1.66068539e-01,  5.95610365e-02, -1.39088720e-01,
         2.75807027e-02,  1.24800183e-01,  3.01254928e-01,
        -1.00319728e-01,  2.92990118e-01,  1.33612260e-01,
        -1.59170210e-01,  9.03117061e-02,  1.17086917e-01,
         4.02323544e-01, -5.27881086e-02, -1.23920990e-03,
         1.43134380e-02,  1.62785321e-01,  2.64486820e-01,
         1.20635331e-03, -6.07602671e-03,  1.51898682e-01,
        -1.17829554e-01,  4.28457148e-02, -3.87182057e-01,
        -1.99187919e-02, -3.18495594e-02, -4.16335613e-02,
        -9.95824933e-02, -2.50402868e-01, -6.39423504e-02,
         2.24446714e-01, -2.71887362e-01, -1.92225426e-01,
        -4.29721892e-01, -1.66247189e-01,  2.64995873e-01,
        -4.76105124e-01, -4.20513004e-02, -3.83637011e-01,
        -1.77786469e-01,  8.09589699e-02,  1.43876612e-01,
         6.85929060e-02,  3.08824003e-01, -1.33027598e-01,
         1.58328250e-01, -1.85837522e-01, -3.93068612e-01,
         7.37473667e-02, -3.24680269e-01,  9.23565477e-02,
         2.24616617e-01, -1.66878141e-02,  2.33029008e-01,
        -2.30094288e-02, -1.72935709e-01, -1.48305893e-01,
         1.46959424e-01, -8.96426067e-02,  2.45205551e-01,
         1.16420932e-01, -2.92239189e-01, -2.19903529e-01,
        -1.45852333e-02, -1.12884730e-01,  1.21205263e-01,
         3.75845909e-01,  9.38015729e-02, -2.72808429e-02,
         3.15641873e-02,  1.89835697e-01,  4.95841861e-01,
         6.45034462e-02,  2.67442882e-01, -6.55058622e-02,
         1.19342245e-01,  5.96749363e-03,  3.01417619e-01,
         7.26516321e-02, -9.98676643e-02,  2.35551953e-01,
         3.58365178e-02,  8.66854936e-02, -1.45180523e-01,
        -1.66113287e-01,  1.73596710e-01,  4.76680428e-01,
         2.35965475e-02, -3.00529063e-01, -1.35613620e-01,
        -4.73285206e-02,  2.06806660e-02, -2.90133595e-01,
        -2.01947778e-01, -8.54969304e-03, -3.78398895e-02,
         5.71457716e-03,  2.04489201e-01,  2.76107900e-02,
        -2.20877603e-02,  2.84488738e-01, -1.04900047e-01,
        -5.44357393e-03,  1.77052796e-01,  3.90127823e-02,
         1.46616064e-02,  3.07046697e-02,  1.79600060e-01,
         7.94766843e-03,  1.54295042e-01,  2.21931815e-01,
         2.96609640e-01, -3.69370803e-02,  1.22395858e-01,
        -6.40294775e-02,  3.93612772e-01, -1.47387860e-02,
        -1.19275481e-01,  7.98071828e-03,  7.46833980e-02,
        -1.68316469e-01,  1.07017815e-01, -5.10819554e-02,
        -1.64192706e-01,  1.51656657e-01,  1.03973737e-02,
         2.97844112e-01, -1.25153903e-02, -3.54179978e-01,
         4.62651491e-01,  2.71738052e-01, -2.86864877e-01,
         1.67007707e-02, -1.65912747e-01, -9.39880013e-02,
        -6.68347394e-03, -2.07736477e-01, -1.88567080e-02,
         2.92463422e-01, -1.22501709e-01,  1.73817396e-01,
        -2.03075141e-01, -1.89429879e-01,  1.92345291e-01,
         6.11555763e-03, -5.90242334e-02, -2.21425563e-01,
        -2.20615845e-02,  4.70936239e-01,  4.30437744e-01,
        -4.90242131e-02,  3.45554411e-01,  5.40286787e-02,
         1.07507808e-02, -6.75508678e-02,  4.17705923e-01,
         4.13872935e-02,  4.29504275e-01,  3.36332321e-01,
         1.98505938e-01,  4.49740797e-01,  2.27247313e-01,
        -1.90355048e-01,  2.64091611e-01, -5.97700849e-02,
         2.26201639e-01, -1.17000848e-01, -2.95819938e-02,
        -1.03406116e-01,  2.17995033e-01,  1.89359754e-01,
        -1.08523533e-01,  1.57556891e-01,  8.70022625e-02,
         7.84068406e-02,  7.28310347e-02,  7.11531099e-03,
        -2.51578271e-01, -3.23284924e-01, -2.58845389e-01,
        -4.18026373e-02, -4.62969020e-03,  4.35095541e-02,
        -2.21494824e-01, -4.32762802e-02,  4.10486877e-01,
        -1.20941982e-01,  2.37313628e-01,  4.26027864e-01,
         1.22738384e-01,  2.20431834e-01, -2.51361411e-02,
        -1.25416443e-01, -3.63363586e-02,  1.30986840e-01,
         2.89002024e-02, -1.10847510e-01, -1.94323286e-02,
         1.07715845e-01, -1.71375781e-01,  4.01002854e-01,
         5.19160479e-02,  9.02532190e-02, -4.18069735e-02,
         2.90577590e-01, -1.13077341e-02,  8.03397968e-02,
         1.52545189e-02,  3.70081306e-01, -9.31114107e-02,
        -3.56100112e-01,  1.03352115e-01, -2.13005245e-02,
         3.58622447e-02,  2.58834898e-01, -1.99628308e-01,
         1.44987702e-01,  3.55793715e-01, -2.47833490e-01,
        -2.67911732e-01, -8.53212774e-02,  8.06710571e-02,
        -9.09893811e-02,  1.84200466e-01, -1.15668746e-02,
        -9.15651023e-02,  2.16844857e-01, -1.06523603e-01,
         2.71142107e-02, -2.23270641e-03, -3.93080190e-02,
         6.92144632e-02, -2.50940442e-01, -2.84455102e-02,
         2.29143247e-01, -1.43797904e-01,  1.23462297e-01,
        -4.49476480e-01, -8.11484084e-02,  4.08695400e-01,
        -3.51869911e-02,  2.74552591e-02, -8.09885859e-02,
        -8.48175883e-02,  1.82121396e-01, -5.47155589e-02,
         2.79090226e-01,  4.20393169e-01,  4.81683873e-02,
         2.19369866e-02,  3.26988667e-01,  1.04671642e-01,
        -8.95101279e-02, -1.36081711e-03,  7.62939453e-04,
         1.76500618e-01,  1.81751043e-01,  6.48696423e-02,
        -1.74151719e-01,  8.47375989e-02, -1.79309145e-01,
         2.66606361e-01, -5.26512451e-02, -1.26955464e-01,
         1.90427542e-01,  1.17339091e-02, -1.47916168e-01,
        -1.28571644e-01, -2.14898944e-01,  2.70426311e-02,
         3.42338562e-01, -5.98337501e-02,  1.58745050e-01,
        -2.93859422e-01,  2.61856824e-01,  1.13292590e-01,
        -7.23389536e-02, -1.82122573e-01, -1.34235740e-01,
         4.31357324e-01, -2.16561005e-01, -3.69083226e-01,
         1.58360958e-01,  8.86119455e-02, -1.88984305e-01,
         2.97786176e-01,  2.37112969e-01, -9.26295519e-02,
         1.52231097e-01, -3.21977511e-02,  2.95609891e-01,
        -1.85104012e-01,  1.13354370e-01,  1.30484208e-01,
         9.59612429e-02, -3.40052843e-01, -6.40364170e+00,
         1.60598755e-01,  4.64463569e-02, -1.57005683e-01,
        -1.65389001e-01, -1.07510120e-01, -4.60514948e-02,
        -5.49661890e-02, -4.83550802e-02, -3.79212737e-01,
        -2.80465931e-04,  9.13467333e-02, -2.58339643e-01,
         3.92495543e-02, -1.34499907e-01,  3.61025095e-01,
         1.29643425e-01, -1.53862029e-01,  8.40432793e-02,
         1.53434321e-01,  9.38043296e-02, -5.11814505e-02,
         1.45528913e-01, -2.00451255e-01, -1.17974848e-01,
         1.53556019e-01,  1.13469800e-02, -2.23141149e-01,
        -2.22949624e-01, -2.25810409e-01, -6.20352104e-02,
        -1.12774789e-01,  2.10240334e-02,  2.23493315e-02,
         2.78976500e-01, -2.80020267e-01, -4.48191166e-02,
         1.65805593e-02,  3.12902451e-01,  1.46261543e-01,
         4.27815728e-02,  1.79360524e-01, -1.98173106e-01,
         3.47695559e-01,  2.40576267e-01, -2.55921692e-01,
         3.40188771e-01, -4.41722542e-01,  2.73976743e-01,
         2.26646274e-01,  4.95660678e-02, -1.18465394e-01,
        -1.85159832e-01, -4.51085418e-01, -2.00748295e-01,
         1.02644242e-01,  1.97818875e-03,  3.61489236e-01,
         5.93013316e-02, -2.72616416e-01, -2.27650911e-01,
         5.56510240e-02, -3.99764813e-03, -3.20810258e-01,
        -9.28988010e-02, -5.98195940e-04, -3.06954116e-01,
        -5.48616499e-02, -1.08850569e-01,  1.68130487e-01,
         2.26426676e-01,  6.69343118e-03,  2.31660139e-02,
        -3.06240857e-01,  1.23473763e-01, -1.01960406e-01,
         5.45359291e-02, -5.39351344e-01,  3.36780310e-01,
        -2.35310957e-01, -1.27840534e-01, -4.16934371e-01,
         3.78902495e-01,  3.09619844e-01, -1.28312737e-01,
        -3.33507992e-02,  1.79927260e-01,  2.99548600e-02,
        -1.37573957e-01,  1.79223418e-01,  3.97339463e-01,
        -8.42426866e-02, -1.90421596e-01, -3.84473689e-02,
        -3.93544324e-03,  6.52977079e-02,  1.53125376e-01,
        -5.51189065e-01,  6.19760677e-02, -2.30919868e-01,
         7.89422691e-02, -5.75489178e-02, -5.64390235e-02,
        -2.37775981e-01, -7.93055594e-02,  7.10738227e-02,
        -2.12780625e-01,  6.94753826e-02,  3.25845122e-01,
        -6.78929910e-02,  4.01482046e-01, -2.79131114e-01,
         1.42436296e-01, -2.25199252e-01,  2.83745416e-02,
        -1.10178985e-01, -8.04112479e-02,  1.28088295e-01,
        -2.13817488e-02, -1.76769763e-01,  1.01543859e-01,
         2.50536293e-01, -2.49424577e-01, -1.98201954e-01,
        -2.63947308e-01,  2.62322202e-02, -7.71389306e-02,
        -2.37330079e-01, -1.42233402e-01,  1.84340715e-01,
        -1.10091373e-01, -1.81779191e-01, -2.19640851e-01,
        -2.72523761e-01,  1.26054436e-01,  1.08669568e-02,
        -8.96360129e-02, -3.21447045e-01,  1.63200617e-01,
        -1.19876666e-02,  2.08650261e-01,  9.70781595e-02,
        -1.51902949e-03,  1.74628541e-01,  9.37879980e-02,
         3.19735169e-01, -1.73356652e-01, -9.60182548e-02,
        -9.46465805e-02,  9.64948088e-02,  9.91473049e-02,
        -1.03540674e-01, -3.32954042e-02, -1.43888772e-01,
        -2.27378398e-01, -1.33600399e-01,  3.55666041e-01,
         1.35063112e-01, -2.16268688e-01, -2.19009474e-01,
         2.63636321e-01, -2.79549479e-01, -9.23077166e-02,
         3.93938631e-01, -2.20613077e-01,  2.75668085e-01,
        -2.47801557e-01, -2.16111362e-01, -1.25634614e-02,
        -1.10986710e-01,  6.54742587e-03, -1.37484059e-01,
        -1.48470432e-01,  4.49475423e-02,  1.73663586e-01,
         2.61441350e-01,  4.64524217e-02, -6.36079013e-02,
        -1.75820634e-01,  1.73696697e-01,  1.30848736e-01,
        -1.86867058e-01,  6.67881593e-02,  8.17114264e-02,
         1.42999783e-01,  1.93829298e-01, -3.62111419e-01,
         2.28940964e-01,  6.34028241e-02,  1.55685425e-01,
         2.27758139e-01,  1.53904647e-01,  8.99831653e-02,
        -3.21790218e-01, -2.01508284e-01, -1.50936991e-01,
        -2.13749126e-01,  3.68751228e-01,  3.68827194e-01,
        -1.40332237e-01, -4.13230062e-01,  1.07777365e-01,
        -2.04547703e-01,  1.68401003e-01, -1.51613623e-01,
        -4.67998832e-02,  2.61930704e-01,  6.47733361e-02,
        -2.84100950e-01, -4.48811576e-02, -9.27679986e-03,
        -4.79344934e-01,  1.80348247e-01, -8.09885859e-02,
        -3.96406054e-01, -1.00402012e-01, -4.98737425e-01,
        -1.55996680e-01, -1.05450470e-02,  1.91057414e-01,
        -2.33687460e-01, -2.98494697e-01, -8.01328719e-02,
         1.47275031e-02, -1.46542415e-01,  1.80806816e-01,
         1.74796283e-01, -1.84591532e-01,  2.17041016e-01,
        -7.97411650e-02,  2.52437592e-01, -8.26918706e-02,
        -1.45545295e-02,  6.97630346e-02, -4.99196798e-02,
         1.53037207e-02, -3.99976611e-01, -1.13265350e-01,
         1.27385452e-01, -2.72009932e-02, -5.19805811e-02,
        -2.27151453e-01, -3.58947635e-01, -2.54014164e-01,
        -4.00681883e-01,  1.17322840e-01, -1.14154756e-01,
         9.59593430e-02, -2.14310274e-01,  3.96991491e-01,
        -6.81067780e-02, -2.46338755e-01, -3.53033878e-02,
        -4.61617112e-01, -1.25572205e-01, -4.14587975e-01,
         1.49934962e-01,  2.51317471e-01, -2.59223282e-01,
         3.92328016e-03, -5.19062765e-02,  1.24002710e-01,
        -3.29656564e-02,  3.92128676e-02, -1.76418480e-02,
         7.52978995e-02, -9.17313620e-03, -1.17343351e-01,
         2.79397927e-02,  2.00161621e-01,  1.02711782e-01,
         1.50723517e-01,  2.80332625e-01, -4.57366891e-02,
        -7.41845816e-02,  7.01623783e-02, -2.76270192e-02,
        -2.91334659e-01,  2.28041530e-01, -1.04562491e-01,
        -1.66420154e-02, -2.65286684e-01,  1.71705872e-01,
         1.77376255e-01,  7.23620877e-02, -5.60413301e-02,
        -3.88549566e-02, -1.36912435e-01, -2.11627662e-01,
         2.06987411e-01,  2.85155118e-01,  6.58864621e-03,
         4.33898997e-03, -2.03748628e-01, -1.59672827e-01,
         1.15332030e-01, -7.66973048e-02,  6.68710694e-02,
        -6.49619401e-02,  4.09574397e-02,  1.40597939e-01,
         2.46036857e-01,  2.10513696e-01, -2.41473690e-03,
         9.95092392e-02, -1.43140703e-02,  8.15885067e-02,
        -4.83965635e-01,  1.07608018e-02,  4.40208822e-01,
        -2.12363482e-01,  8.90740901e-02,  5.67807071e-02,
         2.63502419e-01, -3.64749610e-01, -1.41440243e-01,
        -2.49037951e-01, -3.24707218e-02,  8.37203488e-02,
         1.65735349e-01,  2.73644447e-01, -6.29359335e-02,
         1.53177261e-01,  1.49532214e-01, -3.05593282e-01,
         3.48349899e-01, -1.80983767e-01,  9.00380611e-02,
         1.81810427e-02,  2.17192635e-01, -6.86174491e-03,
         2.72285223e-01, -1.06113106e-02, -1.05980843e-01,
         2.91199327e-01,  1.11199141e-01, -3.23279530e-01,
        -1.42210096e-01, -5.32194525e-02,  1.46327373e-02,
         2.26535171e-01,  1.49452686e-01, -5.12509421e-02,
        -1.78770840e-01,  2.69635260e-01, -2.38245815e-01,
        -4.19224575e-02, -9.71343219e-02,  1.71081305e-01,
         1.10933036e-02,  1.31059423e-01, -6.29256293e-02,
        -1.46857500e-02, -1.47503287e-01, -8.01455081e-02,
         3.06143556e-02,  2.58365124e-01, -1.49316400e-01,
        -2.40121543e-01,  3.50208551e-01, -1.13466550e-02,
         2.35987768e-01, -2.97457367e-01, -1.82918180e-03,
        -1.98214144e-01,  1.55831557e-02, -1.02725938e-01,
         1.02697229e-02, -2.11898416e-01,  1.27640963e-01,
        -8.58409517e-03,  4.83402982e-03, -1.13053709e-01,
         1.17605038e-01,  5.78330234e-02,  2.59228677e-01,
         3.02422140e-03,  4.26272333e-01, -1.84674501e-01,
         3.39900911e-01, -1.40031695e-01,  1.52660996e-01,
        -1.39585480e-01, -8.91129225e-02, -1.89286202e-01,
        -3.79654944e-01, -1.51710361e-01,  2.51011923e-04,
        -6.84879720e-04, -4.44948673e-02, -3.22230766e-03,
        -2.45268553e-01, -4.91974801e-02,  9.12382230e-02,
         4.44179624e-02, -1.97152585e-01,  3.40343595e-01,
         3.96182269e-01,  2.36212790e-01,  9.15680826e-02,
         1.64490446e-01,  5.21150678e-02, -4.88291904e-02,
         2.10357770e-01, -4.61411960e-02,  1.20537356e-01,
         2.05589905e-01,  1.40147805e-01, -1.05749391e-01,
        -7.99807757e-02, -1.15914308e-02,  2.64871657e-01,
        -2.37172633e-01,  2.20415294e-01,  4.52686101e-02,
        -2.48215884e-01,  8.12888592e-02, -1.58735942e-02,
        -1.67199016e-01, -2.54656821e-01, -2.68456072e-01,
        -3.55147570e-01,  6.88820779e-02,  1.80961475e-01,
         1.58511221e-01,  2.25879148e-01, -9.79743712e-03,
         1.81285858e-01,  8.05563033e-02,  1.46003831e-02,
        -2.07978129e-01, -6.19591698e-02, -1.68775618e-01,
         1.28434896e-01, -2.14846760e-01,  1.81692719e-01,
        -7.06792772e-02, -2.14030460e-01, -3.53491306e-02,
        -1.53296635e-01,  6.58661723e-02, -2.47017264e-01,
        -6.35286421e-02,  4.63183522e-02,  1.94279671e-01,
         2.65250802e-01, -2.28229851e-01,  2.50935465e-01,
        -2.41400585e-01, -2.94322461e-01, -2.10735667e-02,
        -3.52898896e-01,  3.84359509e-02, -1.28072709e-01,
        -1.87154815e-01, -3.21229577e-01,  5.28530926e-02,
         3.37179415e-02, -1.27532825e-01, -1.67819113e-01]], dtype=float32)

In [201]:
# Chuyển đổi về float32
text_embeddings = text_embeddings.astype(np.float32)
image_embeddings = image_embeddings.astype(np.float32)

In [202]:
# Kiểm tra kiểu dữ liệu (dtype), kích thước (shape), và số chiều (ndim)
print("Text Embeddings:")
print("Type:", type(text_embeddings))
print("Data type (dtype):", text_embeddings.dtype)
print("Shape:", text_embeddings.shape)
print("Number of dimensions (ndim):", text_embeddings.ndim)

print("\nImage Embeddings:")
print("Type:", type(image_embeddings))
print("Data type (dtype):", image_embeddings.dtype)
print("Shape:", image_embeddings.shape)
print("Number of dimensions (ndim):", image_embeddings.ndim)

Text Embeddings:
Type: <class 'numpy.ndarray'>
Data type (dtype): float32
Shape: (1, 768)
Number of dimensions (ndim): 2

Image Embeddings:
Type: <class 'numpy.ndarray'>
Data type (dtype): float32
Shape: (8944, 768)
Number of dimensions (ndim): 2